/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\nim_test.o f:\mydocument\[programing]\python\pynimcffi\nimcache\nim_test.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>

#include <windows.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct person122009 person122009;
typedef struct vector122005 vector122005;
typedef struct man122007 man122007;
typedef struct TY122470 TY122470;
typedef struct TY122527 TY122527;
typedef struct TY13206 TY13206;
typedef struct TY122641 TY122641;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct table122130 table122130;
typedef struct keyvaluepairseq122133 keyvaluepairseq122133;
typedef struct keyvaluepair122136 keyvaluepair122136;
typedef struct table122152 table122152;
typedef struct keyvaluepairseq122155 keyvaluepairseq122155;
typedef struct keyvaluepair122158 keyvaluepair122158;
typedef struct table122086 table122086;
typedef struct keyvaluepairseq122089 keyvaluepairseq122089;
typedef struct keyvaluepair122092 keyvaluepair122092;
typedef struct table122108 table122108;
typedef struct keyvaluepairseq122111 keyvaluepairseq122111;
typedef struct keyvaluepair122114 keyvaluepair122114;
typedef struct table122218 table122218;
typedef struct keyvaluepairseq122221 keyvaluepairseq122221;
typedef struct keyvaluepair122224 keyvaluepair122224;
typedef struct table122174 table122174;
typedef struct keyvaluepairseq122177 keyvaluepairseq122177;
typedef struct keyvaluepair122180 keyvaluepair122180;
typedef struct table122196 table122196;
typedef struct keyvaluepairseq122199 keyvaluepairseq122199;
typedef struct keyvaluepair122202 keyvaluepair122202;
typedef struct tintkvtuple122025 tintkvtuple122025;
typedef struct tfloatkvtuple122029 tfloatkvtuple122029;
typedef struct tcstringkvtuple122027 tcstringkvtuple122027;
typedef struct tintlistkvtp122031 tintlistkvtp122031;
typedef struct tfloatlistkvtp122033 tfloatlistkvtp122033;
typedef struct tcstringlistkvtp122035 tcstringlistkvtp122035;
typedef struct pytype125027 pytype125027;
typedef struct TY107550 TY107550;
typedef struct table125861 table125861;
typedef struct keyvaluepairseq125864 keyvaluepairseq125864;
typedef struct keyvaluepair125867 keyvaluepair125867;
typedef struct fooHEX3Aobjecttype126777 fooHEX3Aobjecttype126777;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
typedef NU8 TY75869[32];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  person122009  {
NCSTRING Name;
NI Age;
};
struct  vector122005  {
NF X;
NF Y;
NF Z;
};
struct man122007 {
NCSTRING Field0;
NI Field1;
NI Field2;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (NCSTRING msg, void* ClEnv);
void* ClEnv;
} TY122354;
typedef N_CLOSURE_PTR(NIM_BOOL, TMP245) (NCSTRING msg);
typedef N_CLOSURE_PTR(NIM_BOOL, TMP249) (NCSTRING msg);
typedef N_CLOSURE_PTR(NIM_BOOL, TMP253) (NCSTRING msg);
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct keyvaluepair122136 {
NU8 Field0;
NCSTRING Field1;
NCSTRING Field2;
};
struct  table122130  {
keyvaluepairseq122133* Data;
NI Counter;
};
struct keyvaluepair122158 {
NU8 Field0;
NCSTRING Field1;
NimStringDesc* Field2;
};
struct  table122152  {
keyvaluepairseq122155* Data;
NI Counter;
};
struct keyvaluepair122092 {
NU8 Field0;
NCSTRING Field1;
NI Field2;
};
struct  table122086  {
keyvaluepairseq122089* Data;
NI Counter;
};
struct keyvaluepair122114 {
NU8 Field0;
NCSTRING Field1;
NF Field2;
};
struct  table122108  {
keyvaluepairseq122111* Data;
NI Counter;
};
struct keyvaluepair122224 {
NU8 Field0;
NCSTRING Field1;
TY122641* Field2;
};
struct  table122218  {
keyvaluepairseq122221* Data;
NI Counter;
};
struct keyvaluepair122180 {
NU8 Field0;
NCSTRING Field1;
TY122470* Field2;
};
struct  table122174  {
keyvaluepairseq122177* Data;
NI Counter;
};
struct keyvaluepair122202 {
NU8 Field0;
NCSTRING Field1;
TY122527* Field2;
};
struct  table122196  {
keyvaluepairseq122199* Data;
NI Counter;
};
struct tintkvtuple122025 {
NCSTRING Field0;
NI Field1;
};
struct tfloatkvtuple122029 {
NCSTRING Field0;
NF Field1;
};
struct tcstringkvtuple122027 {
NCSTRING Field0;
NCSTRING Field1;
};
struct tintlistkvtp122031 {
NCSTRING Field0;
TY122470* Field1;
};
struct tfloatlistkvtp122033 {
NCSTRING Field0;
TY122527* Field1;
};
struct tcstringlistkvtp122035 {
NCSTRING Field0;
TY122641* Field1;
};
struct  pytype125027  {
TY122470* Data;
NCSTRING Typename;
};
struct TY107550 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct keyvaluepair125867 {
NU8 Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  table125861  {
keyvaluepairseq125864* Data;
NI Counter;
};
struct  fooHEX3Aobjecttype126777  {
NF X;
NF Y;
};
typedef N_CLOSURE_PTR(NIM_BOOL, TMP319) (NCSTRING msg, void* ClEnv);
typedef NI TY125345[4];
typedef NF TY125368[2];
typedef TY107550 TY125815[3];
typedef TY107550 TY126297[1];
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct TY122470 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY122527 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY122641 {
  TGenericSeq Sup;
  NCSTRING data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122133 {
  TGenericSeq Sup;
  keyvaluepair122136 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122155 {
  TGenericSeq Sup;
  keyvaluepair122158 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122089 {
  TGenericSeq Sup;
  keyvaluepair122092 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122111 {
  TGenericSeq Sup;
  keyvaluepair122114 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122221 {
  TGenericSeq Sup;
  keyvaluepair122224 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122177 {
  TGenericSeq Sup;
  keyvaluepair122180 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122199 {
  TGenericSeq Sup;
  keyvaluepair122202 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq125864 {
  TGenericSeq Sup;
  keyvaluepair125867 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, tobool_122247)(NI x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_EXPORT N_CDECL(NimStringDesc*, cstringToString)(NCSTRING s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(person122009, getPerson)(NimStringDesc* name_122296, NI age);
N_LIB_EXPORT N_CDECL(vector122005, getVector)(NF x, NF y, NF z);
N_LIB_EXPORT N_CDECL(man122007, getMan)(NCSTRING name, NI age, NI value);
N_LIB_EXPORT N_CDECL(NCSTRING, stringToCstring)(NimStringDesc* s);
N_LIB_EXPORT N_CDECL(NCSTRING, callback_topython)(NCSTRING s, TY122354 callback);
static N_INLINE(NI, pop_122460)(TY122470** s_122468);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_LIB_EXPORT N_CDECL(NI, intPop)(TY122470** s);
static N_INLINE(NF, pop_122517)(TY122527** s_122525);
N_LIB_EXPORT N_CDECL(NF, floatPop)(TY122527** s);
static N_INLINE(NimStringDesc*, pop_122574)(TY13206** s_122582);
N_LIB_EXPORT N_CDECL(NimStringDesc*, stringPop)(TY13206** s);
static N_INLINE(NCSTRING, pop_122631)(TY122641** s_122639);
N_LIB_EXPORT N_CDECL(NCSTRING, cstringPop)(TY122641** s);
static N_INLINE(TY122470*, reverse_122687)(TY122470* x_122693);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_LIB_EXPORT N_CDECL(TY122470*, intReverse)(TY122470* s);
static N_INLINE(TY122527*, reverse_122788)(TY122527* x_122794);
N_LIB_EXPORT N_CDECL(TY122527*, floatRverse)(TY122527* s);
static N_INLINE(TY13206*, reverse_122889)(TY13206* x_122895);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_LIB_EXPORT N_CDECL(TY13206*, stringReverse)(TY13206* s);
static N_INLINE(TY122641*, reverse_122990)(TY122641* x_122996);
N_LIB_EXPORT N_CDECL(TY122641*, cstringReverse)(TY122641* s);
N_NIMCALL(TY122470*, list_123092)(NI* rest_123098, NI rest_123098Len0);
N_LIB_EXPORT N_CDECL(TY122470*, IntList)(NI* rest, NI restLen0);
N_NIMCALL(TY122527*, list_123213)(NF* rest_123219, NI rest_123219Len0);
N_LIB_EXPORT N_CDECL(TY122527*, FloatList)(NF* rest, NI restLen0);
N_NIMCALL(TY122641*, list_123303)(NCSTRING* rest_123309, NI rest_123309Len0);
N_LIB_EXPORT N_CDECL(TY122641*, CstringList)(NCSTRING* rest, NI restLen0);
N_NIMCALL(TY13206*, list_123424)(NimStringDesc** rest_123430, NI rest_123430Len0);
N_LIB_EXPORT N_CDECL(TY13206*, StringList)(NimStringDesc** rest, NI restLen0);
N_NIMCALL(void, inittable_123510)(NI initialsize_123515, table122130* Result);
N_LIB_EXPORT N_CDECL(void, CstringTable)(table122130* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, inittable_123631)(NI initialsize_123636, table122152* Result);
N_LIB_EXPORT N_CDECL(void, StringTable)(table122152* Result);
N_NIMCALL(void, inittable_123831)(NI initialsize_123836, table122086* Result);
N_LIB_EXPORT N_CDECL(void, IntTable)(table122086* Result);
N_NIMCALL(void, inittable_124031)(NI initialsize_124036, table122108* Result);
N_LIB_EXPORT N_CDECL(void, FloatTable)(table122108* Result);
N_NIMCALL(void, inittable_124231)(NI initialsize_124236, table122218* Result);
N_LIB_EXPORT N_CDECL(void, CstringListTable)(table122218* Result);
N_NIMCALL(void, inittable_124431)(NI initialsize_124436, table122174* Result);
N_LIB_EXPORT N_CDECL(void, IntListTable)(table122174* Result);
N_NIMCALL(void, inittable_124631)(NI initialsize_124636, table122196* Result);
N_LIB_EXPORT N_CDECL(void, FloatListTable)(table122196* Result);
N_LIB_EXPORT N_CDECL(tintkvtuple122025, IntKVTuple)(NCSTRING key, NI val);
N_LIB_EXPORT N_CDECL(tfloatkvtuple122029, FloatKVTuple)(NCSTRING key, NF val);
N_LIB_EXPORT N_CDECL(tcstringkvtuple122027, CstringKVTuple)(NCSTRING key, NCSTRING val);
N_LIB_EXPORT N_CDECL(void, IntListKVTp)(NCSTRING key, TY122470* val, tintlistkvtp122031* Result);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_81404, TNimType* mt);
N_LIB_EXPORT N_CDECL(void, FloatListKVTp)(NCSTRING key, TY122527* val, tfloatlistkvtp122033* Result);
N_LIB_EXPORT N_CDECL(void, CstringListKVTp)(NCSTRING key, TY122641* val, tcstringlistkvtp122035* Result);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, HEX24_125058)(pytype125027 x_125062);
N_NIMCALL(NimStringDesc*, HEX24_125073)(TY122470* x_125079);
N_NIMCALL(NimStringDesc*, collectiontostring_125083)(TY122470* x_125087, NimStringDesc* b_125089, NimStringDesc* e_125091);
N_NIMCALL(void, genpytype_125271)(TY122470* data_125275, NCSTRING typename_125277, pytype125027* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, HEX24_125372)(TY122527* x_125378);
N_NIMCALL(NimStringDesc*, collectiontostring_125382)(TY122527* x_125386, NimStringDesc* b_125388, NimStringDesc* e_125390);
N_NIMCALL(NimStringDesc*, HEX24_125653)(person122009 x_125657);
N_NIMCALL(NimStringDesc*, HEX24_125822)(TY107550 x_125826);
N_NIMCALL(void, inittable_125880)(NI initialsize_125885, table125861* Result);
N_NIMCALL(void, HEX5BHEX5DHEX3D_126025)(table125861* t_126034, NimStringDesc* key_126038, NimStringDesc* val_126040);
N_NIMCALL(NI, rawget_126043)(table125861 t_126050, NimStringDesc* key_126053);
N_NIMCALL(void, enlarge_126100)(table125861* t_126109);
N_NIMCALL(void, rawinsert_126170)(table125861* t_126179, keyvaluepairseq125864** data_126187, NimStringDesc* key_126191, NimStringDesc* val_126193);
N_NIMCALL(void, totable_126314)(TY107550* pairs_126327, NI pairs_126327Len0, table125861* Result);
N_NIMCALL(NimStringDesc*, HEX5BHEX5D_126432)(table125861 t_126439, NimStringDesc* key_126442);
N_NIMCALL(void, HEX5BHEX5DHEX3D_126480)(table122152* t_126489, NCSTRING key_126493, NimStringDesc* val_126495);
N_NIMCALL(NI, rawget_126498)(table122152 t_126505, NCSTRING key_126508);
N_NIMCALL(void, enlarge_126555)(table122152* t_126564);
N_NIMCALL(void, rawinsert_126625)(table122152* t_126634, keyvaluepairseq122155** data_126642, NCSTRING key_126646, NimStringDesc* val_126648);
N_NIMCALL(NimStringDesc*, HEX24_126803)(fooHEX3Aobjecttype126777 x_126807);
N_NIMCALL(NIM_BOOL, HEX3Aanonymous_125304)(NCSTRING msg);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, TMP347)(void* p, NI op);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimborg_low_levelInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimborg_low_levelDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nim_testInit)(void);
NIM_EXTERNC N_NOINLINE(void, nim_testDatInit)(void);
NIM_CONST TY75869 symchars_122241 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP239, "", 0);
STRING_LITERAL(TMP240, "inside nimstring to cstring: ", 29);
STRING_LITERAL(TMP241, "switch case inside nimrod", 25);
STRING_LITERAL(TMP242, "an identifier", 13);
STRING_LITERAL(TMP243, "call python callback: params: ", 30);
STRING_LITERAL(TMP244, "is it a identifier?", 19);
STRING_LITERAL(TMP246, "identifier process", 18);
STRING_LITERAL(TMP247, "cancel identifer process", 24);
STRING_LITERAL(TMP248, "a number", 8);
STRING_LITERAL(TMP250, "numeric process", 15);
STRING_LITERAL(TMP251, "cancel numeric process", 22);
STRING_LITERAL(TMP252, "not a number or an identifier", 29);
STRING_LITERAL(TMP254, "other process", 13);
STRING_LITERAL(TMP255, "cancel other process", 20);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} CNSTSEQ294 = {{3, 3}, {1,
2,
3}};
NIM_CONST TY122470* TMP292 = ((TY122470*)&CNSTSEQ294);
STRING_LITERAL(TMP300, "obj == ", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[3];
} CNSTSEQ303 = {{3, 3}, {3,
4,
5}};
NIM_CONST TY122470* TMP301 = ((TY122470*)&CNSTSEQ303);
STRING_LITERAL(TMP316, "============= Call Inside Nimrod isMainModule =============", 59);
STRING_LITERAL(TMP317, "hello", 5);
STRING_LITERAL(TMP318, "msg:", 4);
STRING_LITERAL(TMP320, "sizeof cstring:", 15);
STRING_LITERAL(TMP321, "sizeof string: ", 15);
STRING_LITERAL(TMP322, "sizeof float: ", 14);
STRING_LITERAL(TMP323, "sizeof cdouble:", 15);
NIM_CONST TY125345 TMP324 = {1,
2,
3,
4}
;
STRING_LITERAL(TMP325, "pop ilist:", 10);
STRING_LITERAL(TMP326, " ilist == ", 10);
NIM_CONST TY125368 TMP327 = {1.1230000000000000e+000,
4.4234000000000000e+000}
;
STRING_LITERAL(TMP328, "hello person", 12);
STRING_LITERAL(TMP329, "end", 3);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[4];
} CNSTSEQ332 = {{4, 4}, {1,
2,
3,
4}};
NIM_CONST TY122470* TMP330 = ((TY122470*)&CNSTSEQ332);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[4];
} CNSTSEQ334 = {{4, 4}, {3,
4,
5,
3}};
NIM_CONST TY122470* TMP332 = ((TY122470*)&CNSTSEQ334);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[2];
} CNSTSEQ336 = {{2, 2}, {1.2000000000000000e+000,
3.2142000000000003e+001}};
NIM_CONST TY122527* TMP334 = ((TY122527*)&CNSTSEQ336);
STRING_LITERAL(TMP337, "Key", 3);
STRING_LITERAL(TMP338, "value", 5);
STRING_LITERAL(TMP339, "key2", 4);
STRING_LITERAL(TMP340, "value2", 6);
STRING_LITERAL(TMP341, "key3", 4);
STRING_LITERAL(TMP342, "value3", 6);
NIM_CONST TY125815 TMP336 = {{((NimStringDesc*) &TMP337),
((NimStringDesc*) &TMP338)}
,
{((NimStringDesc*) &TMP339),
((NimStringDesc*) &TMP340)}
,
{((NimStringDesc*) &TMP341),
((NimStringDesc*) &TMP342)}
}
;
STRING_LITERAL(TMP344, "key", 3);
NIM_CONST TY126297 TMP345 = {{((NimStringDesc*) &TMP344),
((NimStringDesc*) &TMP338)}
}
;
STRING_LITERAL(TMP348, "------------", 12);
extern TFrame* frameptr_16242;
extern TNimType NTI122470; /* seq[int] */
extern TNimType NTI122527; /* seq[float] */
extern TNimType NTI13206; /* seq[string] */
extern tgcheap47016 gch_47044;
extern TNimType NTI122641; /* seq[cstring] */
extern TNimType NTI122130; /* Table */
extern TNimType NTI122152; /* Table */
extern TNimType NTI122086; /* Table */
extern TNimType NTI122108; /* Table */
extern TNimType NTI122218; /* Table */
extern TNimType NTI122174; /* Table */
extern TNimType NTI122196; /* Table */
person122009 psn_125018;
pytype125027 obj_125050;
pytype125027 oojj_125287;
TNimType NTI125027; /* PyType */
extern TNimType NTI151; /* cstring */
NCSTRING s_125298;
NimStringDesc* ss_125299;
NF sss_125301;
double ssss_125303;
TY122470* ilst_125347;
TY122470* ret_125695;
TY125815 xxx_125820;
extern TNimType NTI107550; /* tuple[nonDST: string, DST: string] */
TNimType NTI125815; /* Array constructor[0..2, tuple[string, string]] */
table125861 yyy_126021;
extern TNimType NTI125861; /* Table */
TY126297 z_126302;
TNimType NTI126297; /* Array constructor[0..0, tuple[key: string, valsss: string]] */
table125861 zz_126429;
table122152 xx_126476;
table122152 yy_126752;
NI kk_126773;
int gg_126774;
fooHEX3Aobjecttype126777* f_126781;
TNimType NTI126777; /* Foo:ObjectType */
extern TNimType NTI128; /* float */
TNimType NTI126776; /* Foo */
NI x_126836;
NI* p_126838;
NI y_126844;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NIM_BOOL, tobool_122247)(NI x) {
	NIM_BOOL result;
	nimfr("toBool", "nim_test.nim")
	result = 0;
	nimln(70, "nim_test.nim");
	nimln(70, "nim_test.nim");
	nimln(70, "nim_test.nim");
	result = !((x == 0));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_LIB_EXPORT N_CDECL(NimStringDesc*, cstringToString)(NCSTRING s) {
	NimStringDesc* result;
	NI i;
	nimfr("cstringToString", "nim_test.nim")
	result = 0;
	nimln(74, "nim_test.nim");
	result = copyString(((NimStringDesc*) &TMP239));
	nimln(75, "nim_test.nim");
	i = 0;
	{
		nimln(76, "nim_test.nim");
		while (1) {
			nimln(76, "nim_test.nim");
			nimln(76, "nim_test.nim");
			if (!(i < strlen(s))) goto LA2;
			nimln(77, "nim_test.nim");
			result = addChar(result, s[i]);
			nimln(78, "nim_test.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(person122009, getPerson)(NimStringDesc* name_122296, NI age) {
	person122009 result;
	NCSTRING name;
	person122009 LOC1;
	nimfr("getPerson", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(82, "nim_test.nim");
	name = name_122296->data;
	nimln(83, "nim_test.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Name = name;
	LOC1.Age = age;
	result = LOC1;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(vector122005, getVector)(NF x, NF y, NF z) {
	vector122005 result;
	vector122005 LOC1;
	nimfr("getVector", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(86, "nim_test.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.X = x;
	LOC1.Y = y;
	LOC1.Z = z;
	result = LOC1;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(man122007, getMan)(NCSTRING name, NI age, NI value) {
	man122007 result;
	nimfr("getMan", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(89, "nim_test.nim");
	result.Field0 = name;
	result.Field1 = age;
	result.Field2 = value;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NCSTRING, stringToCstring)(NimStringDesc* s) {
	NCSTRING result;
	nimfr("stringToCstring", "nim_test.nim")
	result = 0;
	nimln(92, "nim_test.nim");
	nimln(92, "nim_test.nim");
	nimln(92, "nim_test.nim");
	printf("%s%s\015\012", (((NimStringDesc*) &TMP240))->data, (s)->data);
	nimln(93, "nim_test.nim");
	result = s->data;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NCSTRING, callback_topython)(NCSTRING s, TY122354 callback) {
	NCSTRING result;
	nimfr("callback_topython", "nim_test.nim")
	result = 0;
	nimln(96, "nim_test.nim");
	nimln(96, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP241))->data);
	nimln(97, "nim_test.nim");
	switch (((NU8)(s[0]))) {
	case 97 ... 122:
	case 95:
	case 65 ... 90:
	case 128 ... 255:
	{
		nimln(99, "nim_test.nim");
		nimln(99, "nim_test.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP242))->data);
		nimln(100, "nim_test.nim");
		nimln(100, "nim_test.nim");
		nimln(100, "nim_test.nim");
		printf("%s%s\015\012", (((NimStringDesc*) &TMP243))->data, (((NimStringDesc*) &TMP244))->data);
		nimln(101, "nim_test.nim");
		{
			NIM_BOOL LOC4;
			nimln(101, "nim_test.nim");
			LOC4 = 0;
			LOC4 = callback.ClEnv? callback.ClPrc("is it a identifier?", callback.ClEnv):((TMP245)(callback.ClPrc))("is it a identifier?");
			if (!LOC4) goto LA5;
			nimln(101, "nim_test.nim");
			nimln(101, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP246))->data);
		}
		goto LA2;
		LA5: ;
		{
			nimln(102, "nim_test.nim");
			nimln(102, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP247))->data);
		}
		LA2: ;
	}
	break;
	case 48 ... 57:
	{
		nimln(104, "nim_test.nim");
		nimln(104, "nim_test.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP248))->data);
		nimln(105, "nim_test.nim");
		{
			NIM_BOOL LOC11;
			nimln(105, "nim_test.nim");
			LOC11 = 0;
			LOC11 = callback.ClEnv? callback.ClPrc("it\'s a number?", callback.ClEnv):((TMP249)(callback.ClPrc))("it\'s a number?");
			if (!LOC11) goto LA12;
			nimln(105, "nim_test.nim");
			nimln(105, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP250))->data);
		}
		goto LA9;
		LA12: ;
		{
			nimln(106, "nim_test.nim");
			nimln(106, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP251))->data);
		}
		LA9: ;
	}
	break;
	default:
	{
		nimln(108, "nim_test.nim");
		nimln(108, "nim_test.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP252))->data);
		nimln(109, "nim_test.nim");
		{
			NIM_BOOL LOC18;
			nimln(109, "nim_test.nim");
			LOC18 = 0;
			LOC18 = callback.ClEnv? callback.ClPrc("it\'s neither a number nor an identifier", callback.ClEnv):((TMP253)(callback.ClPrc))("it\'s neither a number nor an identifier");
			if (!LOC18) goto LA19;
			nimln(109, "nim_test.nim");
			nimln(109, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP254))->data);
		}
		goto LA16;
		LA19: ;
		{
			nimln(110, "nim_test.nim");
			nimln(110, "nim_test.nim");
			printf("%s\015\012", (((NimStringDesc*) &TMP255))->data);
		}
		LA16: ;
	}
	break;
	}
	nimln(112, "nim_test.nim");
	result = "done";
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, pop_122460)(TY122470** s_122468) {
	NI result;
	NI l;
	NI TMP256;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP256 = subInt((*s_122468)->Sup.len, 1);
	l = (NI32)(TMP256);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_122468)->Sup.len)) raiseIndexError();
	result = (*s_122468)->data[l];
	nimln(1812, "system.nim");
	(*s_122468) = (TY122470*) setLengthSeq(&((*s_122468))->Sup, sizeof(NI), l);
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NI, intPop)(TY122470** s) {
	NI result;
	nimfr("intPop", "nim_test.nim")
	result = 0;
	nimln(132, "nim_test.nim");
	result = pop_122460(s);
	popFrame();
	return result;
}

static N_INLINE(NF, pop_122517)(TY122527** s_122525) {
	NF result;
	NI l;
	NI TMP257;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP257 = subInt((*s_122525)->Sup.len, 1);
	l = (NI32)(TMP257);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_122525)->Sup.len)) raiseIndexError();
	result = (*s_122525)->data[l];
	nimln(1812, "system.nim");
	(*s_122525) = (TY122527*) setLengthSeq(&((*s_122525))->Sup, sizeof(NF), l);
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NF, floatPop)(TY122527** s) {
	NF result;
	nimfr("floatPop", "nim_test.nim")
	result = 0;
	nimln(133, "nim_test.nim");
	result = pop_122517(s);
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, pop_122574)(TY13206** s_122582) {
	NimStringDesc* result;
	NI l;
	NI TMP258;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP258 = subInt((*s_122582)->Sup.len, 1);
	l = (NI32)(TMP258);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_122582)->Sup.len)) raiseIndexError();
	result = copyString((*s_122582)->data[l]);
	nimln(1812, "system.nim");
	(*s_122582) = (TY13206*) setLengthSeq(&((*s_122582))->Sup, sizeof(NimStringDesc*), l);
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NimStringDesc*, stringPop)(TY13206** s) {
	NimStringDesc* result;
	nimfr("stringPop", "nim_test.nim")
	result = 0;
	nimln(134, "nim_test.nim");
	result = pop_122574(s);
	popFrame();
	return result;
}

static N_INLINE(NCSTRING, pop_122631)(TY122641** s_122639) {
	NCSTRING result;
	NI l;
	NI TMP259;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP259 = subInt((*s_122639)->Sup.len, 1);
	l = (NI32)(TMP259);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_122639)->Sup.len)) raiseIndexError();
	result = (*s_122639)->data[l];
	nimln(1812, "system.nim");
	(*s_122639) = (TY122641*) setLengthSeq(&((*s_122639))->Sup, sizeof(NCSTRING), l);
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(NCSTRING, cstringPop)(TY122641** s) {
	NCSTRING result;
	nimfr("cstringPop", "nim_test.nim")
	result = 0;
	nimln(135, "nim_test.nim");
	result = pop_122631(s);
	popFrame();
	return result;
}

static N_INLINE(TY122470*, reverse_122687)(TY122470* x_122693) {
	TY122470* result;
	nimfr("reverse", "nim_test.nim")
	result = 0;
	nimln(119, "nim_test.nim");
	result = (TY122470*) newSeq((&NTI122470), 0);
	{
		NI i_122739;
		NI HEX3Atmp_122759;
		NI TMP261;
		NI res_122762;
		i_122739 = 0;
		HEX3Atmp_122759 = 0;
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		TMP261 = subInt(x_122693->Sup.len, 1);
		HEX3Atmp_122759 = (NI32)(TMP261);
		nimln(1560, "system.nim");
		res_122762 = HEX3Atmp_122759;
		{
			nimln(1561, "system.nim");
			while (1) {
				nimln(1561, "system.nim");
				if (!(0 <= res_122762)) goto LA3;
				nimln(1560, "system.nim");
				i_122739 = res_122762;
				nimln(121, "nim_test.nim");
				if ((NU)(i_122739) >= (NU)(x_122693->Sup.len)) raiseIndexError();
				result = (TY122470*) incrSeq(&(result)->Sup, sizeof(NI));
				result->data[result->Sup.len-1] = x_122693->data[i_122739];
				nimln(1563, "system.nim");
				res_122762 = subInt(res_122762, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122470*, intReverse)(TY122470* s) {
	TY122470* result;
	nimfr("intReverse", "nim_test.nim")
	result = 0;
	nimln(137, "nim_test.nim");
	result = reverse_122687(s);
	popFrame();
	return result;
}

static N_INLINE(TY122527*, reverse_122788)(TY122527* x_122794) {
	TY122527* result;
	nimfr("reverse", "nim_test.nim")
	result = 0;
	nimln(119, "nim_test.nim");
	result = (TY122527*) newSeq((&NTI122527), 0);
	{
		NI i_122840;
		NI HEX3Atmp_122860;
		NI TMP263;
		NI res_122863;
		i_122840 = 0;
		HEX3Atmp_122860 = 0;
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		TMP263 = subInt(x_122794->Sup.len, 1);
		HEX3Atmp_122860 = (NI32)(TMP263);
		nimln(1560, "system.nim");
		res_122863 = HEX3Atmp_122860;
		{
			nimln(1561, "system.nim");
			while (1) {
				nimln(1561, "system.nim");
				if (!(0 <= res_122863)) goto LA3;
				nimln(1560, "system.nim");
				i_122840 = res_122863;
				nimln(121, "nim_test.nim");
				if ((NU)(i_122840) >= (NU)(x_122794->Sup.len)) raiseIndexError();
				result = (TY122527*) incrSeq(&(result)->Sup, sizeof(NF));
				result->data[result->Sup.len-1] = x_122794->data[i_122840];
				nimln(1563, "system.nim");
				res_122863 = subInt(res_122863, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122527*, floatRverse)(TY122527* s) {
	TY122527* result;
	nimfr("floatRverse", "nim_test.nim")
	result = 0;
	nimln(138, "nim_test.nim");
	result = reverse_122788(s);
	popFrame();
	return result;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(TY13206*, reverse_122889)(TY13206* x_122895) {
	TY13206* result;
	nimfr("reverse", "nim_test.nim")
	result = 0;
	nimln(119, "nim_test.nim");
	result = (TY13206*) newSeq((&NTI13206), 0);
	{
		NI i_122941;
		NI HEX3Atmp_122961;
		NI TMP264;
		NI res_122964;
		i_122941 = 0;
		HEX3Atmp_122961 = 0;
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		TMP264 = subInt(x_122895->Sup.len, 1);
		HEX3Atmp_122961 = (NI32)(TMP264);
		nimln(1560, "system.nim");
		res_122964 = HEX3Atmp_122961;
		{
			nimln(1561, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				nimln(1561, "system.nim");
				if (!(0 <= res_122964)) goto LA3;
				nimln(1560, "system.nim");
				i_122941 = res_122964;
				nimln(121, "nim_test.nim");
				if ((NU)(i_122941) >= (NU)(x_122895->Sup.len)) raiseIndexError();
				result = (TY13206*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
				LOC4 = 0;
				LOC4 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_122895->data[i_122941]);
				if (LOC4) nimGCunrefNoCycle(LOC4);
				nimln(1563, "system.nim");
				res_122964 = subInt(res_122964, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY13206*, stringReverse)(TY13206* s) {
	TY13206* result;
	nimfr("stringReverse", "nim_test.nim")
	result = 0;
	nimln(139, "nim_test.nim");
	result = reverse_122889(s);
	popFrame();
	return result;
}

static N_INLINE(TY122641*, reverse_122990)(TY122641* x_122996) {
	TY122641* result;
	nimfr("reverse", "nim_test.nim")
	result = 0;
	nimln(119, "nim_test.nim");
	result = (TY122641*) newSeq((&NTI122641), 0);
	{
		NI i_123042;
		NI HEX3Atmp_123062;
		NI TMP266;
		NI res_123065;
		i_123042 = 0;
		HEX3Atmp_123062 = 0;
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		nimln(120, "nim_test.nim");
		TMP266 = subInt(x_122996->Sup.len, 1);
		HEX3Atmp_123062 = (NI32)(TMP266);
		nimln(1560, "system.nim");
		res_123065 = HEX3Atmp_123062;
		{
			nimln(1561, "system.nim");
			while (1) {
				nimln(1561, "system.nim");
				if (!(0 <= res_123065)) goto LA3;
				nimln(1560, "system.nim");
				i_123042 = res_123065;
				nimln(121, "nim_test.nim");
				if ((NU)(i_123042) >= (NU)(x_122996->Sup.len)) raiseIndexError();
				result = (TY122641*) incrSeq(&(result)->Sup, sizeof(NCSTRING));
				result->data[result->Sup.len-1] = x_122996->data[i_123042];
				nimln(1563, "system.nim");
				res_123065 = subInt(res_123065, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122641*, cstringReverse)(TY122641* s) {
	TY122641* result;
	nimfr("cstringReverse", "nim_test.nim")
	result = 0;
	nimln(140, "nim_test.nim");
	result = reverse_122990(s);
	popFrame();
	return result;
}

N_NIMCALL(TY122470*, list_123092)(NI* rest_123098, NI rest_123098Len0) {
	TY122470* result;
	nimfr("list", "nim_test.nim")
	result = 0;
	nimln(128, "nim_test.nim");
	result = (TY122470*) newSeq((&NTI122470), 0);
	{
		NI i_123164;
		NI i_123186;
		i_123164 = 0;
		nimln(1649, "system.nim");
		i_123186 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_123186 < rest_123098Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_123186) >= (NU)(rest_123098Len0)) raiseIndexError();
				i_123164 = rest_123098[i_123186];
				nimln(130, "nim_test.nim");
				result = (TY122470*) incrSeq(&(result)->Sup, sizeof(NI));
				result->data[result->Sup.len-1] = i_123164;
				nimln(1652, "system.nim");
				i_123186 = addInt(i_123186, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122470*, IntList)(NI* rest, NI restLen0) {
	TY122470* result;
	nimfr("IntList", "nim_test.nim")
	result = 0;
	nimln(142, "nim_test.nim");
	result = list_123092(rest, restLen0);
	popFrame();
	return result;
}

N_NIMCALL(TY122527*, list_123213)(NF* rest_123219, NI rest_123219Len0) {
	TY122527* result;
	nimfr("list", "nim_test.nim")
	result = 0;
	nimln(128, "nim_test.nim");
	result = (TY122527*) newSeq((&NTI122527), 0);
	{
		NF i_123254;
		NI i_123276;
		i_123254 = 0;
		nimln(1649, "system.nim");
		i_123276 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_123276 < rest_123219Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_123276) >= (NU)(rest_123219Len0)) raiseIndexError();
				i_123254 = rest_123219[i_123276];
				nimln(130, "nim_test.nim");
				result = (TY122527*) incrSeq(&(result)->Sup, sizeof(NF));
				result->data[result->Sup.len-1] = i_123254;
				nimln(1652, "system.nim");
				i_123276 = addInt(i_123276, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122527*, FloatList)(NF* rest, NI restLen0) {
	TY122527* result;
	nimfr("FloatList", "nim_test.nim")
	result = 0;
	nimln(143, "nim_test.nim");
	result = list_123213(rest, restLen0);
	popFrame();
	return result;
}

N_NIMCALL(TY122641*, list_123303)(NCSTRING* rest_123309, NI rest_123309Len0) {
	TY122641* result;
	nimfr("list", "nim_test.nim")
	result = 0;
	nimln(128, "nim_test.nim");
	result = (TY122641*) newSeq((&NTI122641), 0);
	{
		NCSTRING i_123375;
		NI i_123397;
		i_123375 = 0;
		nimln(1649, "system.nim");
		i_123397 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_123397 < rest_123309Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_123397) >= (NU)(rest_123309Len0)) raiseIndexError();
				i_123375 = rest_123309[i_123397];
				nimln(130, "nim_test.nim");
				result = (TY122641*) incrSeq(&(result)->Sup, sizeof(NCSTRING));
				result->data[result->Sup.len-1] = i_123375;
				nimln(1652, "system.nim");
				i_123397 = addInt(i_123397, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY122641*, CstringList)(NCSTRING* rest, NI restLen0) {
	TY122641* result;
	nimfr("CstringList", "nim_test.nim")
	result = 0;
	nimln(144, "nim_test.nim");
	result = list_123303(rest, restLen0);
	popFrame();
	return result;
}

N_NIMCALL(TY13206*, list_123424)(NimStringDesc** rest_123430, NI rest_123430Len0) {
	TY13206* result;
	nimfr("list", "nim_test.nim")
	result = 0;
	nimln(128, "nim_test.nim");
	result = (TY13206*) newSeq((&NTI13206), 0);
	{
		NimStringDesc* i_123465;
		NI i_123487;
		i_123465 = 0;
		nimln(1649, "system.nim");
		i_123487 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_123487 < rest_123430Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_123487) >= (NU)(rest_123430Len0)) raiseIndexError();
				i_123465 = rest_123430[i_123487];
				nimln(130, "nim_test.nim");
				result = (TY13206*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
				LOC4 = 0;
				LOC4 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(i_123465);
				if (LOC4) nimGCunrefNoCycle(LOC4);
				nimln(1652, "system.nim");
				i_123487 = addInt(i_123487, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(TY13206*, StringList)(NimStringDesc** rest, NI restLen0) {
	TY13206* result;
	nimfr("StringList", "nim_test.nim")
	result = 0;
	nimln(145, "nim_test.nim");
	result = list_123424(rest, restLen0);
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(void, CstringTable)(table122130* Result) {
	nimfr("CstringTable", "nim_test.nim")
	nimln(147, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122130));
	inittable_123510(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, StringTable)(table122152* Result) {
	nimfr("StringTable", "nim_test.nim")
	nimln(148, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122152));
	inittable_123631(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, IntTable)(table122086* Result) {
	nimfr("IntTable", "nim_test.nim")
	nimln(149, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122086));
	inittable_123831(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, FloatTable)(table122108* Result) {
	nimfr("FloatTable", "nim_test.nim")
	nimln(150, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122108));
	inittable_124031(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, CstringListTable)(table122218* Result) {
	nimfr("CstringListTable", "nim_test.nim")
	nimln(152, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122218));
	inittable_124231(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, IntListTable)(table122174* Result) {
	nimfr("IntListTable", "nim_test.nim")
	nimln(154, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122174));
	inittable_124431(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, FloatListTable)(table122196* Result) {
	nimfr("FloatListTable", "nim_test.nim")
	nimln(155, "nim_test.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI122196));
	inittable_124631(64, Result);
	popFrame();
}

N_LIB_EXPORT N_CDECL(tintkvtuple122025, IntKVTuple)(NCSTRING key, NI val) {
	tintkvtuple122025 result;
	nimfr("IntKVTuple", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(157, "nim_test.nim");
	result.Field0 = key;
	result.Field1 = val;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(tfloatkvtuple122029, FloatKVTuple)(NCSTRING key, NF val) {
	tfloatkvtuple122029 result;
	nimfr("FloatKVTuple", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(158, "nim_test.nim");
	result.Field0 = key;
	result.Field1 = val;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(tcstringkvtuple122027, CstringKVTuple)(NCSTRING key, NCSTRING val) {
	tcstringkvtuple122027 result;
	nimfr("CstringKVTuple", "nim_test.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(159, "nim_test.nim");
	result.Field0 = key;
	result.Field1 = val;
	popFrame();
	return result;
}

N_LIB_EXPORT N_CDECL(void, IntListKVTp)(NCSTRING key, TY122470* val, tintlistkvtp122031* Result) {
	nimfr("IntListKVTp", "nim_test.nim")
	nimln(160, "nim_test.nim");
	(*Result).Field0 = key;
	genericSeqAssign((&(*Result).Field1), val, (&NTI122470));
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, FloatListKVTp)(NCSTRING key, TY122527* val, tfloatlistkvtp122033* Result) {
	nimfr("FloatListKVTp", "nim_test.nim")
	nimln(161, "nim_test.nim");
	(*Result).Field0 = key;
	genericSeqAssign((&(*Result).Field1), val, (&NTI122527));
	popFrame();
}

N_LIB_EXPORT N_CDECL(void, CstringListKVTp)(NCSTRING key, TY122641* val, tcstringlistkvtp122035* Result) {
	nimfr("CstringListKVTp", "nim_test.nim")
	nimln(162, "nim_test.nim");
	(*Result).Field0 = key;
	genericSeqAssign((&(*Result).Field1), val, (&NTI122641));
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, genpytype_125271)(TY122470* data_125275, NCSTRING typename_125277, pytype125027* Result) {
	pytype125027 LOC1;
	nimfr("genPyType", "nim_test.nim")
	nimln(206, "nim_test.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	genericSeqAssign((&LOC1.Data), data_125275, (&NTI122470));
	LOC1.Typename = typename_125277;
	unsureAsgnRef((void**) (&(*Result).Data), LOC1.Data);
	(*Result).Typename = LOC1.Typename;
	popFrame();
}

N_NIMCALL(NIM_BOOL, HEX3Aanonymous_125304)(NCSTRING msg) {
	NIM_BOOL result;
	NimStringDesc* LOC1;
	nimfr(":anonymous", "nim_test.nim")
	result = 0;
	nimln(328, "nim_test.nim");
	nimln(328, "nim_test.nim");
	nimln(328, "nim_test.nim");
	LOC1 = 0;
	LOC1 = cstrToNimstr(msg);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP318))->data, (LOC1)->data);
	nimln(329, "nim_test.nim");
	nimln(329, "nim_test.nim");
	result = NIM_FALSE;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP347)(void* p, NI op) {
	fooHEX3Aobjecttype126777* a;
	a = (fooHEX3Aobjecttype126777*)p;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_hashesDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	stdlib_tablesDatInit();
	stdlib_dynlibDatInit();
	nimborg_low_levelDatInit();
	nim_testDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_hashesInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
	stdlib_tablesInit();
	stdlib_dynlibInit();
	nimborg_low_levelInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_EXPORT N_CDECL(void, NimMainInner)(void) {
	nim_testInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fwdreason, 
                    LPVOID lpvReserved) {
	if(fwdreason == DLL_PROCESS_ATTACH) {
	NimMain();
}
	return 1;
}

NIM_EXTERNC N_NOINLINE(void, nim_testInit)(void) {
	person122009 LOC1;
	pytype125027 LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	TY122354 LOC5;
	NCSTRING LOC6;
	NimStringDesc* LOC7;
	NimStringDesc* LOC8;
	NimStringDesc* LOC9;
	NimStringDesc* LOC10;
	NimStringDesc* LOC11;
	NI LOC12;
	NimStringDesc* LOC13;
	NimStringDesc* LOC14;
	TY122527* LOC15;
	NimStringDesc* LOC16;
	NCSTRING LOC17;
	NimStringDesc* LOC18;
	person122009 LOC19;
	NimStringDesc* LOC20;
	TY122470* LOC21;
	NimStringDesc* LOC22;
	TY122470* LOC23;
	NimStringDesc* LOC24;
	TY122527* LOC25;
	NimStringDesc* LOC26;
	NimStringDesc* LOC27;
	NimStringDesc* LOC28;
	NimStringDesc* LOC29;
	NimStringDesc* LOC30;
	NimStringDesc* LOC31;
	NimStringDesc* LOC32;
	NimStringDesc* LOC33;
	NimStringDesc* LOC34;
	nimfr("nim_test", "nim_test.nim")
	nimln(315, "nim_test.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Name = "hello";
	LOC1.Age = 13;
	psn_125018 = LOC1;
	nimln(316, "nim_test.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	genericSeqAssign((&LOC2.Data), TMP292, (&NTI122470));
	LOC2.Typename = "data";
	asgnRefNoCycle((void**) (&obj_125050.Data), LOC2.Data);
	obj_125050.Typename = LOC2.Typename;
	nimln(317, "nim_test.nim");
	nimln(317, "nim_test.nim");
	nimln(317, "nim_test.nim");
	LOC3 = 0;
	LOC3 = HEX24_125058(obj_125050);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP300))->data, (LOC3)->data);
	nimln(318, "nim_test.nim");
	chckNil((void*)(&oojj_125287));
	genericReset((void*)(&oojj_125287), (&NTI125027));
	genpytype_125271(TMP301, "hello", (&oojj_125287));
	nimln(321, "nim_test.nim");
	nimln(321, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP316))->data);
	nimln(322, "nim_test.nim");
	s_125298 = "hello";
	nimln(323, "nim_test.nim");
	LOC4 = 0;
	LOC4 = ss_125299; ss_125299 = copyStringRC1(((NimStringDesc*) &TMP317));
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(324, "nim_test.nim");
	sss_125301 = 1.2343550000000001e+000;
	nimln(325, "nim_test.nim");
	ssss_125303 = 1.2243242299999999e+000;
	nimln(327, "nim_test.nim");
	nimln(327, "nim_test.nim");
	memset((void*)(&LOC5), 0, sizeof(LOC5));
	LOC5.ClPrc = ((TMP319) (HEX3Aanonymous_125304)); LOC5.ClEnv = NIM_NIL;
	LOC6 = 0;
	LOC6 = callback_topython("AnIdentifier", LOC5);
	nimln(333, "nim_test.nim");
	nimln(333, "nim_test.nim");
	nimln(333, "nim_test.nim");
	LOC7 = 0;
	LOC7 = nimIntToStr(4);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP320))->data, (LOC7)->data);
	nimln(334, "nim_test.nim");
	nimln(334, "nim_test.nim");
	nimln(334, "nim_test.nim");
	LOC8 = 0;
	LOC8 = nimIntToStr(4);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP321))->data, (LOC8)->data);
	nimln(335, "nim_test.nim");
	nimln(335, "nim_test.nim");
	nimln(335, "nim_test.nim");
	LOC9 = 0;
	LOC9 = nimIntToStr(8);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP322))->data, (LOC9)->data);
	nimln(336, "nim_test.nim");
	nimln(336, "nim_test.nim");
	nimln(336, "nim_test.nim");
	LOC10 = 0;
	LOC10 = nimIntToStr(8);
	printf("%s%s\015\012", (((NimStringDesc*) &TMP323))->data, (LOC10)->data);
	nimln(337, "nim_test.nim");
	nimln(337, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP239))->data);
	nimln(338, "nim_test.nim");
	nimln(338, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP239))->data);
	nimln(339, "nim_test.nim");
	nimln(339, "nim_test.nim");
	nimln(339, "nim_test.nim");
	LOC11 = 0;
	LOC11 = cstringToString(s_125298);
	printf("%s\015\012", (LOC11)->data);
	nimln(340, "nim_test.nim");
	asgnRefNoCycle((void**) (&ilst_125347), IntList(TMP324, 4));
	nimln(341, "nim_test.nim");
	nimln(341, "nim_test.nim");
	nimln(341, "nim_test.nim");
	nimln(341, "nim_test.nim");
	LOC12 = 0;
	LOC12 = intPop((&ilst_125347));
	LOC13 = 0;
	LOC13 = nimIntToStr(LOC12);
	nimln(341, "nim_test.nim");
	nimln(341, "nim_test.nim");
	LOC14 = 0;
	LOC14 = HEX24_125073(ilst_125347);
	printf("%s%s%s%s\015\012", (((NimStringDesc*) &TMP325))->data, (LOC13)->data, (((NimStringDesc*) &TMP326))->data, (LOC14)->data);
	nimln(342, "nim_test.nim");
	nimln(342, "nim_test.nim");
	nimln(342, "nim_test.nim");
	LOC15 = 0;
	LOC15 = FloatList(TMP327, 2);
	LOC16 = 0;
	LOC16 = HEX24_125372(LOC15);
	printf("%s\015\012", (LOC16)->data);
	nimln(344, "nim_test.nim");
	nimln(344, "nim_test.nim");
	nimln(344, "nim_test.nim");
	LOC17 = 0;
	LOC17 = stringToCstring(((NimStringDesc*) &TMP328));
	LOC18 = 0;
	LOC18 = cstrToNimstr(LOC17);
	printf("%s\015\012", (LOC18)->data);
	nimln(345, "nim_test.nim");
	nimln(345, "nim_test.nim");
	nimln(345, "nim_test.nim");
	LOC19 = getPerson(((NimStringDesc*) &TMP328), 13);
	LOC20 = 0;
	LOC20 = HEX24_125653(LOC19);
	printf("%s\015\012", (LOC20)->data);
	nimln(346, "nim_test.nim");
	nimln(346, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP329))->data);
	nimln(348, "nim_test.nim");
	genericSeqAssign((&ret_125695), TMP330, (&NTI122470));
	nimln(349, "nim_test.nim");
	nimln(349, "nim_test.nim");
	nimln(349, "nim_test.nim");
	LOC21 = 0;
	LOC21 = reverse_122687(ret_125695);
	LOC22 = 0;
	LOC22 = HEX24_125073(LOC21);
	printf("%s\015\012", (LOC22)->data);
	nimln(350, "nim_test.nim");
	nimln(350, "nim_test.nim");
	nimln(350, "nim_test.nim");
	LOC23 = 0;
	LOC23 = reverse_122687(TMP332);
	LOC24 = 0;
	LOC24 = HEX24_125073(LOC23);
	printf("%s\015\012", (LOC24)->data);
	nimln(351, "nim_test.nim");
	nimln(351, "nim_test.nim");
	nimln(351, "nim_test.nim");
	LOC25 = 0;
	LOC25 = reverse_122788(TMP334);
	LOC26 = 0;
	LOC26 = HEX24_125372(LOC25);
	printf("%s\015\012", (LOC26)->data);
	nimln(353, "nim_test.nim");
	genericAssign((void*)xxx_125820, (void*)TMP336, (&NTI125815));
	nimln(354, "nim_test.nim");
	nimln(354, "nim_test.nim");
	LOC27 = 0;
	LOC27 = HEX24_125822(xxx_125820[(0)- 0]);
	nimln(354, "nim_test.nim");
	LOC28 = 0;
	LOC28 = HEX24_125822(xxx_125820[(1)- 0]);
	nimln(354, "nim_test.nim");
	LOC29 = 0;
	LOC29 = HEX24_125822(xxx_125820[(2)- 0]);
	nimln(354, "nim_test.nim");
	printf("%s%s%s%s\015\012", (LOC27)->data, (LOC28)->data, (LOC29)->data, (xxx_125820[(2)- 0].Field0)->data);
	nimln(356, "nim_test.nim");
	chckNil((void*)(&yyy_126021));
	genericReset((void*)(&yyy_126021), (&NTI125861));
	inittable_125880(64, (&yyy_126021));
	nimln(357, "nim_test.nim");
	HEX5BHEX5DHEX3D_126025((&yyy_126021), ((NimStringDesc*) &TMP344), ((NimStringDesc*) &TMP338));
	nimln(359, "nim_test.nim");
	genericAssign((void*)z_126302, (void*)TMP345, (&NTI126297));
	nimln(360, "nim_test.nim");
	nimln(360, "nim_test.nim");
	printf("%s\015\012", (z_126302[(0)- 0].Field0)->data);
	nimln(362, "nim_test.nim");
	chckNil((void*)(&zz_126429));
	genericReset((void*)(&zz_126429), (&NTI125861));
	totable_126314(z_126302, 1, (&zz_126429));
	nimln(363, "nim_test.nim");
	nimln(363, "nim_test.nim");
	nimln(363, "nim_test.nim");
	LOC30 = 0;
	LOC30 = HEX5BHEX5D_126432(zz_126429, ((NimStringDesc*) &TMP344));
	printf("%s\015\012", (LOC30)->data);
	nimln(365, "nim_test.nim");
	chckNil((void*)(&xx_126476));
	genericReset((void*)(&xx_126476), (&NTI122152));
	inittable_125880(64, (&xx_126476));
	nimln(366, "nim_test.nim");
	HEX5BHEX5DHEX3D_126480((&xx_126476), "key", ((NimStringDesc*) &TMP338));
	nimln(368, "nim_test.nim");
	chckNil((void*)(&yy_126752));
	genericReset((void*)(&yy_126752), (&NTI122152));
	StringTable((&yy_126752));
	nimln(369, "nim_test.nim");
	HEX5BHEX5DHEX3D_126480((&yy_126752), "name", ((NimStringDesc*) &TMP317));
	nimln(372, "nim_test.nim");
	kk_126773 = 1;
	nimln(373, "nim_test.nim");
	gg_126774 = ((int) (kk_126773));
	nimln(381, "nim_test.nim");
	if (f_126781) nimGCunrefNoCycle(f_126781);
	f_126781 = (fooHEX3Aobjecttype126777*) newObjRC1((&NTI126776), sizeof(fooHEX3Aobjecttype126777));
	nimln(382, "nim_test.nim");
	nimln(382, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP348))->data);
	nimln(383, "nim_test.nim");
	nimln(383, "nim_test.nim");
	LOC31 = 0;
	LOC31 = HEX24_126803((*f_126781));
	printf("%s\015\012", (LOC31)->data);
	nimln(384, "nim_test.nim");
	nimln(384, "nim_test.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP348))->data);
	nimln(385, "nim_test.nim");
	nimln(385, "nim_test.nim");
	LOC32 = 0;
	LOC32 = nimFloatToStr((*f_126781).X);
	printf("%s\015\012", (LOC32)->data);
	nimln(386, "nim_test.nim");
	(*f_126781).Y = 1.2000000000000000e+001;
	nimln(387, "nim_test.nim");
	nimln(387, "nim_test.nim");
	LOC33 = 0;
	LOC33 = nimFloatToStr((*f_126781).Y);
	printf("%s\015\012", (LOC33)->data);
	nimln(388, "nim_test.nim");
	(*f_126781).X = 1.3500000000000000e+001;
	nimln(389, "nim_test.nim");
	x_126836 = 3;
	nimln(390, "nim_test.nim");
	p_126838 = (&x_126836);
	nimln(391, "nim_test.nim");
	nimln(391, "nim_test.nim");
	LOC34 = 0;
	LOC34 = nimIntToStr((*p_126838));
	printf("%s\015\012", (LOC34)->data);
	nimln(392, "nim_test.nim");
	(*p_126838) = 42;
	nimln(393, "nim_test.nim");
	y_126844 = 12;
	nimln(394, "nim_test.nim");
	p_126838 = (&y_126844);
	nimln(395, "nim_test.nim");
	p_126838 = NIM_NIL;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nim_testDatInit)(void) {
static TNimNode* TMP303[2];
static TNimNode* TMP346[2];
static TNimNode TMP131[6];
NTI125027.size = sizeof(pytype125027);
NTI125027.kind = 18;
NTI125027.base = 0;
NTI125027.flags = 2;
TMP303[0] = &TMP131[1];
TMP131[1].kind = 1;
TMP131[1].offset = offsetof(pytype125027, Data);
TMP131[1].typ = (&NTI122470);
TMP131[1].name = "data";
TMP303[1] = &TMP131[2];
TMP131[2].kind = 1;
TMP131[2].offset = offsetof(pytype125027, Typename);
TMP131[2].typ = (&NTI151);
TMP131[2].name = "typename";
TMP131[0].len = 2; TMP131[0].kind = 2; TMP131[0].sons = &TMP303[0];
NTI125027.node = &TMP131[0];
NTI125815.size = sizeof(TY125815);
NTI125815.kind = 4;
NTI125815.base = (&NTI107550);
NTI125815.flags = 2;
NTI126297.size = sizeof(TY126297);
NTI126297.kind = 4;
NTI126297.base = (&NTI107550);
NTI126297.flags = 2;
NTI126777.size = sizeof(fooHEX3Aobjecttype126777);
NTI126777.kind = 18;
NTI126777.base = 0;
NTI126777.flags = 3;
TMP346[0] = &TMP131[4];
TMP131[4].kind = 1;
TMP131[4].offset = offsetof(fooHEX3Aobjecttype126777, X);
TMP131[4].typ = (&NTI128);
TMP131[4].name = "x";
TMP346[1] = &TMP131[5];
TMP131[5].kind = 1;
TMP131[5].offset = offsetof(fooHEX3Aobjecttype126777, Y);
TMP131[5].typ = (&NTI128);
TMP131[5].name = "y";
TMP131[3].len = 2; TMP131[3].kind = 2; TMP131[3].sons = &TMP346[0];
NTI126777.node = &TMP131[3];
NTI126776.size = sizeof(fooHEX3Aobjecttype126777*);
NTI126776.kind = 22;
NTI126776.base = (&NTI126777);
NTI126776.flags = 2;
NTI126776.marker = TMP347;
}

