/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\nim_test.o f:\mydocument\[programing]\python\pynimcffi\nimcache\nim_test.h */
#ifndef __nim_test__
#define __nim_test__
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct person122009 person122009;
typedef struct vector122005 vector122005;
typedef struct man122007 man122007;
typedef struct TY122470 TY122470;
typedef struct TY122527 TY122527;
typedef struct TY13206 TY13206;
typedef struct TY122641 TY122641;
typedef struct table122130 table122130;
typedef struct keyvaluepairseq122133 keyvaluepairseq122133;
typedef struct keyvaluepair122136 keyvaluepair122136;
typedef struct table122152 table122152;
typedef struct keyvaluepairseq122155 keyvaluepairseq122155;
typedef struct keyvaluepair122158 keyvaluepair122158;
typedef struct table122086 table122086;
typedef struct keyvaluepairseq122089 keyvaluepairseq122089;
typedef struct keyvaluepair122092 keyvaluepair122092;
typedef struct table122108 table122108;
typedef struct keyvaluepairseq122111 keyvaluepairseq122111;
typedef struct keyvaluepair122114 keyvaluepair122114;
typedef struct table122218 table122218;
typedef struct keyvaluepairseq122221 keyvaluepairseq122221;
typedef struct keyvaluepair122224 keyvaluepair122224;
typedef struct table122174 table122174;
typedef struct keyvaluepairseq122177 keyvaluepairseq122177;
typedef struct keyvaluepair122180 keyvaluepair122180;
typedef struct table122196 table122196;
typedef struct keyvaluepairseq122199 keyvaluepairseq122199;
typedef struct keyvaluepair122202 keyvaluepair122202;
typedef struct tintkvtuple122025 tintkvtuple122025;
typedef struct tfloatkvtuple122029 tfloatkvtuple122029;
typedef struct tcstringkvtuple122027 tcstringkvtuple122027;
typedef struct tintlistkvtp122031 tintlistkvtp122031;
typedef struct tfloatlistkvtp122033 tfloatlistkvtp122033;
typedef struct tcstringlistkvtp122035 tcstringlistkvtp122035;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  person122009  {
NCSTRING Name;
NI Age;
};
struct  vector122005  {
NF X;
NF Y;
NF Z;
};
struct man122007 {
NCSTRING Field0;
NI Field1;
NI Field2;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (NCSTRING msg, void* ClEnv);
void* ClEnv;
} TY122354;
struct keyvaluepair122136 {
NU8 Field0;
NCSTRING Field1;
NCSTRING Field2;
};
struct  table122130  {
keyvaluepairseq122133* Data;
NI Counter;
};
struct keyvaluepair122158 {
NU8 Field0;
NCSTRING Field1;
NimStringDesc* Field2;
};
struct  table122152  {
keyvaluepairseq122155* Data;
NI Counter;
};
struct keyvaluepair122092 {
NU8 Field0;
NCSTRING Field1;
NI Field2;
};
struct  table122086  {
keyvaluepairseq122089* Data;
NI Counter;
};
struct keyvaluepair122114 {
NU8 Field0;
NCSTRING Field1;
NF Field2;
};
struct  table122108  {
keyvaluepairseq122111* Data;
NI Counter;
};
struct keyvaluepair122224 {
NU8 Field0;
NCSTRING Field1;
TY122641* Field2;
};
struct  table122218  {
keyvaluepairseq122221* Data;
NI Counter;
};
struct keyvaluepair122180 {
NU8 Field0;
NCSTRING Field1;
TY122470* Field2;
};
struct  table122174  {
keyvaluepairseq122177* Data;
NI Counter;
};
struct keyvaluepair122202 {
NU8 Field0;
NCSTRING Field1;
TY122527* Field2;
};
struct  table122196  {
keyvaluepairseq122199* Data;
NI Counter;
};
struct tintkvtuple122025 {
NCSTRING Field0;
NI Field1;
};
struct tfloatkvtuple122029 {
NCSTRING Field0;
NF Field1;
};
struct tcstringkvtuple122027 {
NCSTRING Field0;
NCSTRING Field1;
};
struct tintlistkvtp122031 {
NCSTRING Field0;
TY122470* Field1;
};
struct tfloatlistkvtp122033 {
NCSTRING Field0;
TY122527* Field1;
};
struct tcstringlistkvtp122035 {
NCSTRING Field0;
TY122641* Field1;
};
struct TY122470 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY122527 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY122641 {
  TGenericSeq Sup;
  NCSTRING data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122133 {
  TGenericSeq Sup;
  keyvaluepair122136 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122155 {
  TGenericSeq Sup;
  keyvaluepair122158 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122089 {
  TGenericSeq Sup;
  keyvaluepair122092 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122111 {
  TGenericSeq Sup;
  keyvaluepair122114 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122221 {
  TGenericSeq Sup;
  keyvaluepair122224 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122177 {
  TGenericSeq Sup;
  keyvaluepair122180 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122199 {
  TGenericSeq Sup;
  keyvaluepair122202 data[SEQ_DECL_SIZE];
};
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(NI, getRefcount)(void* p);
N_LIB_IMPORT N_CDECL(NimStringDesc*, cstringToString)(NCSTRING s);
N_LIB_IMPORT N_CDECL(person122009, getPerson)(NimStringDesc* name_122296, NI age);
N_LIB_IMPORT N_CDECL(vector122005, getVector)(NF x, NF y, NF z);
N_LIB_IMPORT N_CDECL(man122007, getMan)(NCSTRING name, NI age, NI value);
N_LIB_IMPORT N_CDECL(NCSTRING, stringToCstring)(NimStringDesc* s);
N_LIB_IMPORT N_CDECL(NCSTRING, callback_topython)(NCSTRING s, TY122354 callback);
N_LIB_IMPORT N_CDECL(NI, intPop)(TY122470** s);
N_LIB_IMPORT N_CDECL(NF, floatPop)(TY122527** s);
N_LIB_IMPORT N_CDECL(NimStringDesc*, stringPop)(TY13206** s);
N_LIB_IMPORT N_CDECL(NCSTRING, cstringPop)(TY122641** s);
N_LIB_IMPORT N_CDECL(TY122470*, intReverse)(TY122470* s);
N_LIB_IMPORT N_CDECL(TY122527*, floatRverse)(TY122527* s);
N_LIB_IMPORT N_CDECL(TY13206*, stringReverse)(TY13206* s);
N_LIB_IMPORT N_CDECL(TY122641*, cstringReverse)(TY122641* s);
N_LIB_IMPORT N_CDECL(TY122470*, IntList)(NI* rest, NI restLen0);
N_LIB_IMPORT N_CDECL(TY122527*, FloatList)(NF* rest, NI restLen0);
N_LIB_IMPORT N_CDECL(TY122641*, CstringList)(NCSTRING* rest, NI restLen0);
N_LIB_IMPORT N_CDECL(TY13206*, StringList)(NimStringDesc** rest, NI restLen0);
N_LIB_IMPORT N_CDECL(void, CstringTable)(table122130* Result);
N_LIB_IMPORT N_CDECL(void, StringTable)(table122152* Result);
N_LIB_IMPORT N_CDECL(void, IntTable)(table122086* Result);
N_LIB_IMPORT N_CDECL(void, FloatTable)(table122108* Result);
N_LIB_IMPORT N_CDECL(void, CstringListTable)(table122218* Result);
N_LIB_IMPORT N_CDECL(void, IntListTable)(table122174* Result);
N_LIB_IMPORT N_CDECL(void, FloatListTable)(table122196* Result);
N_LIB_IMPORT N_CDECL(tintkvtuple122025, IntKVTuple)(NCSTRING key, NI val);
N_LIB_IMPORT N_CDECL(tfloatkvtuple122029, FloatKVTuple)(NCSTRING key, NF val);
N_LIB_IMPORT N_CDECL(tcstringkvtuple122027, CstringKVTuple)(NCSTRING key, NCSTRING val);
N_LIB_IMPORT N_CDECL(void, IntListKVTp)(NCSTRING key, TY122470* val, tintlistkvtp122031* Result);
N_LIB_IMPORT N_CDECL(void, FloatListKVTp)(NCSTRING key, TY122527* val, tfloatlistkvtp122033* Result);
N_LIB_IMPORT N_CDECL(void, CstringListKVTp)(NCSTRING key, TY122641* val, tcstringlistkvtp122035* Result);
N_LIB_IMPORT N_CDECL(void, NimMain)(void);
#endif /* __nim_test__ */
