/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\NimBorg_low_level.o f:\mydocument\[programing]\python\pynimcffi\nimcache\NimBorg_low_level.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct tpyobject117591 tpyobject117591;
typedef struct tpycodeobject117663 tpycodeobject117663;
typedef struct tfrozen117597 tfrozen117597;
typedef struct tpyintobject117593 tpyintobject117593;
typedef struct tpytypeobject117643 tpytypeobject117643;
typedef struct tpynumbermethods117573 tpynumbermethods117573;
typedef struct tpysequencemethods117577 tpysequencemethods117577;
typedef struct tpymappingmethods117581 tpymappingmethods117581;
typedef struct tpybufferprocs117585 tpybufferprocs117585;
typedef struct tpymethoddef117603 tpymethoddef117603;
typedef struct tpymemberdef117607 tpymemberdef117607;
typedef struct tpygetsetdef117615 tpygetsetdef117615;
typedef struct tpybuffer117665 tpybuffer117665;
typedef N_CDECL_PTR(NI, TY118238) (tpyobject117591* args, NCSTRING format, ...);
typedef N_CDECL_PTR(NI, TY118243) (tpyobject117591* args, NCSTRING format, void* x1, void* x2, void* x3, ...);
typedef N_CDECL_PTR(tpyobject117591*, TY118251) (NCSTRING format, ...);
typedef N_CDECL_PTR(NI, TY118255) (tpycodeobject117663* co, NI addrq);
typedef N_CDECL_PTR(NCSTRING, TY118260) (void);
struct  tpyobject117591  {
NI Obrefcnt;
tpytypeobject117643* Obtype;
};
struct  tpycodeobject117663  {
  tpyobject117591 Sup;
NI Coargcount;
NI Conlocals;
NI Costacksize;
NI Coflags;
tpyobject117591* Cocode;
tpyobject117591* Coconsts;
tpyobject117591* Conames;
tpyobject117591* Covarnames;
tpyobject117591* Cofreevars;
tpyobject117591* Cocellvars;
tpyobject117591* Cofilename;
tpyobject117591* Coname;
NI Cofirstlineno;
tpyobject117591* Colnotab;
};
struct  tfrozen117597  {
NCSTRING Name;
NI8* Code;
NI Size;
};
struct  tpyintobject117593  {
  tpyobject117591 Sup;
NI32 Obival;
};
typedef N_CDECL_PTR(void, tpydestructor117519) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI, tprintfunc117521) (tpyobject117591* ob, FILE* f, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tgetattrfunc117523) (tpyobject117591* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, tsetattrfunc117525) (tpyobject117591* ob1, NCSTRING name, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tcmpfunc117527) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, treprfunc117529) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI32, thashfunc117531) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, tternaryfunc117503) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(tpyobject117591*, tgetattrofunc117533) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tsetattrofunc117535) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tvisitproc117551) (tpyobject117591* ob1, void* p);
typedef N_CDECL_PTR(NI, ttraverseproc117553) (tpyobject117591* ob1, tvisitproc117551 prc, void* p);
typedef N_CDECL_PTR(NI, tinquiry117505) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, trichcmpfunc117555) (tpyobject117591* ob1, tpyobject117591* ob2, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tgetiterfunc117557) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, titernextfunc117559) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, tdescrgetfunc117561) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tdescrsetfunc117563) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tinitproc117565) (tpyobject117591* self, tpyobject117591* args, tpyobject117591* kwds);
typedef N_CDECL_PTR(tpyobject117591*, tallocfunc117569) (tpytypeobject117643* self, NI nitems);
typedef N_CDECL_PTR(tpyobject117591*, tnewfunc117567) (tpytypeobject117643* subtype, tpyobject117591* args, tpyobject117591* kwds);
struct  tpytypeobject117643  {
  tpyobject117591 Sup;
NI Obsize;
NCSTRING Tpname;
NI Tpbasicsize;
NI Tpitemsize;
tpydestructor117519 Tpdealloc;
tprintfunc117521 Tpprint;
tgetattrfunc117523 Tpgetattr;
tsetattrfunc117525 Tpsetattr;
tcmpfunc117527 Tpcompare;
treprfunc117529 Tprepr;
tpynumbermethods117573* Tpasnumber;
tpysequencemethods117577* Tpassequence;
tpymappingmethods117581* Tpasmapping;
thashfunc117531 Tphash;
tternaryfunc117503 Tpcall;
treprfunc117529 Tpstr;
tgetattrofunc117533 Tpgetattro;
tsetattrofunc117535 Tpsetattro;
tpybufferprocs117585* Tpasbuffer;
NI32 Tpflags;
NCSTRING Tpdoc;
ttraverseproc117553 Tptraverse;
tinquiry117505 Tpclear;
trichcmpfunc117555 Tprichcompare;
NI32 Tpweaklistoffset;
tgetiterfunc117557 Tpiter;
titernextfunc117559 Tpiternext;
tpymethoddef117603* Tpmethods;
tpymemberdef117607* Tpmembers;
tpygetsetdef117615* Tpgetset;
tpytypeobject117643* Tpbase;
tpyobject117591* Tpdict;
tdescrgetfunc117561 Tpdescrget;
tdescrsetfunc117563 Tpdescrset;
NI32 Tpdictoffset;
tinitproc117565 Tpinit;
tallocfunc117569 Tpalloc;
tnewfunc117567 Tpnew;
tpydestructor117519 Tpfree;
tinquiry117505 Tpisgc;
tpyobject117591* Tpbases;
tpyobject117591* Tpmro;
tpyobject117591* Tpcache;
tpyobject117591* Tpsubclasses;
tpyobject117591* Tpweaklist;
void* Tpxxx7;
void* Tpxxx8;
};
typedef N_CDECL_PTR(tpyobject117591*, tbinaryfunc117501) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, tunaryfunc117499) (tpyobject117591* ob1);
typedef N_CDECL_PTR(NI, tcoercion117507) (tpyobject117591** ob1, tpyobject117591** ob2);
struct  tpynumbermethods117573  {
tbinaryfunc117501 Nbadd;
tbinaryfunc117501 Nbsubstract;
tbinaryfunc117501 Nbmultiply;
tbinaryfunc117501 Nbdivide;
tbinaryfunc117501 Nbremainder;
tbinaryfunc117501 Nbdivmod;
tternaryfunc117503 Nbpower;
tunaryfunc117499 Nbnegative;
tunaryfunc117499 Nbpositive;
tunaryfunc117499 Nbabsolute;
tinquiry117505 Nbnonzero;
tunaryfunc117499 Nbinvert;
tbinaryfunc117501 Nblshift;
tbinaryfunc117501 Nbrshift;
tbinaryfunc117501 Nband;
tbinaryfunc117501 Nbxor;
tbinaryfunc117501 Nbor;
tcoercion117507 Nbcoerce;
tunaryfunc117499 Nbint;
tunaryfunc117499 Nblong;
tunaryfunc117499 Nbfloat;
tunaryfunc117499 Nboct;
tunaryfunc117499 Nbhex;
tbinaryfunc117501 Nbinplaceadd;
tbinaryfunc117501 Nbinplacesubtract;
tbinaryfunc117501 Nbinplacemultiply;
tbinaryfunc117501 Nbinplacedivide;
tbinaryfunc117501 Nbinplaceremainder;
tternaryfunc117503 Nbinplacepower;
tbinaryfunc117501 Nbinplacelshift;
tbinaryfunc117501 Nbinplacershift;
tbinaryfunc117501 Nbinplaceand;
tbinaryfunc117501 Nbinplacexor;
tbinaryfunc117501 Nbinplaceor;
tbinaryfunc117501 Nbfloordivide;
tbinaryfunc117501 Nbtruedivide;
tbinaryfunc117501 Nbinplacefloordivide;
tbinaryfunc117501 Nbinplacetruedivide;
};
typedef N_CDECL_PTR(tpyobject117591*, tintargfunc117509) (tpyobject117591* ob1, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tintintargfunc117511) (tpyobject117591* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, tintobjargproc117513) (tpyobject117591* ob1, NI i, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tintintobjargproc117515) (tpyobject117591* ob1, NI i1, NI i2, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tobjobjproc117549) (tpyobject117591* ob1, tpyobject117591* ob2);
struct  tpysequencemethods117577  {
tinquiry117505 Sqlength;
tbinaryfunc117501 Sqconcat;
tintargfunc117509 Sqrepeat;
tintargfunc117509 Sqitem;
tintintargfunc117511 Sqslice;
tintobjargproc117513 Sqassitem;
tintintobjargproc117515 Sqassslice;
tobjobjproc117549 Sqcontains;
tbinaryfunc117501 Sqinplaceconcat;
tintargfunc117509 Sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, tobjobjargproc117517) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
struct  tpymappingmethods117581  {
tinquiry117505 Mplength;
tbinaryfunc117501 Mpsubscript;
tobjobjargproc117517 Mpasssubscript;
};
typedef N_CDECL_PTR(NI, tgetreadbufferproc117537) (tpyobject117591* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, tgetwritebufferproc117539) (tpyobject117591* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, tgetsegcountproc117541) (tpyobject117591* ob1, NI i);
typedef N_CDECL_PTR(NI, tgetcharbufferproc117543) (tpyobject117591* ob1, NI i, NCSTRING pstr);
typedef N_CDECL_PTR(NI, tgetbufferproc117545) (tpyobject117591* a, tpybuffer117665* buf, NI c);
typedef N_CDECL_PTR(void, treleasebufferproc117547) (tpyobject117591* a, tpybuffer117665* buf);
struct  tpybufferprocs117585  {
tgetreadbufferproc117537 Bfgetreadbuffer;
tgetwritebufferproc117539 Bfgetwritebuffer;
tgetsegcountproc117541 Bfgetsegcount;
tgetcharbufferproc117543 Bfgetcharbuffer;
tgetbufferproc117545 Bfgetbuffer;
treleasebufferproc117547 Bfreleasebuffer;
};
typedef struct {
N_NIMCALL_PTR(tpyobject117591*, ClPrc) (tpyobject117591* self, tpyobject117591* args, void* ClEnv);
void* ClEnv;
} TY117890;
struct  tpymethoddef117603  {
NCSTRING Mlname;
TY117890 Mlmeth;
NI Mlflags;
NCSTRING Mldoc;
};
struct  tpymemberdef117607  {
NCSTRING Name;
NI Thetype;
NI Offset;
NI Flags;
NCSTRING Doc;
};
typedef N_CDECL_PTR(tpyobject117591*, tgetter117609) (tpyobject117591* obj, void* context);
typedef N_CDECL_PTR(NI, tsetter117611) (tpyobject117591* obj, tpyobject117591* value, void* context);
struct  tpygetsetdef117615  {
NCSTRING Name;
tgetter117609 Get;
tsetter117611 Setter;
NCSTRING Doc;
void* Closure;
};
typedef int TY118015[2];
struct  tpybuffer117665  {
void* Buf;
tpyobject117591* Obj;
int Length;
int Itemsize;
int Readonly;
int Ndim;
NCSTRING Format;
NI32* Shape;
NI32* Strides;
NI32* Suboffsets;
TY118015 Smalltable;
void* Internal;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
TY118238 pyargparse_118242;
TY118243 pyargparsetuple_118250;
TY118251 pybuildvalue_118254;
TY118255 pycodeaddr2line_118259;
TY118260 dllpygetbuildinfo_118262;
NI* pydebugflag_118281;
NI* pyverboseflag_118282;
NI* pyinteractiveflag_118283;
NI* pyoptimizeflag_118284;
NI* pynositeflag_118285;
NI* pyuseclassexceptionsflag_118286;
NI* pyfrozenflag_118287;
NI* pytabcheckflag_118288;
NI* pyunicodeflag_118289;
NI* pyignoreenvironmentflag_118290;
NI* pydivisionwarningflag_118291;
tfrozen117597** pyimportfrozenmodules_118292;
tpyobject117591* pynone_118293;
tpyobject117591* pyellipsis_118294;
tpyintobject117593* pyfalse_118295;
tpyintobject117593* pytrue_118296;
tpyobject117591* pynotimplemented_118297;
tpyobject117591** pyexcattributeerror_118298;
tpyobject117591** pyexceoferror_118299;
tpyobject117591** pyexcioerror_118300;
tpyobject117591** pyexcimporterror_118301;
tpyobject117591** pyexcindexerror_118302;
tpyobject117591** pyexckeyerror_118303;
tpyobject117591** pyexckeyboardinterrupt_118304;
tpyobject117591** pyexcmemoryerror_118305;
tpyobject117591** pyexcnameerror_118306;
tpyobject117591** pyexcoverflowerror_118307;
tpyobject117591** pyexcruntimeerror_118308;
tpyobject117591** pyexcsyntaxerror_118309;
tpyobject117591** pyexcsystemerror_118310;
tpyobject117591** pyexcsystemexit_118311;
tpyobject117591* pyexctypeerror_118312;
tpyobject117591** pyexcvalueerror_118313;
tpyobject117591** pyexczerodivisionerror_118314;
tpyobject117591** pyexcarithmeticerror_118315;
tpyobject117591** pyexcexception_118316;
tpyobject117591** pyexcfloatingpointerror_118317;
tpyobject117591** pyexclookuperror_118318;
tpyobject117591** pyexcstandarderror_118319;
tpyobject117591** pyexcassertionerror_118320;
tpyobject117591** pyexcenvironmenterror_118321;
tpyobject117591** pyexcindentationerror_118322;
tpyobject117591** pyexcmemoryerrorinst_118323;
tpyobject117591** pyexcnotimplementederror_118324;
tpyobject117591** pyexcoserror_118325;
tpyobject117591** pyexctaberror_118326;
tpyobject117591** pyexcunboundlocalerror_118327;
tpyobject117591** pyexcunicodeerror_118328;
tpyobject117591** pyexcwarning_118329;
tpyobject117591** pyexcdeprecationwarning_118330;
tpyobject117591** pyexcruntimewarning_118331;
tpyobject117591** pyexcsyntaxwarning_118332;
tpyobject117591** pyexcuserwarning_118333;
tpyobject117591** pyexcoverflowwarning_118334;
tpyobject117591** pyexcreferenceerror_118335;
tpyobject117591** pyexcstopiteration_118336;
tpyobject117591** pyexcfuturewarning_118337;
tpyobject117591** pyexcpendingdeprecationwarning_118338;
tpyobject117591** pyexcunicodedecodeerror_118339;
tpyobject117591** pyexcunicodeencodeerror_118340;
tpyobject117591** pyexcunicodetranslateerror_118341;
tpytypeobject117643* pytypetype_118342;
tpytypeobject117643* pycfunctiontype_118343;
tpytypeobject117643* pycobjecttype_118344;
tpytypeobject117643* pyclasstype_118345;
tpytypeobject117643* pycodetype_118346;
tpytypeobject117643* pycomplextype_118347;
tpytypeobject117643* pydicttype_118348;
tpytypeobject117643* pyfiletype_118349;
tpytypeobject117643* pyfloattype_118350;
tpytypeobject117643* pyframetype_118351;
tpytypeobject117643* pyfunctiontype_118352;
tpytypeobject117643* pyinstancetype_118353;
tpytypeobject117643* pylisttype_118354;
tpytypeobject117643* pylongtype_118355;
tpytypeobject117643* pymethodtype_118356;
tpytypeobject117643* pymoduletype_118357;
tpytypeobject117643* pyobjecttype_118358;
tpytypeobject117643* pyrangetype_118359;
tpytypeobject117643* pyslicetype_118360;
tpytypeobject117643* pybytestype_118361;
tpytypeobject117643* pytupletype_118362;
tpytypeobject117643* pybaseobjecttype_118363;
tpytypeobject117643* pybuffertype_118364;
tpytypeobject117643* pycallitertype_118365;
tpytypeobject117643* pycelltype_118366;
tpytypeobject117643* pyclassmethodtype_118367;
tpytypeobject117643* pypropertytype_118368;
tpytypeobject117643* pyseqitertype_118369;
tpytypeobject117643* pystaticmethodtype_118370;
tpytypeobject117643* pysupertype_118371;
tpytypeobject117643* pysymtableentrytype_118372;
tpytypeobject117643* pytracebacktype_118373;
tpytypeobject117643* pyunicodetype_118374;
tpytypeobject117643* pywrapperdescrtype_118375;
tpytypeobject117643* pybasestringtype_118376;
tpytypeobject117643* pybooltype_118377;
tpytypeobject117643* pyenumtype_118378;
void* lib_121580;
extern TFrame* frameptr_16242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, nimborg_low_levelInit)(void) {
	nimfr("low_level", "low_level.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimborg_low_levelDatInit)(void) {
}

