/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\macropy\anothermacropy\karnickel-py3\nimcache\NimBorg_high_level.o f:\mydocument\[programing]\python\macropy\anothermacropy\karnickel-py3\nimcache\NimBorg_high_level.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct epython127012 epython127012;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct tpyobject117591 tpyobject117591;
typedef struct pyref127008 pyref127008;
typedef struct tpytypeobject117643 tpytypeobject117643;
typedef struct tpynumbermethods117573 tpynumbermethods117573;
typedef struct tpysequencemethods117577 tpysequencemethods117577;
typedef struct tpymappingmethods117581 tpymappingmethods117581;
typedef struct tpybufferprocs117585 tpybufferprocs117585;
typedef struct tpymethoddef117603 tpymethoddef117603;
typedef struct tpymemberdef117607 tpymemberdef117607;
typedef struct tpygetsetdef117615 tpygetsetdef117615;
typedef struct tpybuffer117665 tpybuffer117665;
typedef struct typedpybuffer1d128111 typedpybuffer1d128111;
typedef struct epynotsupported127014 epynotsupported127014;
typedef struct epytypeerror127016 epytypeerror127016;
typedef struct context127018 context127018;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, TY118602) (void);
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  epython127012  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct  pyref127008  {
TNimType* m_type;
tpyobject117591* P;
};
struct  tpyobject117591  {
NI Obrefcnt;
tpytypeobject117643* Obtype;
};
typedef N_CDECL_PTR(void, tpydestructor117519) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI, tprintfunc117521) (tpyobject117591* ob, FILE* f, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tgetattrfunc117523) (tpyobject117591* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, tsetattrfunc117525) (tpyobject117591* ob1, NCSTRING name, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tcmpfunc117527) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, treprfunc117529) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI32, thashfunc117531) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, tternaryfunc117503) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(tpyobject117591*, tgetattrofunc117533) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tsetattrofunc117535) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tvisitproc117551) (tpyobject117591* ob1, void* p);
typedef N_CDECL_PTR(NI, ttraverseproc117553) (tpyobject117591* ob1, tvisitproc117551 prc, void* p);
typedef N_CDECL_PTR(NI, tinquiry117505) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, trichcmpfunc117555) (tpyobject117591* ob1, tpyobject117591* ob2, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tgetiterfunc117557) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, titernextfunc117559) (tpyobject117591* ob1);
typedef N_CDECL_PTR(tpyobject117591*, tdescrgetfunc117561) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tdescrsetfunc117563) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(NI, tinitproc117565) (tpyobject117591* self, tpyobject117591* args, tpyobject117591* kwds);
typedef N_CDECL_PTR(tpyobject117591*, tallocfunc117569) (tpytypeobject117643* self, NI nitems);
typedef N_CDECL_PTR(tpyobject117591*, tnewfunc117567) (tpytypeobject117643* subtype, tpyobject117591* args, tpyobject117591* kwds);
struct  tpytypeobject117643  {
  tpyobject117591 Sup;
NI Obsize;
NCSTRING Tpname;
NI Tpbasicsize;
NI Tpitemsize;
tpydestructor117519 Tpdealloc;
tprintfunc117521 Tpprint;
tgetattrfunc117523 Tpgetattr;
tsetattrfunc117525 Tpsetattr;
tcmpfunc117527 Tpcompare;
treprfunc117529 Tprepr;
tpynumbermethods117573* Tpasnumber;
tpysequencemethods117577* Tpassequence;
tpymappingmethods117581* Tpasmapping;
thashfunc117531 Tphash;
tternaryfunc117503 Tpcall;
treprfunc117529 Tpstr;
tgetattrofunc117533 Tpgetattro;
tsetattrofunc117535 Tpsetattro;
tpybufferprocs117585* Tpasbuffer;
NI32 Tpflags;
NCSTRING Tpdoc;
ttraverseproc117553 Tptraverse;
tinquiry117505 Tpclear;
trichcmpfunc117555 Tprichcompare;
NI32 Tpweaklistoffset;
tgetiterfunc117557 Tpiter;
titernextfunc117559 Tpiternext;
tpymethoddef117603* Tpmethods;
tpymemberdef117607* Tpmembers;
tpygetsetdef117615* Tpgetset;
tpytypeobject117643* Tpbase;
tpyobject117591* Tpdict;
tdescrgetfunc117561 Tpdescrget;
tdescrsetfunc117563 Tpdescrset;
NI32 Tpdictoffset;
tinitproc117565 Tpinit;
tallocfunc117569 Tpalloc;
tnewfunc117567 Tpnew;
tpydestructor117519 Tpfree;
tinquiry117505 Tpisgc;
tpyobject117591* Tpbases;
tpyobject117591* Tpmro;
tpyobject117591* Tpcache;
tpyobject117591* Tpsubclasses;
tpyobject117591* Tpweaklist;
void* Tpxxx7;
void* Tpxxx8;
};
typedef N_CDECL_PTR(tpyobject117591*, TY118920) (NF db);
typedef N_CDECL_PTR(tpyobject117591*, TY119093) (NI32 l);
typedef N_CDECL_PTR(tpyobject117591*, TY118789) (NCSTRING str);
typedef N_CDECL_PTR(NI, TY119052) (tpyobject117591* dp, NI idx, tpyobject117591* item);
typedef N_CDECL_PTR(tpyobject117591*, TY119850) (NI size);
typedef N_CDECL_PTR(NI, TY119856) (tpyobject117591* ob, NI key, tpyobject117591* value);
typedef N_CDECL_PTR(tpyobject117591*, TY118762) (tpyobject117591* v);
typedef N_CDECL_PTR(NCSTRING, TY118783) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI32, TY118998) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY118597) (void);
typedef N_CDECL_PTR(NF, TY118914) (tpyobject117591* ob);
typedef N_CDECL_PTR(NI, TY119439) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY119405) (tpyobject117591* ob, NCSTRING c);
typedef N_CDECL_PTR(NI, TY119465) (tpyobject117591* ob, NCSTRING key, tpyobject117591* value);
typedef pyref127008* TY127587[1];
typedef N_CDECL_PTR(NI, TY119445) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY119384) (tpyobject117591* ob, tpyobject117591* args);
typedef N_CDECL_PTR(tpyobject117591*, TY119412) (tpyobject117591* ob, tpyobject117591* key);
typedef N_CDECL_PTR(NI, TY119473) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
typedef N_CDECL_PTR(tpyobject117591*, TY119312) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, TY119225) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, TY119360) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, TY119267) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, TY119346) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, TY119319) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY119332) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY119219) (tpyobject117591* ob);
typedef N_CDECL_PTR(tpyobject117591*, TY119544) (tpyobject117591* o1, tpyobject117591* o2, NU8 opid);
typedef N_CDECL_PTR(tpyobject117591*, TY118730) (void);
typedef N_CDECL_PTR(tpyobject117591*, TY119040) (NI size);
typedef int TY118011[2];
struct  tpybuffer117665  {
void* Buf;
tpyobject117591* Obj;
int Length;
int Itemsize;
int Readonly;
int Ndim;
NCSTRING Format;
NI32* Shape;
NI32* Strides;
NI32* Suboffsets;
TY118011 Smalltable;
void* Internal;
};
typedef N_CDECL_PTR(void, TY119560) (tpybuffer117665* view);
typedef N_CDECL_PTR(NI, tgetreadbufferproc117537) (tpyobject117591* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, tgetwritebufferproc117539) (tpyobject117591* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, tgetsegcountproc117541) (tpyobject117591* ob1, NI i);
typedef N_CDECL_PTR(NI, tgetcharbufferproc117543) (tpyobject117591* ob1, NI i, NCSTRING pstr);
typedef N_CDECL_PTR(NI, tgetbufferproc117545) (tpyobject117591* a, tpybuffer117665* buf, NI c);
typedef N_CDECL_PTR(void, treleasebufferproc117547) (tpyobject117591* a, tpybuffer117665* buf);
struct  tpybufferprocs117585  {
tgetreadbufferproc117537 Bfgetreadbuffer;
tgetwritebufferproc117539 Bfgetwritebuffer;
tgetsegcountproc117541 Bfgetsegcount;
tgetcharbufferproc117543 Bfgetcharbuffer;
tgetbufferproc117545 Bfgetbuffer;
treleasebufferproc117547 Bfreleasebuffer;
};
typedef N_CDECL_PTR(int, TY119552) (tpyobject117591* obj, tpybuffer117665* view, int flags);
struct  typedpybuffer1d128111  {
tpybuffer117665 Pybuf;
NI Nelements;
};
struct  epynotsupported127014  {
  epython127012 Sup;
};
typedef NimStringDesc* TY128319[2];
struct  epytypeerror127016  {
  epython127012 Sup;
};
typedef N_CDECL_PTR(tpyobject117591*, TY118768) (NCSTRING str, NI start, tpyobject117591* globals, tpyobject117591* locals);
struct  context127018  {
pyref127008* Globals;
pyref127008* Locals;
};
typedef N_CDECL_PTR(tpyobject117591*, TY118657) (void);
typedef N_CDECL_PTR(tpyobject117591*, TY118967) (NCSTRING name);
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
typedef N_CDECL_PTR(tpyobject117591*, tbinaryfunc117501) (tpyobject117591* ob1, tpyobject117591* ob2);
typedef N_CDECL_PTR(tpyobject117591*, tunaryfunc117499) (tpyobject117591* ob1);
typedef N_CDECL_PTR(NI, tcoercion117507) (tpyobject117591** ob1, tpyobject117591** ob2);
struct  tpynumbermethods117573  {
tbinaryfunc117501 Nbadd;
tbinaryfunc117501 Nbsubstract;
tbinaryfunc117501 Nbmultiply;
tbinaryfunc117501 Nbdivide;
tbinaryfunc117501 Nbremainder;
tbinaryfunc117501 Nbdivmod;
tternaryfunc117503 Nbpower;
tunaryfunc117499 Nbnegative;
tunaryfunc117499 Nbpositive;
tunaryfunc117499 Nbabsolute;
tinquiry117505 Nbnonzero;
tunaryfunc117499 Nbinvert;
tbinaryfunc117501 Nblshift;
tbinaryfunc117501 Nbrshift;
tbinaryfunc117501 Nband;
tbinaryfunc117501 Nbxor;
tbinaryfunc117501 Nbor;
tcoercion117507 Nbcoerce;
tunaryfunc117499 Nbint;
tunaryfunc117499 Nblong;
tunaryfunc117499 Nbfloat;
tunaryfunc117499 Nboct;
tunaryfunc117499 Nbhex;
tbinaryfunc117501 Nbinplaceadd;
tbinaryfunc117501 Nbinplacesubtract;
tbinaryfunc117501 Nbinplacemultiply;
tbinaryfunc117501 Nbinplacedivide;
tbinaryfunc117501 Nbinplaceremainder;
tternaryfunc117503 Nbinplacepower;
tbinaryfunc117501 Nbinplacelshift;
tbinaryfunc117501 Nbinplacershift;
tbinaryfunc117501 Nbinplaceand;
tbinaryfunc117501 Nbinplacexor;
tbinaryfunc117501 Nbinplaceor;
tbinaryfunc117501 Nbfloordivide;
tbinaryfunc117501 Nbtruedivide;
tbinaryfunc117501 Nbinplacefloordivide;
tbinaryfunc117501 Nbinplacetruedivide;
};
typedef N_CDECL_PTR(tpyobject117591*, tintargfunc117509) (tpyobject117591* ob1, NI i);
typedef N_CDECL_PTR(tpyobject117591*, tintintargfunc117511) (tpyobject117591* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, tintobjargproc117513) (tpyobject117591* ob1, NI i, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tintintobjargproc117515) (tpyobject117591* ob1, NI i1, NI i2, tpyobject117591* ob2);
typedef N_CDECL_PTR(NI, tobjobjproc117549) (tpyobject117591* ob1, tpyobject117591* ob2);
struct  tpysequencemethods117577  {
tinquiry117505 Sqlength;
tbinaryfunc117501 Sqconcat;
tintargfunc117509 Sqrepeat;
tintargfunc117509 Sqitem;
tintintargfunc117511 Sqslice;
tintobjargproc117513 Sqassitem;
tintintobjargproc117515 Sqassslice;
tobjobjproc117549 Sqcontains;
tbinaryfunc117501 Sqinplaceconcat;
tintargfunc117509 Sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, tobjobjargproc117517) (tpyobject117591* ob1, tpyobject117591* ob2, tpyobject117591* ob3);
struct  tpymappingmethods117581  {
tinquiry117505 Mplength;
tbinaryfunc117501 Mpsubscript;
tobjobjargproc117517 Mpasssubscript;
};
typedef N_CDECL_PTR(tpyobject117591*, tpycfunction117493) (tpyobject117591* self, tpyobject117591* args);
struct  tpymethoddef117603  {
NCSTRING Mlname;
tpycfunction117493 Mlmeth;
NI Mlflags;
NCSTRING Mldoc;
};
struct  tpymemberdef117607  {
NCSTRING Name;
NI Thetype;
NI Offset;
NI Flags;
NCSTRING Doc;
};
typedef N_CDECL_PTR(tpyobject117591*, tgetter117609) (tpyobject117591* obj, void* context);
typedef N_CDECL_PTR(NI, tsetter117611) (tpyobject117591* obj, tpyobject117591* value, void* context);
struct  tpygetsetdef117615  {
NCSTRING Name;
tgetter117609 Get;
tsetter117611 Setter;
NCSTRING Doc;
void* Closure;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
N_NIMCALL(void, handleerror_127095)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP250)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(tpyobject117591*, check_127125)(tpyobject117591* p);
N_NIMCALL(NI, check_127152)(NI x);
N_NIMCALL(NI, refcount_127162)(pyref127008* o);
N_NIMCALL(void, finalizepyref_127172)(pyref127008* o);
static N_INLINE(void, pydecref_120391)(tpyobject117591* op);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(pyref127008*, wrapnew_127198)(tpyobject117591* p);
N_NIMCALL(void, TMP262)(void* p, NI op);
N_NIMCALL(pyref127008*, dup_127238)(pyref127008* src);
static N_INLINE(void, pyincref_120370)(tpyobject117591* op);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(tpyobject117591*, rawpyobject_127278)(pyref127008* x);
N_NIMCALL(pyref127008*, topy_127288)(pyref127008* x);
N_NIMCALL(pyref127008*, topy_127298)(NF f);
N_NIMCALL(pyref127008*, topy_127308)(NI i);
N_NIMCALL(pyref127008*, topy_127319)(NCSTRING s);
N_NIMCALL(pyref127008*, topy_127329)(NimStringDesc* s);
N_NIMCALL(pyref127008*, tolist_127339)(pyref127008** vals, NI valsLen0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(pyref127008*, totuple_127423)(pyref127008** vals, NI valsLen0);
N_NIMCALL(pyref127008*, mktuple_127469)(pyref127008** args, NI argsLen0);
N_NIMCALL(NimStringDesc*, HEX24_127089)(pyref127008* o);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NI, toint_127491)(pyref127008* o);
N_NIMCALL(NF, tofloat_127518)(pyref127008* o);
N_NIMCALL(NIM_BOOL, tobool_127547)(pyref127008* o);
N_NIMCALL(pyref127008*, getattr_127028)(pyref127008* o, NCSTRING field);
N_NIMCALL(void, setattr_127035)(pyref127008* o, NCSTRING field, pyref127008* val);
N_NIMCALL(NimStringDesc*, repr_127579)(pyref127008* o);
N_NIMCALL(NI, len_127595)(pyref127008* o);
static N_INLINE(pyref127008*, HEX2E_127605)(pyref127008* obj, NimStringDesc* field);
N_NIMCALL(pyref127008*, HEX28HEX29_127070)(pyref127008* f, pyref127008** args, NI argsLen0);
N_NIMCALL(pyref127008*, HEX5BHEX5D_127050)(pyref127008* v, pyref127008* key);
N_NIMCALL(void, HEX5BHEX5DHEX3D_127057)(pyref127008* mapping, pyref127008* key, pyref127008* val);
N_NIMCALL(pyref127008*, HEX2A_127728)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, HEX2B_127739)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, HEX2D_127750)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, HEX2F_127761)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, HEX25_127772)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, HEX2D_127783)(pyref127008* a);
N_NIMCALL(pyref127008*, HEX2B_127793)(pyref127008* a);
N_NIMCALL(pyref127008*, abs_127803)(pyref127008* a);
N_NIMCALL(pyref127008*, HEX3DHEX3D_127813)(pyref127008* a, pyref127008* b);
N_NIMCALL(pyref127008*, pydict_127078)(void);
N_NIMCALL(pyref127008*, pylist_127083)(NI size);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(void, finalizerawpybuffer_128022)(tpybuffer117665* b);
static N_INLINE(NIM_BOOL, ispybufferable_128050)(pyref127008* obj);
static N_INLINE(NIM_BOOL, pyobjectcheckbuffer_121432)(tpyobject117591* obj);
N_NIMCALL(NIM_BOOL, pytypehasfeature_120363)(tpytypeobject117643* atype, NI aflag);
N_NIMCALL(tpybuffer117665*, rawpybuffer_128060)(pyref127008* obj, int flags);
N_NIMCALL(void, finalizetypedpybuffer1d_128231)(typedpybuffer1d128111* tb_128239);
N_NIMCALL(typedpybuffer1d128111*, float64buffer_128216)(pyref127008* obj, int flags);
N_NIMCALL(void, TMP273)(void* p, NI op);
N_NIMCALL(void, TMP274)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, TMP295)(void* p, NI op);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, finalizetypedpybuffer1d_128367)(typedpybuffer1d128111* tb_128375);
N_NIMCALL(typedpybuffer1d128111*, float32buffer_128352)(pyref127008* obj, int flags);
N_NIMCALL(void, TMP297)(void* p, NI op);
N_NIMCALL(void, finalizetypedpybuffer1d_128503)(typedpybuffer1d128111* tb_128511);
N_NIMCALL(typedpybuffer1d128111*, uint8buffer_128488)(pyref127008* obj, int flags);
N_NIMCALL(void, TMP300)(void* p, NI op);
N_NIMCALL(pyref127008*, eval_127043)(context127018* c, NCSTRING src);
N_NIMCALL(pyref127008*, builtins_127065)(void);
N_NIMCALL(pyref127008*, pyimport_128640)(NCSTRING name);
N_NIMCALL(context127018*, initcontext_128650)(void);
N_NIMCALL(void, TMP304)(void* p, NI op);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51025)(tcell44933* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c);
static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c);
N_NOINLINE(void, incl_45671)(tcellset44945* s, tcell44933* cell);
static N_INLINE(void, decref_50604)(tcell44933* c);
N_NIMCALL(void, initpython_121604)(void);
STRING_LITERAL(TMP251, "check(nil)", 10);
STRING_LITERAL(TMP252, "check(-1)", 9);
STRING_LITERAL(TMP265, "failed conversion to int", 24);
STRING_LITERAL(TMP266, "failed conversion to float", 26);
STRING_LITERAL(TMP267, "repr", 4);
STRING_LITERAL(TMP269, "err == 0 ", 9);
STRING_LITERAL(TMP275, "buffer interface not supported with flags ", 42);
STRING_LITERAL(TMP276, "d", 1);
STRING_LITERAL(TMP294, "expected buffer format $1 but got $2", 36);
STRING_LITERAL(TMP298, "f", 1);
STRING_LITERAL(TMP301, "B", 1);
STRING_LITERAL(TMP305, "__builtins__", 12);
extern TY118602 Dl_118601;
extern TNimType NTI3227; /* Exception */
TNimType NTI127012; /* EPython */
TNimType NTI127101; /* ref EPython */
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;
TNimType NTI127008; /* PyRef */
extern TNimType NTI117481; /* PPyObject */
TNimType NTI127010; /* PPyRef */
extern TY118920 Dl_118919;
extern TY119093 Dl_119092;
extern TY118789 Dl_118788;
extern TY119052 Dl_119051;
extern TY119850 Dl_119849;
extern TY119856 Dl_119855;
extern TY118762 Dl_118761;
extern TY118783 Dl_118782;
extern TY118998 Dl_118997;
extern TY118597 Dl_118596;
extern TY118914 Dl_118913;
extern TY119439 Dl_119438;
extern TY119405 Dl_119404;
extern TY119465 Dl_119464;
extern TY119445 Dl_119444;
extern TY119384 Dl_119383;
extern TY119412 Dl_119411;
extern TY119473 Dl_119472;
extern TY119312 Dl_119311;
extern TY119225 Dl_119224;
extern TY119360 Dl_119359;
extern TY119267 Dl_119266;
extern TY119346 Dl_119345;
extern TY119319 Dl_119318;
extern TY119332 Dl_119331;
extern TY119219 Dl_119218;
extern TY119544 Dl_119543;
extern TY118730 Dl_118729;
extern TY119040 Dl_119039;
extern tpyobject117591* pynone_118289;
extern TY119560 Dl_119559;
extern TNimType NTI128024; /* ref TPy_buffer */
extern TY119552 Dl_119551;
int defaultbufferflags_128180;
TNimType NTI128111; /* TypedPyBuffer1D */
extern TNimType NTI117665; /* TPy_buffer */
extern TNimType NTI108; /* int */
TNimType NTI128240; /* ref TypedPyBuffer1D[float64] */
TNimType NTI127014; /* EPyNotSupported */
TNimType NTI128300; /* ref EPyNotSupported */
TNimType NTI127016; /* EPyTypeError */
TNimType NTI128323; /* ref EPyTypeError */
TNimType NTI128376; /* ref TypedPyBuffer1D[float32] */
TNimType NTI128512; /* ref TypedPyBuffer1D[uint8] */
extern TY118768 Dl_118767;
extern TY118657 Dl_118656;
extern TY118967 Dl_118966;
TNimType NTI127018; /* Context */
TNimType NTI127020; /* PContext */
N_NIMCALL(void, TMP250)(void* p, NI op) {
	epython127012* a;
	a = (epython127012*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, handleerror_127095)(NimStringDesc* s) {
	epython127012* e_127100;
	NimStringDesc* LOC1;
	nimfr("handleError", "high_level.nim")
	nimln(52, "high_level.nim");
	Dl_118601();
	e_127100 = 0;
	nimln(2149, "system.nim");
	e_127100 = (epython127012*) newObj((&NTI127101), sizeof(epython127012));
	(*e_127100).Sup.Sup.m_type = (&NTI127012);
	nimln(2150, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_127100).Sup.message; (*e_127100).Sup.message = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(53, "high_level.nim");
	raiseException((Exception*)e_127100, "EPython");
	popFrame();
}

N_NIMCALL(tpyobject117591*, check_127125)(tpyobject117591* p) {
	tpyobject117591* result;
	nimfr("check", "high_level.nim")
	result = 0;
	nimln(56, "high_level.nim");
	{
		nimln(56, "high_level.nim");
		if (!(p == NIM_NIL)) goto LA3;
		nimln(56, "high_level.nim");
		handleerror_127095(((NimStringDesc*) &TMP251));
	}
	LA3: ;
	nimln(57, "high_level.nim");
	result = p;
	popFrame();
	return result;
}

N_NIMCALL(NI, check_127152)(NI x) {
	NI result;
	nimfr("check", "high_level.nim")
	result = 0;
	nimln(60, "high_level.nim");
	{
		nimln(60, "high_level.nim");
		if (!(x == -1)) goto LA3;
		nimln(60, "high_level.nim");
		handleerror_127095(((NimStringDesc*) &TMP252));
	}
	LA3: ;
	nimln(61, "high_level.nim");
	result = x;
	popFrame();
	return result;
}

N_NIMCALL(NI, refcount_127162)(pyref127008* o) {
	NI result;
	nimfr("refCount", "high_level.nim")
	result = 0;
	nimln(66, "high_level.nim");
	result = (*(*o).P).Obrefcnt;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, pydecref_120391)(tpyobject117591* op) {
	nimfr("Py_DECREF", "low_level.nim")
	nimln(1377, "low_level.nim");
	(*op).Obrefcnt = subInt((*op).Obrefcnt, 1);
	nimln(1378, "low_level.nim");
	{
		nimln(1378, "low_level.nim");
		if (!((*op).Obrefcnt == 0)) goto LA3;
		nimln(1379, "low_level.nim");
		(*(*op).Obtype).Tpdealloc(op);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, finalizepyref_127172)(pyref127008* o) {
	nimfr("finalizePyRef", "high_level.nim")
	nimln(69, "high_level.nim");
	{
		nimln(69, "high_level.nim");
		nimln(69, "high_level.nim");
		if (!!(((*o).P == NIM_NIL))) goto LA3;
		nimln(70, "high_level.nim");
		pydecref_120391((*o).P);
		nimln(71, "high_level.nim");
		(*o).P = NIM_NIL;
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP262)(void* p, NI op) {
	pyref127008* a;
	a = (pyref127008*)p;
}

N_NIMCALL(pyref127008*, wrapnew_127198)(tpyobject117591* p) {
	pyref127008* result;
	nimfr("wrapNew", "high_level.nim")
	result = 0;
	nimln(74, "high_level.nim");
	result = (pyref127008*) newObj((&NTI127010), sizeof(pyref127008));
	(*result).m_type = (&NTI127008);
	nimln(75, "high_level.nim");
	(*result).P = check_127125(p);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, pyincref_120370)(tpyobject117591* op) {
	nimfr("Py_INCREF", "low_level.nim")
	nimln(1374, "low_level.nim");
	(*op).Obrefcnt = addInt((*op).Obrefcnt, 1);
	popFrame();
}

N_NIMCALL(pyref127008*, dup_127238)(pyref127008* src) {
	pyref127008* result;
	nimfr("dup", "high_level.nim")
	result = 0;
	nimln(78, "high_level.nim");
	result = (pyref127008*) newObj((&NTI127010), sizeof(pyref127008));
	(*result).m_type = (&NTI127008);
	nimln(79, "high_level.nim");
	(*result).P = (*src).P;
	nimln(80, "high_level.nim");
	pyincref_120370((*result).P);
	popFrame();
	return result;
}

N_NIMCALL(tpyobject117591*, rawpyobject_127278)(pyref127008* x) {
	tpyobject117591* result;
	nimfr("rawPyObject", "high_level.nim")
	result = 0;
	nimln(85, "high_level.nim");
	result = (*x).P;
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, topy_127288)(pyref127008* x) {
	pyref127008* result;
	nimfr("toPy", "high_level.nim")
	result = 0;
	nimln(87, "high_level.nim");
	result = x;
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, topy_127298)(NF f) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("toPy", "high_level.nim")
	result = 0;
	nimln(88, "high_level.nim");
	nimln(88, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118919(f);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, topy_127308)(NI i) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("toPy", "high_level.nim")
	result = 0;
	nimln(89, "high_level.nim");
	nimln(89, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119092(((NI32) (i)));
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, topy_127319)(NCSTRING s) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("toPy", "high_level.nim")
	result = 0;
	nimln(90, "high_level.nim");
	nimln(90, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118788(s);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, topy_127329)(NimStringDesc* s) {
	pyref127008* result;
	nimfr("toPy", "high_level.nim")
	result = 0;
	nimln(91, "high_level.nim");
	result = topy_127319(s->data);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, tolist_127339)(pyref127008** vals, NI valsLen0) {
	pyref127008* result;
	nimfr("toList", "high_level.nim")
	result = 0;
	nimln(94, "high_level.nim");
	nimln(94, "high_level.nim");
	result = pylist_127083(valsLen0);
	{
		NI i_127368;
		NI HEX3Atmp_127371;
		NI TMP263;
		NI res_127374;
		i_127368 = 0;
		HEX3Atmp_127371 = 0;
		nimln(95, "high_level.nim");
		nimln(95, "high_level.nim");
		nimln(95, "high_level.nim");
		TMP263 = subInt(valsLen0, 1);
		HEX3Atmp_127371 = (NI32)(TMP263);
		nimln(1576, "system.nim");
		res_127374 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				tpyobject117591* p;
				NI LOC4;
				NI LOC5;
				nimln(1577, "system.nim");
				if (!(res_127374 <= HEX3Atmp_127371)) goto LA3;
				nimln(1576, "system.nim");
				i_127368 = res_127374;
				nimln(96, "high_level.nim");
				if ((NU)(i_127368) >= (NU)(valsLen0)) raiseIndexError();
				p = (*vals[i_127368]).P;
				nimln(97, "high_level.nim");
				pyincref_120370(p);
				nimln(98, "high_level.nim");
				nimln(98, "high_level.nim");
				nimln(98, "high_level.nim");
				LOC4 = 0;
				LOC4 = Dl_119051((*result).P, i_127368, p);
				LOC5 = 0;
				LOC5 = check_127152(LOC4);
				nimln(1579, "system.nim");
				res_127374 = addInt(res_127374, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, totuple_127423)(pyref127008** vals, NI valsLen0) {
	pyref127008* result;
	NI size;
	tpyobject117591* LOC1;
	nimfr("toTuple", "high_level.nim")
	result = 0;
	nimln(108, "high_level.nim");
	nimln(108, "high_level.nim");
	size = valsLen0;
	nimln(109, "high_level.nim");
	nimln(109, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119849(size);
	result = wrapnew_127198(LOC1);
	{
		NI i_127446;
		NI HEX3Atmp_127449;
		NI TMP264;
		NI res_127452;
		i_127446 = 0;
		HEX3Atmp_127449 = 0;
		nimln(110, "high_level.nim");
		nimln(110, "high_level.nim");
		TMP264 = subInt(size, 1);
		HEX3Atmp_127449 = (NI32)(TMP264);
		nimln(1576, "system.nim");
		res_127452 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				tpyobject117591* p;
				NI LOC5;
				NI LOC6;
				nimln(1577, "system.nim");
				if (!(res_127452 <= HEX3Atmp_127449)) goto LA4;
				nimln(1576, "system.nim");
				i_127446 = res_127452;
				nimln(111, "high_level.nim");
				if ((NU)(i_127446) >= (NU)(valsLen0)) raiseIndexError();
				p = (*vals[i_127446]).P;
				nimln(112, "high_level.nim");
				pyincref_120370(p);
				nimln(113, "high_level.nim");
				nimln(113, "high_level.nim");
				nimln(113, "high_level.nim");
				LOC5 = 0;
				LOC5 = Dl_119855((*result).P, i_127446, p);
				LOC6 = 0;
				LOC6 = check_127152(LOC5);
				nimln(1579, "system.nim");
				res_127452 = addInt(res_127452, 1);
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, mktuple_127469)(pyref127008** args, NI argsLen0) {
	pyref127008* result;
	nimfr("mkTuple", "high_level.nim")
	result = 0;
	nimln(115, "high_level.nim");
	result = totuple_127423(args, argsLen0);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_127089)(pyref127008* o) {
	NimStringDesc* result;
	pyref127008* s;
	tpyobject117591* LOC1;
	NCSTRING LOC2;
	nimfr("$", "high_level.nim")
	result = 0;
	nimln(118, "high_level.nim");
	nimln(118, "high_level.nim");
	nimln(118, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118761((*o).P);
	s = wrapnew_127198(LOC1);
	nimln(119, "high_level.nim");
	nimln(119, "high_level.nim");
	LOC2 = 0;
	LOC2 = Dl_118782((*s).P);
	result = cstrToNimstr(LOC2);
	popFrame();
	return result;
}

N_NIMCALL(NI, toint_127491)(pyref127008* o) {
	NI result;
	NI32 LOC1;
	nimfr("toInt", "high_level.nim")
	result = 0;
	nimln(122, "high_level.nim");
	nimln(122, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118997((*o).P);
	result = ((NI) (LOC1));
	nimln(123, "high_level.nim");
	{
		nimln(123, "high_level.nim");
		if (!(result == -1)) goto LA4;
		nimln(124, "high_level.nim");
		{
			tpyobject117591* LOC8;
			nimln(124, "high_level.nim");
			nimln(124, "high_level.nim");
			nimln(124, "high_level.nim");
			LOC8 = 0;
			LOC8 = Dl_118596();
			if (!!((LOC8 == NIM_NIL))) goto LA9;
			nimln(125, "high_level.nim");
			handleerror_127095(((NimStringDesc*) &TMP265));
		}
		LA9: ;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, tofloat_127518)(pyref127008* o) {
	NF result;
	nimfr("toFloat", "high_level.nim")
	result = 0;
	nimln(128, "high_level.nim");
	result = Dl_118913((*o).P);
	nimln(129, "high_level.nim");
	{
		nimln(129, "high_level.nim");
		if (!(result == -1.0000000000000000e+000)) goto LA3;
		nimln(130, "high_level.nim");
		{
			tpyobject117591* LOC7;
			nimln(130, "high_level.nim");
			nimln(130, "high_level.nim");
			nimln(130, "high_level.nim");
			LOC7 = 0;
			LOC7 = Dl_118596();
			if (!!((LOC7 == NIM_NIL))) goto LA8;
			nimln(131, "high_level.nim");
			handleerror_127095(((NimStringDesc*) &TMP266));
		}
		LA8: ;
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, tobool_127547)(pyref127008* o) {
	NIM_BOOL result;
	tpyobject117591* LOC1;
	NI LOC2;
	nimfr("toBool", "high_level.nim")
	result = 0;
	nimln(133, "high_level.nim");
	nimln(133, "high_level.nim");
	nimln(133, "high_level.nim");
	nimln(133, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(o);
	LOC2 = 0;
	LOC2 = Dl_119438(LOC1);
	result = (LOC2 == 1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, getattr_127028)(pyref127008* o, NCSTRING field) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("getattr", "high_level.nim")
	result = 0;
	nimln(139, "high_level.nim");
	nimln(139, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119404((*o).P, field);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, setattr_127035)(pyref127008* o, NCSTRING field, pyref127008* val) {
	NI LOC1;
	NI LOC2;
	nimfr("setattr", "high_level.nim")
	nimln(142, "high_level.nim");
	nimln(142, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119464((*o).P, field, (*val).P);
	LOC2 = 0;
	LOC2 = check_127152(LOC1);
	popFrame();
}

N_NIMCALL(NimStringDesc*, repr_127579)(pyref127008* o) {
	NimStringDesc* result;
	pyref127008* LOC1;
	pyref127008* LOC2;
	pyref127008* LOC3;
	TY127587 LOC4;
	pyref127008* LOC5;
	nimfr("repr", "high_level.nim")
	result = 0;
	nimln(144, "high_level.nim");
	nimln(144, "high_level.nim");
	nimln(144, "high_level.nim");
	nimln(144, "high_level.nim");
	LOC1 = 0;
	LOC1 = builtins_127065();
	nimln(144, "high_level.nim");
	LOC2 = 0;
	LOC2 = topy_127329(((NimStringDesc*) &TMP267));
	LOC3 = 0;
	LOC3 = HEX5BHEX5D_127050(LOC1, LOC2);
	memset((void*)LOC4, 0, sizeof(LOC4));
	nimln(144, "high_level.nim");
	LOC4[0] = topy_127288(o);
	LOC5 = 0;
	LOC5 = HEX28HEX29_127070(LOC3, LOC4, 1);
	result = HEX24_127089(LOC5);
	popFrame();
	return result;
}

N_NIMCALL(NI, len_127595)(pyref127008* o) {
	NI result;
	NI LOC1;
	nimfr("len", "high_level.nim")
	result = 0;
	nimln(146, "high_level.nim");
	nimln(146, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119444((*o).P);
	result = check_127152(LOC1);
	popFrame();
	return result;
}

static N_INLINE(pyref127008*, HEX2E_127605)(pyref127008* obj, NimStringDesc* field) {
	pyref127008* result;
	nimfr(".", "high_level.nim")
	result = 0;
	nimln(152, "high_level.nim");
	result = getattr_127028(obj, field->data);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX28HEX29_127070)(pyref127008* f, pyref127008** args, NI argsLen0) {
	pyref127008* result;
	pyref127008* argstup;
	tpyobject117591* LOC1;
	nimfr("()", "high_level.nim")
	result = 0;
	nimln(166, "high_level.nim");
	nimln(166, "high_level.nim");
	argstup = totuple_127423(args, argsLen0);
	nimln(167, "high_level.nim");
	nimln(167, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119383((*f).P, (*argstup).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX5BHEX5D_127050)(pyref127008* v, pyref127008* key) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("[]", "high_level.nim")
	result = 0;
	nimln(170, "high_level.nim");
	nimln(170, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119411((*v).P, (*key).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_127057)(pyref127008* mapping, pyref127008* key, pyref127008* val) {
	NI LOC1;
	NI LOC2;
	nimfr("[]=", "high_level.nim")
	nimln(173, "high_level.nim");
	nimln(173, "high_level.nim");
	nimln(173, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119472((*mapping).P, (*key).P, (*val).P);
	LOC2 = 0;
	LOC2 = check_127152(LOC1);
	popFrame();
}

N_NIMCALL(pyref127008*, HEX2A_127728)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("*", "high_level.nim")
	result = 0;
	nimln(175, "high_level.nim");
	nimln(175, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119311((*a).P, (*b).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX2B_127739)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("+", "high_level.nim")
	result = 0;
	nimln(176, "high_level.nim");
	nimln(176, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119224((*a).P, (*b).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX2D_127750)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("-", "high_level.nim")
	result = 0;
	nimln(177, "high_level.nim");
	nimln(177, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119359((*a).P, (*b).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX2F_127761)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("/", "high_level.nim")
	result = 0;
	nimln(178, "high_level.nim");
	nimln(178, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119266((*a).P, (*b).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX25_127772)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("%", "high_level.nim")
	result = 0;
	nimln(179, "high_level.nim");
	nimln(179, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119345((*a).P, (*b).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX2D_127783)(pyref127008* a) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("-", "high_level.nim")
	result = 0;
	nimln(180, "high_level.nim");
	nimln(180, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119318((*a).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX2B_127793)(pyref127008* a) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("+", "high_level.nim")
	result = 0;
	nimln(181, "high_level.nim");
	nimln(181, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119331((*a).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, abs_127803)(pyref127008* a) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("abs", "high_level.nim")
	result = 0;
	nimln(182, "high_level.nim");
	nimln(182, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119218((*a).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, HEX3DHEX3D_127813)(pyref127008* a, pyref127008* b) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("==", "high_level.nim")
	result = 0;
	nimln(183, "high_level.nim");
	nimln(183, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119543((*a).P, (*b).P, ((NU8) 2));
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, pydict_127078)(void) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("pyDict", "high_level.nim")
	result = 0;
	nimln(188, "high_level.nim");
	nimln(188, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118729();
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, pylist_127083)(NI size) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("pyList", "high_level.nim")
	result = 0;
	nimln(191, "high_level.nim");
	nimln(191, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_119039(size);
	result = wrapnew_127198(LOC1);
	{
		NI i_127847;
		NI HEX3Atmp_128002;
		NI TMP268;
		NI res_128005;
		i_127847 = 0;
		HEX3Atmp_128002 = 0;
		nimln(192, "high_level.nim");
		nimln(192, "high_level.nim");
		TMP268 = subInt(size, 1);
		HEX3Atmp_128002 = (NI32)(TMP268);
		nimln(1576, "system.nim");
		res_128005 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				NI err;
				nimln(1577, "system.nim");
				if (!(res_128005 <= HEX3Atmp_128002)) goto LA4;
				nimln(1576, "system.nim");
				i_127847 = res_128005;
				nimln(193, "high_level.nim");
				pyincref_120370(pynone_118289);
				nimln(194, "high_level.nim");
				err = Dl_119051((*result).P, i_127847, pynone_118289);
				nimln(195, "high_level.nim");
				{
					nimln(195, "high_level.nim");
					nimln(195, "high_level.nim");
					if (!!((err == 0))) goto LA7;
					nimln(195, "high_level.nim");
					failedassertimpl_86825(((NimStringDesc*) &TMP269));
				}
				LA7: ;
				nimln(1579, "system.nim");
				res_128005 = addInt(res_128005, 1);
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(void, finalizerawpybuffer_128022)(tpybuffer117665* b) {
	nimfr("finalizeRawPyBuffer", "high_level.nim")
	nimln(198, "high_level.nim");
	{
		nimln(198, "high_level.nim");
		nimln(198, "high_level.nim");
		if (!!(((*b).Obj == NIM_NIL))) goto LA3;
		nimln(198, "high_level.nim");
		Dl_119559(b);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, pyobjectcheckbuffer_121432)(tpyobject117591* obj) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	nimfr("PyObject_CheckBuffer", "low_level.nim")
	result = 0;
	nimln(1505, "low_level.nim");
	nimln(1506, "low_level.nim");
	LOC1 = 0;
	nimln(1505, "low_level.nim");
	LOC2 = 0;
	nimln(1505, "low_level.nim");
	nimln(1505, "low_level.nim");
	LOC2 = !(((*(*obj).Obtype).Tpasbuffer == NIM_NIL));
	if (!(LOC2)) goto LA3;
	nimln(1506, "low_level.nim");
	LOC2 = pytypehasfeature_120363((*obj).Obtype, 2097152);
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	nimln(1507, "low_level.nim");
	nimln(1507, "low_level.nim");
	LOC1 = !(((*(*(*obj).Obtype).Tpasbuffer).Bfgetbuffer == NIM_NIL));
	LA4: ;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, ispybufferable_128050)(pyref127008* obj) {
	NIM_BOOL result;
	tpyobject117591* LOC1;
	nimfr("isPyBufferable", "high_level.nim")
	result = 0;
	nimln(201, "high_level.nim");
	nimln(201, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(obj);
	result = pyobjectcheckbuffer_121432(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(tpybuffer117665*, rawpybuffer_128060)(pyref127008* obj, int flags) {
	tpybuffer117665* result;
	int err;
	tpyobject117591* LOC1;
	nimfr("rawPyBuffer", "high_level.nim")
	result = 0;
	nimln(206, "high_level.nim");
	result = (tpybuffer117665*) newObj((&NTI128024), sizeof(tpybuffer117665));
	nimln(207, "high_level.nim");
	nimln(207, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(obj);
	err = Dl_119551(LOC1, result, flags);
	nimln(208, "high_level.nim");
	{
		nimln(208, "high_level.nim");
		if (!(err == ((NI32) -1))) goto LA4;
		nimln(209, "high_level.nim");
		(*result).Obj = NIM_NIL;
		nimln(210, "high_level.nim");
		result = NIM_NIL;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, finalizetypedpybuffer1d_128231)(typedpybuffer1d128111* tb_128239) {
	nimfr("finalizeTypedPyBuffer1D", "high_level.nim")
	nimln(235, "high_level.nim");
	{
		nimln(235, "high_level.nim");
		nimln(235, "high_level.nim");
		if (!!(((*tb_128239).Pybuf.Obj == NIM_NIL))) goto LA3;
		nimln(235, "high_level.nim");
		Dl_119559((&(*tb_128239).Pybuf));
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP273)(void* p, NI op) {
	typedpybuffer1d128111* a;
	NI LOC1;
	a = (typedpybuffer1d128111*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 2; LOC1++) {
	}
}
N_NIMCALL(void, TMP274)(void* p, NI op) {
	epynotsupported127014* a;
	a = (epynotsupported127014*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP295)(void* p, NI op) {
	epytypeerror127016* a;
	a = (epytypeerror127016*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (-2147483647 -1));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI32)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(typedpybuffer1d128111*, float64buffer_128216)(pyref127008* obj, int flags) {
	typedpybuffer1d128111* result;
	int err_128213;
	tpyobject117591* LOC1;
	NI32 TMP296;
	nimfr("float64Buffer", "high_level.nim")
	result = 0;
	nimln(241, "high_level.nim");
	result = (typedpybuffer1d128111*) newObj((&NTI128240), sizeof(typedpybuffer1d128111));
	nimln(242, "high_level.nim");
	(*result).Pybuf.Obj = NIM_NIL;
	nimln(243, "high_level.nim");
	nimln(243, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(obj);
	err_128213 = Dl_119551(LOC1, (&(*result).Pybuf), flags);
	nimln(244, "high_level.nim");
	{
		epynotsupported127014* e_128299;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(244, "high_level.nim");
		if (!(err_128213 == ((NI32) -1))) goto LA4;
		e_128299 = 0;
		nimln(2149, "system.nim");
		e_128299 = (epynotsupported127014*) newObj((&NTI128300), sizeof(epynotsupported127014));
		(*e_128299).Sup.Sup.Sup.m_type = (&NTI127014);
		nimln(2150, "system.nim");
		nimln(246, "high_level.nim");
		LOC6 = 0;
		nimln(246, "high_level.nim");
		LOC7 = 0;
		LOC7 = nimIntToStr(((NI) (flags)));
		LOC6 = rawNewString(LOC7->Sup.len + 42);
appendString(LOC6, ((NimStringDesc*) &TMP275));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_128299).Sup.Sup.message), LOC6);
		nimln(245, "high_level.nim");
		raiseException((Exception*)e_128299, "EPyNotSupported");
	}
	LA4: ;
	nimln(247, "high_level.nim");
	{
		NIM_BOOL LOC10;
		NimStringDesc* LOC12;
		NimStringDesc* msg_128215;
		TY128319 LOC15;
		epytypeerror127016* e_128322;
		NimStringDesc* LOC16;
		nimln(247, "high_level.nim");
		LOC10 = 0;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC10 = !(((NI32)(flags & ((NI32) 4)) == ((NI32) 0)));
		if (!(LOC10)) goto LA11;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC12 = 0;
		LOC12 = cstrToNimstr((*result).Pybuf.Format);
		LOC10 = !(eqStrings(((NimStringDesc*) &TMP276), LOC12));
		LA11: ;
		if (!LOC10) goto LA13;
		nimln(248, "high_level.nim");
		memset((void*)LOC15, 0, sizeof(LOC15));
		LOC15[0] = copyString(((NimStringDesc*) &TMP276));
		nimln(248, "high_level.nim");
		LOC15[1] = cstrToNimstr((*result).Pybuf.Format);
		msg_128215 = nsuFormatOpenArray(((NimStringDesc*) &TMP294), LOC15, 2);
		e_128322 = 0;
		nimln(2149, "system.nim");
		e_128322 = (epytypeerror127016*) newObj((&NTI128323), sizeof(epytypeerror127016));
		(*e_128322).Sup.Sup.Sup.m_type = (&NTI127016);
		nimln(2150, "system.nim");
		LOC16 = 0;
		LOC16 = (*e_128322).Sup.Sup.message; (*e_128322).Sup.Sup.message = copyStringRC1(msg_128215);
		if (LOC16) nimGCunrefNoCycle(LOC16);
		nimln(249, "high_level.nim");
		raiseException((Exception*)e_128322, "EPyTypeError");
	}
	LA13: ;
	nimln(250, "high_level.nim");
	nimln(250, "high_level.nim");
	TMP296 = divInt((*result).Pybuf.Length, (*result).Pybuf.Itemsize);
	(*result).Nelements = ((NI) ((NI32)(TMP296)));
	popFrame();
	return result;
}

N_NIMCALL(void, finalizetypedpybuffer1d_128367)(typedpybuffer1d128111* tb_128375) {
	nimfr("finalizeTypedPyBuffer1D", "high_level.nim")
	nimln(235, "high_level.nim");
	{
		nimln(235, "high_level.nim");
		nimln(235, "high_level.nim");
		if (!!(((*tb_128375).Pybuf.Obj == NIM_NIL))) goto LA3;
		nimln(235, "high_level.nim");
		Dl_119559((&(*tb_128375).Pybuf));
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP297)(void* p, NI op) {
	typedpybuffer1d128111* a;
	NI LOC1;
	a = (typedpybuffer1d128111*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 2; LOC1++) {
	}
}

N_NIMCALL(typedpybuffer1d128111*, float32buffer_128352)(pyref127008* obj, int flags) {
	typedpybuffer1d128111* result;
	int err_128349;
	tpyobject117591* LOC1;
	NI32 TMP299;
	nimfr("float32Buffer", "high_level.nim")
	result = 0;
	nimln(241, "high_level.nim");
	result = (typedpybuffer1d128111*) newObj((&NTI128376), sizeof(typedpybuffer1d128111));
	nimln(242, "high_level.nim");
	(*result).Pybuf.Obj = NIM_NIL;
	nimln(243, "high_level.nim");
	nimln(243, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(obj);
	err_128349 = Dl_119551(LOC1, (&(*result).Pybuf), flags);
	nimln(244, "high_level.nim");
	{
		epynotsupported127014* e_128435;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(244, "high_level.nim");
		if (!(err_128349 == ((NI32) -1))) goto LA4;
		e_128435 = 0;
		nimln(2149, "system.nim");
		e_128435 = (epynotsupported127014*) newObj((&NTI128300), sizeof(epynotsupported127014));
		(*e_128435).Sup.Sup.Sup.m_type = (&NTI127014);
		nimln(2150, "system.nim");
		nimln(246, "high_level.nim");
		LOC6 = 0;
		nimln(246, "high_level.nim");
		LOC7 = 0;
		LOC7 = nimIntToStr(((NI) (flags)));
		LOC6 = rawNewString(LOC7->Sup.len + 42);
appendString(LOC6, ((NimStringDesc*) &TMP275));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_128435).Sup.Sup.message), LOC6);
		nimln(245, "high_level.nim");
		raiseException((Exception*)e_128435, "EPyNotSupported");
	}
	LA4: ;
	nimln(247, "high_level.nim");
	{
		NIM_BOOL LOC10;
		NimStringDesc* LOC12;
		NimStringDesc* msg_128351;
		TY128319 LOC15;
		epytypeerror127016* e_128458;
		NimStringDesc* LOC16;
		nimln(247, "high_level.nim");
		LOC10 = 0;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC10 = !(((NI32)(flags & ((NI32) 4)) == ((NI32) 0)));
		if (!(LOC10)) goto LA11;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC12 = 0;
		LOC12 = cstrToNimstr((*result).Pybuf.Format);
		LOC10 = !(eqStrings(((NimStringDesc*) &TMP298), LOC12));
		LA11: ;
		if (!LOC10) goto LA13;
		nimln(248, "high_level.nim");
		memset((void*)LOC15, 0, sizeof(LOC15));
		LOC15[0] = copyString(((NimStringDesc*) &TMP298));
		nimln(248, "high_level.nim");
		LOC15[1] = cstrToNimstr((*result).Pybuf.Format);
		msg_128351 = nsuFormatOpenArray(((NimStringDesc*) &TMP294), LOC15, 2);
		e_128458 = 0;
		nimln(2149, "system.nim");
		e_128458 = (epytypeerror127016*) newObj((&NTI128323), sizeof(epytypeerror127016));
		(*e_128458).Sup.Sup.Sup.m_type = (&NTI127016);
		nimln(2150, "system.nim");
		LOC16 = 0;
		LOC16 = (*e_128458).Sup.Sup.message; (*e_128458).Sup.Sup.message = copyStringRC1(msg_128351);
		if (LOC16) nimGCunrefNoCycle(LOC16);
		nimln(249, "high_level.nim");
		raiseException((Exception*)e_128458, "EPyTypeError");
	}
	LA13: ;
	nimln(250, "high_level.nim");
	nimln(250, "high_level.nim");
	TMP299 = divInt((*result).Pybuf.Length, (*result).Pybuf.Itemsize);
	(*result).Nelements = ((NI) ((NI32)(TMP299)));
	popFrame();
	return result;
}

N_NIMCALL(void, finalizetypedpybuffer1d_128503)(typedpybuffer1d128111* tb_128511) {
	nimfr("finalizeTypedPyBuffer1D", "high_level.nim")
	nimln(235, "high_level.nim");
	{
		nimln(235, "high_level.nim");
		nimln(235, "high_level.nim");
		if (!!(((*tb_128511).Pybuf.Obj == NIM_NIL))) goto LA3;
		nimln(235, "high_level.nim");
		Dl_119559((&(*tb_128511).Pybuf));
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP300)(void* p, NI op) {
	typedpybuffer1d128111* a;
	NI LOC1;
	a = (typedpybuffer1d128111*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 2; LOC1++) {
	}
}

N_NIMCALL(typedpybuffer1d128111*, uint8buffer_128488)(pyref127008* obj, int flags) {
	typedpybuffer1d128111* result;
	int err_128485;
	tpyobject117591* LOC1;
	NI32 TMP302;
	nimfr("uint8Buffer", "high_level.nim")
	result = 0;
	nimln(241, "high_level.nim");
	result = (typedpybuffer1d128111*) newObj((&NTI128512), sizeof(typedpybuffer1d128111));
	nimln(242, "high_level.nim");
	(*result).Pybuf.Obj = NIM_NIL;
	nimln(243, "high_level.nim");
	nimln(243, "high_level.nim");
	LOC1 = 0;
	LOC1 = rawpyobject_127278(obj);
	err_128485 = Dl_119551(LOC1, (&(*result).Pybuf), flags);
	nimln(244, "high_level.nim");
	{
		epynotsupported127014* e_128571;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(244, "high_level.nim");
		if (!(err_128485 == ((NI32) -1))) goto LA4;
		e_128571 = 0;
		nimln(2149, "system.nim");
		e_128571 = (epynotsupported127014*) newObj((&NTI128300), sizeof(epynotsupported127014));
		(*e_128571).Sup.Sup.Sup.m_type = (&NTI127014);
		nimln(2150, "system.nim");
		nimln(246, "high_level.nim");
		LOC6 = 0;
		nimln(246, "high_level.nim");
		LOC7 = 0;
		LOC7 = nimIntToStr(((NI) (flags)));
		LOC6 = rawNewString(LOC7->Sup.len + 42);
appendString(LOC6, ((NimStringDesc*) &TMP275));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_128571).Sup.Sup.message), LOC6);
		nimln(245, "high_level.nim");
		raiseException((Exception*)e_128571, "EPyNotSupported");
	}
	LA4: ;
	nimln(247, "high_level.nim");
	{
		NIM_BOOL LOC10;
		NimStringDesc* LOC12;
		NimStringDesc* msg_128487;
		TY128319 LOC15;
		epytypeerror127016* e_128594;
		NimStringDesc* LOC16;
		nimln(247, "high_level.nim");
		LOC10 = 0;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC10 = !(((NI32)(flags & ((NI32) 4)) == ((NI32) 0)));
		if (!(LOC10)) goto LA11;
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		nimln(247, "high_level.nim");
		LOC12 = 0;
		LOC12 = cstrToNimstr((*result).Pybuf.Format);
		LOC10 = !(eqStrings(((NimStringDesc*) &TMP301), LOC12));
		LA11: ;
		if (!LOC10) goto LA13;
		nimln(248, "high_level.nim");
		memset((void*)LOC15, 0, sizeof(LOC15));
		LOC15[0] = copyString(((NimStringDesc*) &TMP301));
		nimln(248, "high_level.nim");
		LOC15[1] = cstrToNimstr((*result).Pybuf.Format);
		msg_128487 = nsuFormatOpenArray(((NimStringDesc*) &TMP294), LOC15, 2);
		e_128594 = 0;
		nimln(2149, "system.nim");
		e_128594 = (epytypeerror127016*) newObj((&NTI128323), sizeof(epytypeerror127016));
		(*e_128594).Sup.Sup.Sup.m_type = (&NTI127016);
		nimln(2150, "system.nim");
		LOC16 = 0;
		LOC16 = (*e_128594).Sup.Sup.message; (*e_128594).Sup.Sup.message = copyStringRC1(msg_128487);
		if (LOC16) nimGCunrefNoCycle(LOC16);
		nimln(249, "high_level.nim");
		raiseException((Exception*)e_128594, "EPyTypeError");
	}
	LA13: ;
	nimln(250, "high_level.nim");
	nimln(250, "high_level.nim");
	TMP302 = divInt((*result).Pybuf.Length, (*result).Pybuf.Itemsize);
	(*result).Nelements = ((NI) ((NI32)(TMP302)));
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, eval_127043)(context127018* c, NCSTRING src) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("eval", "high_level.nim")
	result = 0;
	nimln(260, "high_level.nim");
	nimln(260, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118767(src, 258, (*(*c).Globals).P, (*(*c).Locals).P);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, builtins_127065)(void) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("builtins", "high_level.nim")
	result = 0;
	nimln(262, "high_level.nim");
	nimln(262, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118656();
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(pyref127008*, pyimport_128640)(NCSTRING name) {
	pyref127008* result;
	tpyobject117591* LOC1;
	nimfr("pyImport", "high_level.nim")
	result = 0;
	nimln(265, "high_level.nim");
	nimln(265, "high_level.nim");
	LOC1 = 0;
	LOC1 = Dl_118966(name);
	result = wrapnew_127198(LOC1);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP304)(void* p, NI op) {
	context127018* a;
	a = (context127018*)p;
	nimGCvisit((void*)(*a).Globals, op);
	nimGCvisit((void*)(*a).Locals, op);
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell44933* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49429)(tcell44933* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45671((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51025)(tcell44933* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell44933* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49429(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell44933* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51025(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell44933* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(context127018*, initcontext_128650)(void) {
	context127018* result;
	pyref127008* b;
	pyref127008* LOC1;
	pyref127008* LOC2;
	nimfr("initContext", "high_level.nim")
	result = 0;
	nimln(268, "high_level.nim");
	result = (context127018*) newObj((&NTI127020), sizeof(context127018));
	nimln(269, "high_level.nim");
	asgnRef((void**) (&(*result).Locals), pydict_127078());
	nimln(270, "high_level.nim");
	asgnRef((void**) (&(*result).Globals), pydict_127078());
	nimln(271, "high_level.nim");
	b = builtins_127065();
	nimln(272, "high_level.nim");
	nimln(272, "high_level.nim");
	LOC1 = 0;
	LOC1 = topy_127329(((NimStringDesc*) &TMP305));
	HEX5BHEX5DHEX3D_127057((*result).Globals, LOC1, b);
	nimln(273, "high_level.nim");
	nimln(273, "high_level.nim");
	LOC2 = 0;
	LOC2 = topy_127329(((NimStringDesc*) &TMP305));
	HEX5BHEX5DHEX3D_127057((*result).Locals, LOC2, b);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimborg_high_levelInit)(void) {
	nimfr("high_level", "high_level.nim")
	nimln(237, "high_level.nim");
	defaultbufferflags_128180 = ((int) 5);
	nimln(298, "high_level.nim");
	initpython_121604();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimborg_high_levelDatInit)(void) {
static TNimNode* TMP272[2];
static TNimNode* TMP303[2];
static TNimNode TMP239[10];
NTI127012.size = sizeof(epython127012);
NTI127012.kind = 17;
NTI127012.base = (&NTI3227);
TMP239[0].len = 0; TMP239[0].kind = 2;
NTI127012.node = &TMP239[0];
NTI127101.size = sizeof(epython127012*);
NTI127101.kind = 22;
NTI127101.base = (&NTI127012);
NTI127101.marker = TMP250;
NTI127008.size = sizeof(pyref127008);
NTI127008.kind = 17;
NTI127008.base = 0;
NTI127008.flags = 1;
TMP239[1].kind = 1;
TMP239[1].offset = offsetof(pyref127008, P);
TMP239[1].typ = (&NTI117481);
TMP239[1].name = "p";
NTI127008.node = &TMP239[1];
NTI127010.size = sizeof(pyref127008*);
NTI127010.kind = 22;
NTI127010.base = (&NTI127008);
NTI127010.marker = TMP262;
(&NTI127010)->finalizer = (void*)finalizepyref_127172;
(&NTI127010)->finalizer = (void*)finalizepyref_127172;
(&NTI128024)->finalizer = (void*)finalizerawpybuffer_128022;
NTI128111.size = sizeof(typedpybuffer1d128111);
NTI128111.kind = 18;
NTI128111.base = 0;
NTI128111.flags = 3;
TMP272[0] = &TMP239[3];
TMP239[3].kind = 1;
TMP239[3].offset = offsetof(typedpybuffer1d128111, Pybuf);
TMP239[3].typ = (&NTI117665);
TMP239[3].name = "pyBuf";
TMP272[1] = &TMP239[4];
TMP239[4].kind = 1;
TMP239[4].offset = offsetof(typedpybuffer1d128111, Nelements);
TMP239[4].typ = (&NTI108);
TMP239[4].name = "nElements";
TMP239[2].len = 2; TMP239[2].kind = 2; TMP239[2].sons = &TMP272[0];
NTI128111.node = &TMP239[2];
NTI128240.size = sizeof(typedpybuffer1d128111*);
NTI128240.kind = 22;
NTI128240.base = (&NTI128111);
NTI128240.flags = 2;
NTI128240.marker = TMP273;
(&NTI128240)->finalizer = (void*)finalizetypedpybuffer1d_128231;
NTI127014.size = sizeof(epynotsupported127014);
NTI127014.kind = 17;
NTI127014.base = (&NTI127012);
TMP239[5].len = 0; TMP239[5].kind = 2;
NTI127014.node = &TMP239[5];
NTI128300.size = sizeof(epynotsupported127014*);
NTI128300.kind = 22;
NTI128300.base = (&NTI127014);
NTI128300.marker = TMP274;
NTI127016.size = sizeof(epytypeerror127016);
NTI127016.kind = 17;
NTI127016.base = (&NTI127012);
TMP239[6].len = 0; TMP239[6].kind = 2;
NTI127016.node = &TMP239[6];
NTI128323.size = sizeof(epytypeerror127016*);
NTI128323.kind = 22;
NTI128323.base = (&NTI127016);
NTI128323.marker = TMP295;
NTI128376.size = sizeof(typedpybuffer1d128111*);
NTI128376.kind = 22;
NTI128376.base = (&NTI128111);
NTI128376.flags = 2;
NTI128376.marker = TMP297;
(&NTI128376)->finalizer = (void*)finalizetypedpybuffer1d_128367;
NTI128512.size = sizeof(typedpybuffer1d128111*);
NTI128512.kind = 22;
NTI128512.base = (&NTI128111);
NTI128512.flags = 2;
NTI128512.marker = TMP300;
(&NTI128512)->finalizer = (void*)finalizetypedpybuffer1d_128503;
NTI127018.size = sizeof(context127018);
NTI127018.kind = 18;
NTI127018.base = 0;
TMP303[0] = &TMP239[8];
TMP239[8].kind = 1;
TMP239[8].offset = offsetof(context127018, Globals);
TMP239[8].typ = (&NTI127010);
TMP239[8].name = "globals";
TMP303[1] = &TMP239[9];
TMP239[9].kind = 1;
TMP239[9].offset = offsetof(context127018, Locals);
TMP239[9].typ = (&NTI127010);
TMP239[9].name = "locals";
TMP239[7].len = 2; TMP239[7].kind = 2; TMP239[7].sons = &TMP303[0];
NTI127018.node = &TMP239[7];
NTI127020.size = sizeof(context127018*);
NTI127020.kind = 22;
NTI127020.base = (&NTI127018);
NTI127020.marker = TMP304;
}

