/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_dynlib.o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_dynlib.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <windows.h>
typedef struct libraryerror3235 libraryerror3235;
typedef struct oserror3233 oserror3233;
typedef struct systemerror3229 systemerror3229;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  oserror3233  {
  systemerror3229 Sup;
NI32 Errorcode;
};
struct  libraryerror3235  {
  oserror3233 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
N_NOINLINE(void, raiseinvalidlibrary_116041)(NCSTRING name);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void*, checkedsymaddr_116076)(void* lib, NCSTRING name);
N_NIMCALL(void*, loadlib_116023)(NimStringDesc* path, NIM_BOOL globalsymbols);
N_NIMCALL(void*, loadlib_116030)(void);
N_NIMCALL(void, unloadlib_116035)(void* lib);
N_NIMCALL(void*, symaddr_116069)(void* lib, NCSTRING name);
STRING_LITERAL(TMP238, "could not find symbol: ", 23);
extern TNimType NTI116044; /* ref LibraryError */
extern TNimType NTI3235; /* LibraryError */
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NOINLINE(void, raiseinvalidlibrary_116041)(NCSTRING name) {
	libraryerror3235* e;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("raiseInvalidLibrary", "dynlib.nim")
	e = 0;
	nimln(33, "dynlib.nim");
	e = (libraryerror3235*) newObj((&NTI116044), sizeof(libraryerror3235));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI3235);
	nimln(34, "dynlib.nim");
	nimln(34, "dynlib.nim");
	LOC1 = 0;
	nimln(34, "dynlib.nim");
	LOC2 = 0;
	LOC2 = cstrToNimstr(name);
	LOC1 = rawNewString(LOC2->Sup.len + 23);
appendString(LOC1, ((NimStringDesc*) &TMP238));
appendString(LOC1, LOC2);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), LOC1);
	nimln(35, "dynlib.nim");
	raiseException((Exception*)e, "LibraryError");
	popFrame();
}

N_NIMCALL(void*, checkedsymaddr_116076)(void* lib, NCSTRING name) {
	void* result;
	nimfr("checkedSymAddr", "dynlib.nim")
	result = 0;
	nimln(44, "dynlib.nim");
	result = symaddr_116069(lib, name);
	nimln(45, "dynlib.nim");
	{
		nimln(45, "dynlib.nim");
		if (!(result == NIM_NIL)) goto LA3;
		nimln(45, "dynlib.nim");
		raiseinvalidlibrary_116041(name);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void*, loadlib_116023)(NimStringDesc* path, NIM_BOOL globalsymbols) {
	void* result;
	void* LOC1;
	nimfr("loadLib", "dynlib.nim")
	result = 0;
	nimln(91, "dynlib.nim");
	nimln(91, "dynlib.nim");
	LOC1 = 0;
	LOC1 = LoadLibraryA(path->data);
	result = ((void*) (LOC1));
	popFrame();
	return result;
}

N_NIMCALL(void*, loadlib_116030)(void) {
	void* result;
	void* LOC1;
	nimfr("loadLib", "dynlib.nim")
	result = 0;
	nimln(93, "dynlib.nim");
	nimln(93, "dynlib.nim");
	LOC1 = 0;
	LOC1 = LoadLibraryA(NIM_NIL);
	result = ((void*) (LOC1));
	popFrame();
	return result;
}

N_NIMCALL(void, unloadlib_116035)(void* lib) {
	nimfr("unloadLib", "dynlib.nim")
	nimln(94, "dynlib.nim");
	FreeLibrary(((void*) (lib)));
	popFrame();
}

N_NIMCALL(void*, symaddr_116069)(void* lib, NCSTRING name) {
	void* result;
	nimfr("symAddr", "dynlib.nim")
	result = 0;
	nimln(97, "dynlib.nim");
	result = GetProcAddress(((void*) (lib)), name);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit)(void) {
	nimfr("dynlib", "dynlib.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit)(void) {
}

