/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_winlean.o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_winlean.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include "Winsock2.h"

#include <string.h>

#include "winsock2.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tsecurityattributes104270 tsecurityattributes104270;
typedef struct tstartupinfo104272 tstartupinfo104272;
typedef struct tprocessinformation104274 tprocessinformation104274;
typedef struct twin32finddata105219 twin32finddata105219;
typedef struct tfiletime104276 tfiletime104276;
typedef struct tbyhandlefileinformation104278 tbyhandlefileinformation104278;
typedef struct servent105860 servent105860;
typedef struct hostent105862 hostent105862;
typedef struct tfdset105864 tfdset105864;
typedef struct timeval105866 timeval105866;
typedef struct addrinfo105868 addrinfo105868;
typedef struct toverlapped106608 toverlapped106608;
typedef struct tguid106614 tguid106614;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, TY104425) (NI hobject);
typedef N_STDCALL_PTR(NI32, TY104431) (NI hfile, void* buffer, NI32 nnumberofbytestoread, NI32* lpnumberofbytesread, void* lpoverlapped);
typedef N_STDCALL_PTR(NI32, TY104442) (NI hfile, void* buffer, NI32 nnumberofbytestowrite, NI32* lpnumberofbyteswritten, void* lpoverlapped);
typedef N_STDCALL_PTR(NI32, TY104453) (NI* hreadpipe, NI* hwritepipe, tsecurityattributes104270* lppipeattributes, NI32 nsize);
typedef N_STDCALL_PTR(NI32, TY104464) (NI16* lpapplicationname, NI16* lpcommandline, tsecurityattributes104270* lpprocessattributes, tsecurityattributes104270* lpthreadattributes, NI32 binherithandles, NI32 dwcreationflags, NI16* lpenvironment, NI16* lpcurrentdirectory, tstartupinfo104272* lpstartupinfo, tprocessinformation104274* lpprocessinformation);
typedef N_STDCALL_PTR(NI32, TY104605) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY104611) (NI hthread);
typedef N_STDCALL_PTR(NI32, TY104617) (NI hhandle, NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI32, TY104624) (NI hprocess, NI uexitcode);
typedef N_STDCALL_PTR(NI32, TY104631) (NI hprocess, NI32* lpexitcode);
typedef N_STDCALL_PTR(NI, TY104639) (NI32 nstdhandle);
typedef N_STDCALL_PTR(NI32, TY104645) (NI32 nstdhandle, NI hhandle);
typedef N_STDCALL_PTR(NI32, TY104652) (NI hfile);
typedef N_STDCALL_PTR(NI32, TY104658) (void);
typedef N_STDCALL_PTR(NI32, TY104663) (NI32 dwflags, void* lpsource, NI32 dwmessageid, NI32 dwlanguageid, void* lpbuffer, NI32 nsize, void* arguments);
typedef N_STDCALL_PTR(void, TY104805) (void* p);
typedef N_STDCALL_PTR(NI32, TY104811) (NI32 nbufferlength, NI16* lpbuffer);
typedef N_STDCALL_PTR(NI32, TY104815) (NI16* lppathname);
typedef N_STDCALL_PTR(NI32, TY104818) (NI16* pathname, void* security);
typedef N_STDCALL_PTR(NI32, TY104822) (NI16* lppathname);
typedef N_STDCALL_PTR(NI32, TY104825) (NI16* lpname, NI16* lpvalue);
typedef N_STDCALL_PTR(NI32, TY104829) (NI handle, NI16* buf, NI32 size);
typedef N_STDCALL_PTR(NI32, TY105005) (NI16* lpsymlinkfilename, NI16* lptargetfilename, NI32 flags);
typedef N_STDCALL_PTR(NI32, TY105010) (NI16* lpfilename, NI16* lpexistingfilename, void* security);
typedef N_STDCALL_PTR(NI, TY105240) (NI16* lpfilename, twin32finddata105219* lpfindfiledata);
typedef N_STDCALL_PTR(NI32, TY105245) (NI hfindfile, twin32finddata105219* lpfindfiledata);
typedef N_STDCALL_PTR(void, TY105405) (NI hfindfile);
typedef N_STDCALL_PTR(NI32, TY105411) (NI16* lpfilename, NI32 nbufferlength, NI16* lpbuffer, NI16** lpfilepart);
typedef N_STDCALL_PTR(NI32, TY105418) (NI16* lpfilename);
typedef N_STDCALL_PTR(NI32, TY105421) (NI16* lpfilename, NI32 dwfileattributes);
typedef N_STDCALL_PTR(int, TY105425) (NI16* lpexistingfilename, NI16* lpnewfilename, int bfailifexists);
typedef N_STDCALL_PTR(NI16*, TY105430) (void);
typedef N_STDCALL_PTR(NI32, TY105432) (NI16* para1);
typedef N_STDCALL_PTR(NI16*, TY105435) (void);
struct  tfiletime104276  {
NI32 Dwlowdatetime;
NI32 Dwhighdatetime;
};
typedef NI16 TY105228[260];
typedef NI16 TY105232[14];
struct  twin32finddata105219  {
NI32 Dwfileattributes;
tfiletime104276 Ftcreationtime;
tfiletime104276 Ftlastaccesstime;
tfiletime104276 Ftlastwritetime;
NI32 Nfilesizehigh;
NI32 Nfilesizelow;
NI32 Dwreserved0;
NI32 Dwreserved1;
TY105228 Cfilename;
TY105232 Calternatefilename;
};
typedef N_STDCALL_PTR(void, TY105625) (tfiletime104276* lpsystemtimeasfiletime);
typedef N_STDCALL_PTR(void, TY105632) (NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI, TY105638) (NI hwnd, NI16* lpoperation, NI16* lpfile, NI16* lpparameters, NI16* lpdirectory, NI32 nshowcmd);
typedef N_STDCALL_PTR(NI32, TY105805) (NI hfile, tbyhandlefileinformation104278* lpfileinformation);
typedef N_CDECL_PTR(int, TY105832) (void);
typedef N_STDCALL_PTR(servent105860*, TY105991) (NCSTRING name, NCSTRING proto);
typedef N_STDCALL_PTR(servent105860*, TY105999) (int port, NCSTRING proto);
typedef N_STDCALL_PTR(hostent105862*, TY106007) (IN_ADDR* ip, int len, int thetype);
typedef N_STDCALL_PTR(hostent105862*, TY106017) (NCSTRING name);
typedef N_STDCALL_PTR(NI, TY106024) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, TY106032) (NI s);
typedef N_STDCALL_PTR(NI, TY106038) (NI s, SOCKADDR* a, int* addrlen);
typedef N_STDCALL_PTR(int, TY106048) (NI s, SOCKADDR* name, int namelen);
typedef N_STDCALL_PTR(int, TY106057) (NI s, SOCKADDR* name, int namelen);
typedef N_STDCALL_PTR(int, TY106066) (NI s, SOCKADDR* name, int* namelen);
typedef N_STDCALL_PTR(int, TY106076) (NI s, int level, int optname, void* optval, int* optlen);
typedef N_STDCALL_PTR(int, TY106087) (NI s, int level, int optname, void* optval, int optlen);
typedef N_STDCALL_PTR(int, TY106097) (NI s, int backlog);
typedef N_STDCALL_PTR(int, TY106104) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(int, TY106113) (NI s, NCSTRING buf, int len, int flags, SOCKADDR* fromm, int* fromlen);
typedef N_STDCALL_PTR(int, TY106126) (int nfds, tfdset105864* readfds, tfdset105864* writefds, tfdset105864* exceptfds, timeval105866* timeout);
typedef N_STDCALL_PTR(int, TY106138) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(int, TY106147) (NI s, void* buf, int len, int flags, SOCKADDR* to, int tolen);
typedef N_STDCALL_PTR(int, TY106159) (NI s, int how);
typedef N_STDCALL_PTR(int, TY106166) (SOCKADDR* a1, int a2, NCSTRING a3, int a4, NCSTRING a5, int a6, int a7);
typedef N_STDCALL_PTR(NI32, TY106179) (NCSTRING cp);
typedef N_STDCALL_PTR(NIM_BOOL, TY106185) (NI s, tfdset105864* set);
typedef NI TY105915[64];
struct  tfdset105864  {
int Fdcount;
TY105915 Fdarray;
};
typedef N_STDCALL_PTR(int, TY106241) (NI16 wversionrequired, WSADATA* wsdata);
typedef N_STDCALL_PTR(int, TY106249) (NCSTRING nodename, NCSTRING servname, addrinfo105868* hints, addrinfo105868** res);
typedef N_STDCALL_PTR(void, TY106261) (addrinfo105868* ai);
typedef N_STDCALL_PTR(NCSTRING, TY106268) (IN_ADDR i);
typedef N_STDCALL_PTR(NI32, TY106286) (NI32 ncount, NI* lphandles, NI32 bwaitall, NI32 dwmilliseconds);
typedef N_STDCALL_PTR(NI, TY106323) (NI16* lpfilename, NI32 dwdesiredaccess, NI32 dwsharemode, void* lpsecurityattributes, NI32 dwcreationdisposition, NI32 dwflagsandattributes, NI htemplatefile);
typedef N_STDCALL_PTR(NI32, TY106332) (NI16* pathname);
typedef N_STDCALL_PTR(NI32, TY106405) (NI hfile);
typedef N_STDCALL_PTR(NI32, TY106411) (NI hfile, NI32 ldistancetomove, NI32* lpdistancetomovehigh, NI32 dwmovemethod);
typedef N_STDCALL_PTR(NI32, TY106421) (NI hfile, NI32* lpfilesizehigh);
typedef N_STDCALL_PTR(void*, TY106429) (NI hfilemappingobject, NI32 dwdesiredaccess, NI32 dwfileoffsethigh, NI32 dwfileoffsetlow, NI32 dwnumberofbytestomap, void* lpbaseaddress);
typedef N_STDCALL_PTR(NI, TY106440) (NI hfile, void* lpfilemappingattributes, NI32 flprotect, NI32 dwmaximumsizehigh, NI32 dwmaximumsizelow, void* lpname);
typedef N_STDCALL_PTR(NI32, TY106602) (void* lpbaseaddress);
typedef N_STDCALL_PTR(NI, TY106652) (NI filehandle, NI existingcompletionport, NI32 completionkey, NI32 numberofconcurrentthreads);
typedef N_STDCALL_PTR(NI32, TY106661) (NI completionport, NI32* lpnumberofbytestransferred, NI* lpcompletionkey, toverlapped106608** lpoverlapped, NI32 dwmilliseconds);
struct  toverlapped106608  {
NI* Internal;
NI* Internalhigh;
NI32 Offset;
NI32 Offsethigh;
NI Hevent;
};
typedef N_STDCALL_PTR(NI32, TY106672) (NI hfile, toverlapped106608* lpoverlapped, NI32* lpnumberofbytestransferred, NI32 bwait);
typedef NI8 TY106627[8];
struct  tguid106614  {
NI32 D1;
NI16 D2;
NI16 D3;
TY106627 D4;
};
typedef NI8 TY106708[8];
typedef N_STDCALL_PTR(void, poverlappedcompletionroutine106612) (NI32 para1, NI32 para2, toverlapped106608* para3);
typedef N_STDCALL_PTR(int, TY106729) (NI s, NI32 dwiocontrolcode, void* lpvinbuffer, NI32 cbinbuffer, void* lpvoutbuffer, NI32 cboutbuffer, NI32* lpcbbytesreturned, toverlapped106608* lpoverlapped, poverlappedcompletionroutine106612 lpcompletionroutine);
typedef N_STDCALL_PTR(int, TY106750) (NI s, WSABUF* buf, NI32 bufcount, NI32* bytesreceived, NI32* flags, toverlapped106608* lpoverlapped, poverlappedcompletionroutine106612 completionproc);
typedef N_STDCALL_PTR(int, TY106763) (NI s, WSABUF* buf, NI32 bufcount, NI32* bytessent, NI32 flags, toverlapped106608* lpoverlapped, poverlappedcompletionroutine106612 completionproc);
typedef N_STDCALL_PTR(NI32, TY106782) (tfiletime104276* lpidletime, tfiletime104276* lpkerneltime, tfiletime104276* lpusertime);
typedef N_STDCALL_PTR(NI32, TY106791) (NI hprocess, tfiletime104276* lpcreationtime, tfiletime104276* lpexittime, tfiletime104276* lpkerneltime, tfiletime104276* lpusertime);
struct  tsecurityattributes104270  {
NI32 Nlength;
void* Lpsecuritydescriptor;
NI32 Binherithandle;
};
struct  tstartupinfo104272  {
NI32 Cb;
NCSTRING Lpreserved;
NCSTRING Lpdesktop;
NCSTRING Lptitle;
NI32 Dwx;
NI32 Dwy;
NI32 Dwxsize;
NI32 Dwysize;
NI32 Dwxcountchars;
NI32 Dwycountchars;
NI32 Dwfillattribute;
NI32 Dwflags;
NI16 Wshowwindow;
NI16 Cbreserved2;
void* Lpreserved2;
NI Hstdinput;
NI Hstdoutput;
NI Hstderror;
};
struct  tprocessinformation104274  {
NI Hprocess;
NI Hthread;
NI32 Dwprocessid;
NI32 Dwthreadid;
};
struct  tbyhandlefileinformation104278  {
NI32 Dwfileattributes;
tfiletime104276 Ftcreationtime;
tfiletime104276 Ftlastaccesstime;
tfiletime104276 Ftlastwritetime;
NI32 Dwvolumeserialnumber;
NI32 Nfilesizehigh;
NI32 Nfilesizelow;
NI32 Nnumberoflinks;
NI32 Nfileindexhigh;
NI32 Nfileindexlow;
};
struct  servent105860  {
NCSTRING Sname;
NCSTRING* Saliases;
NI16 Sport;
NCSTRING Sproto;
};
struct  hostent105862  {
NCSTRING Hname;
NCSTRING* Haliases;
NI16 Haddrtype;
NI16 Hlength;
NCSTRING* Haddrlist;
};
typedef NIM_CHAR TY105883[14];
struct  timeval105866  {
NI32 Tvsec;
NI32 Tvusec;
};
typedef NIM_CHAR TY105873[257];
typedef NIM_CHAR TY105876[129];
struct  addrinfo105868  {
int Aiflags;
int Aifamily;
int Aisocktype;
int Aiprotocol;
NI Aiaddrlen;
NCSTRING Aicanonname;
SOCKADDR* Aiaddr;
addrinfo105868* Ainext;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(NI64, rdfiletime_105604)(tfiletime104276 f);
N_NIMCALL(NI64, rdfilesize_105614)(twin32finddata105219* f);
N_NIMCALL(int, fdisset_106192)(NI socket, tfdset105864* set);
N_NIMCALL(void, fdset_106204)(NI socket, tfdset105864* s);
N_NIMCALL(void, fdzero_106230)(tfdset105864* s);
STRING_LITERAL(TMP153, "kernel32", 8);
STRING_LITERAL(TMP154, "kernel32", 8);
STRING_LITERAL(TMP156, "shell32.dll", 11);
STRING_LITERAL(TMP157, "shell32.dll", 11);
STRING_LITERAL(TMP159, "Ws2_32.dll", 10);
STRING_LITERAL(TMP160, "Ws2_32.dll", 10);
NIM_CONST TY106708 TMP161 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST TY106708 TMP162 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
static void* TMP152;
TY104425 Dl_104424;
TY104431 Dl_104430;
TY104442 Dl_104441;
TY104453 Dl_104452;
TY104464 Dl_104463;
TY104605 Dl_104604;
TY104611 Dl_104610;
TY104617 Dl_104616;
TY104624 Dl_104623;
TY104631 Dl_104630;
TY104639 Dl_104638;
TY104645 Dl_104644;
TY104652 Dl_104651;
TY104658 Dl_104657;
TY104663 Dl_104662;
TY104805 Dl_104804;
TY104811 Dl_104810;
TY104815 Dl_104814;
TY104818 Dl_104817;
TY104822 Dl_104821;
TY104825 Dl_104824;
TY104829 Dl_104828;
TY105005 Dl_105004;
TY105010 Dl_105009;
TY105240 Dl_105239;
TY105245 Dl_105244;
TY105405 Dl_105404;
TY105411 Dl_105410;
TY105418 Dl_105417;
TY105421 Dl_105420;
TY105425 Dl_105424;
TY105430 Dl_105429;
TY105432 Dl_105431;
TY105435 Dl_105434;
TY105625 Dl_105624;
TY105632 Dl_105631;
static void* TMP155;
TY105638 Dl_105637;
TY105805 Dl_105804;
static void* TMP158;
TY105832 Dl_105831;
TY105991 Dl_105990;
TY105999 Dl_105998;
TY106007 Dl_106006;
TY106017 Dl_106016;
TY106024 Dl_106023;
TY106032 Dl_106031;
TY106038 Dl_106037;
TY106048 Dl_106047;
TY106057 Dl_106056;
TY106066 Dl_106065;
TY106076 Dl_106075;
TY106087 Dl_106086;
TY106097 Dl_106096;
TY106104 Dl_106103;
TY106113 Dl_106112;
TY106126 Dl_106125;
TY106138 Dl_106137;
TY106147 Dl_106146;
TY106159 Dl_106158;
TY106166 Dl_106165;
TY106179 Dl_106178;
TY106185 Dl_106184;
TY106241 Dl_106240;
TY106249 Dl_106248;
TY106261 Dl_106260;
TY106268 Dl_106267;
TY106286 Dl_106285;
TY106323 Dl_106322;
TY106332 Dl_106331;
TY106405 Dl_106404;
TY106411 Dl_106410;
TY106421 Dl_106420;
TY106429 Dl_106428;
TY106440 Dl_106439;
TY106602 Dl_106601;
TY106652 Dl_106651;
TY106661 Dl_106660;
TY106672 Dl_106671;
tguid106614 wsaidconnectex_106710;
tguid106614 wsaidacceptex_106714;
tguid106614 wsaidgetacceptexsockaddrs_106718;
TY106729 Dl_106728;
TY106750 Dl_106749;
TY106763 Dl_106762;
TY106782 Dl_106781;
TY106791 Dl_106790;

N_NIMCALL(NI64, rdfiletime_105604)(tfiletime104276 f) {
	NI64 result;
	result = 0;
	result = (NI64)(((NI64)(NU64)(NU32)(f.Dwlowdatetime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.Dwhighdatetime))) << (NU64)(IL64(32))));
	return result;
}

N_NIMCALL(NI64, rdfilesize_105614)(twin32finddata105219* f) {
	NI64 result;
	result = 0;
	result = (NI64)(((NI64)(NU64)(NU32)((*f).Nfilesizelow)) | (NI64)((NU64)(((NI64)(NU64)(NU32)((*f).Nfilesizehigh))) << (NU64)(IL64(32))));
	return result;
}

N_NIMCALL(int, fdisset_106192)(NI socket, tfdset105864* set) {
	int result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = Dl_106184(socket, set);
		if (!LOC3) goto LA4;
		result = ((NI32) 1);
	}
	goto LA1;
	LA4: ;
	{
		result = ((NI32) 0);
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, fdset_106204)(NI socket, tfdset105864* s) {
	{
		if (!((*s).Fdcount < ((NI32) 64))) goto LA3;
		(*s).Fdarray[(((NI) ((*s).Fdcount)))- 0] = socket;
		(*s).Fdcount += 1;
	}
	LA3: ;
}

N_NIMCALL(void, fdzero_106230)(tfdset105864* s) {
	(*s).Fdcount = ((int) 0);
}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void) {
	tguid106614 LOC1;
	tguid106614 LOC2;
	tguid106614 LOC3;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.D1 = ((NI32) 631375801);
	LOC1.D2 = ((NI16) -8717);
	LOC1.D3 = ((NI16) 18016);
	memcpy((void*)LOC1.D4, (NIM_CONST void*)TMP161, sizeof(LOC1.D4));
	wsaidconnectex_106710 = LOC1;
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.D1 = ((NI32) -1254720015);
	LOC2.D2 = ((NI16) -13396);
	LOC2.D3 = ((NI16) 4559);
	memcpy((void*)LOC2.D4, (NIM_CONST void*)TMP162, sizeof(LOC2.D4));
	wsaidacceptex_106714 = LOC2;
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.D1 = ((NI32) -1254720014);
	LOC3.D2 = ((NI16) -13396);
	LOC3.D3 = ((NI16) 4559);
	memcpy((void*)LOC3.D4, (NIM_CONST void*)TMP162, sizeof(LOC3.D4));
	wsaidgetacceptexsockaddrs_106718 = LOC3;
}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void) {
if (!((TMP152 = nimLoadLibrary((NimStringDesc*) &TMP153))
)) nimLoadLibraryError((NimStringDesc*) &TMP154);
	Dl_104424 = (TY104425) nimGetProcAddr(TMP152, "CloseHandle");
	Dl_104430 = (TY104431) nimGetProcAddr(TMP152, "ReadFile");
	Dl_104441 = (TY104442) nimGetProcAddr(TMP152, "WriteFile");
	Dl_104452 = (TY104453) nimGetProcAddr(TMP152, "CreatePipe");
	Dl_104463 = (TY104464) nimGetProcAddr(TMP152, "CreateProcessW");
	Dl_104604 = (TY104605) nimGetProcAddr(TMP152, "SuspendThread");
	Dl_104610 = (TY104611) nimGetProcAddr(TMP152, "ResumeThread");
	Dl_104616 = (TY104617) nimGetProcAddr(TMP152, "WaitForSingleObject");
	Dl_104623 = (TY104624) nimGetProcAddr(TMP152, "TerminateProcess");
	Dl_104630 = (TY104631) nimGetProcAddr(TMP152, "GetExitCodeProcess");
	Dl_104638 = (TY104639) nimGetProcAddr(TMP152, "GetStdHandle");
	Dl_104644 = (TY104645) nimGetProcAddr(TMP152, "SetStdHandle");
	Dl_104651 = (TY104652) nimGetProcAddr(TMP152, "FlushFileBuffers");
	Dl_104657 = (TY104658) nimGetProcAddr(TMP152, "GetLastError");
	Dl_104662 = (TY104663) nimGetProcAddr(TMP152, "FormatMessageW");
	Dl_104804 = (TY104805) nimGetProcAddr(TMP152, "LocalFree");
	Dl_104810 = (TY104811) nimGetProcAddr(TMP152, "GetCurrentDirectoryW");
	Dl_104814 = (TY104815) nimGetProcAddr(TMP152, "SetCurrentDirectoryW");
	Dl_104817 = (TY104818) nimGetProcAddr(TMP152, "CreateDirectoryW");
	Dl_104821 = (TY104822) nimGetProcAddr(TMP152, "RemoveDirectoryW");
	Dl_104824 = (TY104825) nimGetProcAddr(TMP152, "SetEnvironmentVariableW");
	Dl_104828 = (TY104829) nimGetProcAddr(TMP152, "GetModuleFileNameW");
	Dl_105004 = (TY105005) nimGetProcAddr(TMP152, "CreateSymbolicLinkW");
	Dl_105009 = (TY105010) nimGetProcAddr(TMP152, "CreateHardLinkW");
	Dl_105239 = (TY105240) nimGetProcAddr(TMP152, "FindFirstFileW");
	Dl_105244 = (TY105245) nimGetProcAddr(TMP152, "FindNextFileW");
	Dl_105404 = (TY105405) nimGetProcAddr(TMP152, "FindClose");
	Dl_105410 = (TY105411) nimGetProcAddr(TMP152, "GetFullPathNameW");
	Dl_105417 = (TY105418) nimGetProcAddr(TMP152, "GetFileAttributesW");
	Dl_105420 = (TY105421) nimGetProcAddr(TMP152, "SetFileAttributesW");
	Dl_105424 = (TY105425) nimGetProcAddr(TMP152, "CopyFileW");
	Dl_105429 = (TY105430) nimGetProcAddr(TMP152, "GetEnvironmentStringsW");
	Dl_105431 = (TY105432) nimGetProcAddr(TMP152, "FreeEnvironmentStringsW");
	Dl_105434 = (TY105435) nimGetProcAddr(TMP152, "GetCommandLineW");
	Dl_105624 = (TY105625) nimGetProcAddr(TMP152, "GetSystemTimeAsFileTime");
	Dl_105631 = (TY105632) nimGetProcAddr(TMP152, "Sleep");
if (!((TMP155 = nimLoadLibrary((NimStringDesc*) &TMP156))
)) nimLoadLibraryError((NimStringDesc*) &TMP157);
	Dl_105637 = (TY105638) nimGetProcAddr(TMP155, "ShellExecuteW");
	Dl_105804 = (TY105805) nimGetProcAddr(TMP152, "GetFileInformationByHandle");
if (!((TMP158 = nimLoadLibrary((NimStringDesc*) &TMP159))
)) nimLoadLibraryError((NimStringDesc*) &TMP160);
	Dl_105831 = (TY105832) nimGetProcAddr(TMP158, "WSAGetLastError");
	Dl_105990 = (TY105991) nimGetProcAddr(TMP158, "getservbyname");
	Dl_105998 = (TY105999) nimGetProcAddr(TMP158, "getservbyport");
	Dl_106006 = (TY106007) nimGetProcAddr(TMP158, "gethostbyaddr");
	Dl_106016 = (TY106017) nimGetProcAddr(TMP158, "gethostbyname");
	Dl_106023 = (TY106024) nimGetProcAddr(TMP158, "socket");
	Dl_106031 = (TY106032) nimGetProcAddr(TMP158, "closesocket");
	Dl_106037 = (TY106038) nimGetProcAddr(TMP158, "accept");
	Dl_106047 = (TY106048) nimGetProcAddr(TMP158, "bind");
	Dl_106056 = (TY106057) nimGetProcAddr(TMP158, "connect");
	Dl_106065 = (TY106066) nimGetProcAddr(TMP158, "getsockname");
	Dl_106075 = (TY106076) nimGetProcAddr(TMP158, "getsockopt");
	Dl_106086 = (TY106087) nimGetProcAddr(TMP158, "setsockopt");
	Dl_106096 = (TY106097) nimGetProcAddr(TMP158, "listen");
	Dl_106103 = (TY106104) nimGetProcAddr(TMP158, "recv");
	Dl_106112 = (TY106113) nimGetProcAddr(TMP158, "recvfrom");
	Dl_106125 = (TY106126) nimGetProcAddr(TMP158, "select");
	Dl_106137 = (TY106138) nimGetProcAddr(TMP158, "send");
	Dl_106146 = (TY106147) nimGetProcAddr(TMP158, "sendto");
	Dl_106158 = (TY106159) nimGetProcAddr(TMP158, "shutdown");
	Dl_106165 = (TY106166) nimGetProcAddr(TMP158, "getnameinfo");
	Dl_106178 = (TY106179) nimGetProcAddr(TMP158, "inet_addr");
	Dl_106184 = (TY106185) nimGetProcAddr(TMP158, "__WSAFDIsSet");
	Dl_106240 = (TY106241) nimGetProcAddr(TMP158, "WSAStartup");
	Dl_106248 = (TY106249) nimGetProcAddr(TMP158, "getaddrinfo");
	Dl_106260 = (TY106261) nimGetProcAddr(TMP158, "freeaddrinfo");
	Dl_106267 = (TY106268) nimGetProcAddr(TMP158, "inet_ntoa");
	Dl_106285 = (TY106286) nimGetProcAddr(TMP152, "WaitForMultipleObjects");
	Dl_106322 = (TY106323) nimGetProcAddr(TMP152, "CreateFileW");
	Dl_106331 = (TY106332) nimGetProcAddr(TMP152, "DeleteFileW");
	Dl_106404 = (TY106405) nimGetProcAddr(TMP152, "SetEndOfFile");
	Dl_106410 = (TY106411) nimGetProcAddr(TMP152, "SetFilePointer");
	Dl_106420 = (TY106421) nimGetProcAddr(TMP152, "GetFileSize");
	Dl_106428 = (TY106429) nimGetProcAddr(TMP152, "MapViewOfFileEx");
	Dl_106439 = (TY106440) nimGetProcAddr(TMP152, "CreateFileMappingW");
	Dl_106601 = (TY106602) nimGetProcAddr(TMP152, "UnmapViewOfFile");
	Dl_106651 = (TY106652) nimGetProcAddr(TMP152, "CreateIoCompletionPort");
	Dl_106660 = (TY106661) nimGetProcAddr(TMP152, "GetQueuedCompletionStatus");
	Dl_106671 = (TY106672) nimGetProcAddr(TMP152, "GetOverlappedResult");
	Dl_106728 = (TY106729) nimGetProcAddr(TMP158, "WSAIoctl");
	Dl_106749 = (TY106750) nimGetProcAddr(TMP158, "WSARecv");
	Dl_106762 = (TY106763) nimGetProcAddr(TMP158, "WSASend");
	Dl_106781 = (TY106782) nimGetProcAddr(TMP152, "GetSystemTimes");
	Dl_106790 = (TY106791) nimGetProcAddr(TMP152, "GetProcessTimes");
}

