/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_tables.o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_tables.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct table122130 table122130;
typedef struct keyvaluepairseq122133 keyvaluepairseq122133;
typedef struct keyvaluepair122136 keyvaluepair122136;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct table122152 table122152;
typedef struct keyvaluepairseq122155 keyvaluepairseq122155;
typedef struct keyvaluepair122158 keyvaluepair122158;
typedef struct table122086 table122086;
typedef struct keyvaluepairseq122089 keyvaluepairseq122089;
typedef struct keyvaluepair122092 keyvaluepair122092;
typedef struct table122108 table122108;
typedef struct keyvaluepairseq122111 keyvaluepairseq122111;
typedef struct keyvaluepair122114 keyvaluepair122114;
typedef struct table122218 table122218;
typedef struct keyvaluepairseq122221 keyvaluepairseq122221;
typedef struct keyvaluepair122224 keyvaluepair122224;
typedef struct TY122641 TY122641;
typedef struct table122174 table122174;
typedef struct keyvaluepairseq122177 keyvaluepairseq122177;
typedef struct keyvaluepair122180 keyvaluepair122180;
typedef struct TY122470 TY122470;
typedef struct table122196 table122196;
typedef struct keyvaluepairseq122199 keyvaluepairseq122199;
typedef struct keyvaluepair122202 keyvaluepair122202;
typedef struct TY122527 TY122527;
typedef struct table125861 table125861;
typedef struct keyvaluepairseq125864 keyvaluepairseq125864;
typedef struct keyvaluepair125867 keyvaluepair125867;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct TY107550 TY107550;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct keyvaluepair122136 {
NU8 Field0;
NCSTRING Field1;
NCSTRING Field2;
};
struct  table122130  {
keyvaluepairseq122133* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct keyvaluepair122158 {
NU8 Field0;
NCSTRING Field1;
NimStringDesc* Field2;
};
struct  table122152  {
keyvaluepairseq122155* Data;
NI Counter;
};
struct keyvaluepair122092 {
NU8 Field0;
NCSTRING Field1;
NI Field2;
};
struct  table122086  {
keyvaluepairseq122089* Data;
NI Counter;
};
struct keyvaluepair122114 {
NU8 Field0;
NCSTRING Field1;
NF Field2;
};
struct  table122108  {
keyvaluepairseq122111* Data;
NI Counter;
};
struct keyvaluepair122224 {
NU8 Field0;
NCSTRING Field1;
TY122641* Field2;
};
struct  table122218  {
keyvaluepairseq122221* Data;
NI Counter;
};
struct keyvaluepair122180 {
NU8 Field0;
NCSTRING Field1;
TY122470* Field2;
};
struct  table122174  {
keyvaluepairseq122177* Data;
NI Counter;
};
struct keyvaluepair122202 {
NU8 Field0;
NCSTRING Field1;
TY122527* Field2;
};
struct  table122196  {
keyvaluepairseq122199* Data;
NI Counter;
};
struct keyvaluepair125867 {
NU8 Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  table125861  {
keyvaluepairseq125864* Data;
NI Counter;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
struct TY107550 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
struct keyvaluepairseq122133 {
  TGenericSeq Sup;
  keyvaluepair122136 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122155 {
  TGenericSeq Sup;
  keyvaluepair122158 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122089 {
  TGenericSeq Sup;
  keyvaluepair122092 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122111 {
  TGenericSeq Sup;
  keyvaluepair122114 data[SEQ_DECL_SIZE];
};
struct TY122641 {
  TGenericSeq Sup;
  NCSTRING data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122221 {
  TGenericSeq Sup;
  keyvaluepair122224 data[SEQ_DECL_SIZE];
};
struct TY122470 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122177 {
  TGenericSeq Sup;
  keyvaluepair122180 data[SEQ_DECL_SIZE];
};
struct TY122527 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq122199 {
  TGenericSeq Sup;
  keyvaluepair122202 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq125864 {
  TGenericSeq Sup;
  keyvaluepair125867 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_113302)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_86825)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_113410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NIM_BOOL, ispoweroftwo_110318)(NI x);
N_NIMCALL(void, TMP272)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP275)(void* p, NI op);
N_NIMCALL(void, TMP278)(void* p, NI op);
N_NIMCALL(void, TMP281)(void* p, NI op);
N_NIMCALL(void, TMP284)(void* p, NI op);
N_NIMCALL(void, TMP287)(void* p, NI op);
N_NIMCALL(void, TMP290)(void* p, NI op);
N_NIMCALL(void, TMP309)(void* p, NI op);
N_NIMCALL(NI, rawget_126043)(table125861 t_126050, NimStringDesc* key_126053);
N_NIMCALL(NI, hash_100842)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, enlarge_126100)(table125861* t_126109);
N_NIMCALL(void, rawinsert_126170)(table125861* t_126179, keyvaluepairseq125864** data_126187, NimStringDesc* key_126191, NimStringDesc* val_126193);
N_NIMCALL(void, inittable_125880)(NI initialsize_125885, table125861* Result);
N_NIMCALL(NI, nextpoweroftwo_110328)(NI x);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX5BHEX5DHEX3D_126025)(table125861* t_126034, NimStringDesc* key_126038, NimStringDesc* val_126040);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, rawget_126498)(table122152 t_126505, NCSTRING key_126508);
static N_INLINE(NI, hash_100401)(void* x);
N_NIMCALL(void, enlarge_126555)(table122152* t_126564);
N_NIMCALL(void, rawinsert_126625)(table122152* t_126634, keyvaluepairseq122155** data_126642, NCSTRING key_126646, NimStringDesc* val_126648);
STRING_LITERAL(TMP227, "length > counter ", 17);
STRING_LITERAL(TMP267, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_16242;
TNimType NTI122136; /* KeyValuePair */
TNimType NTI113009; /* SlotEnum */
extern TNimType NTI151; /* cstring */
TNimType NTI122133; /* KeyValuePairSeq */
TNimType NTI122130; /* Table */
extern TNimType NTI108; /* int */
TNimType NTI122158; /* KeyValuePair */
extern TNimType NTI149; /* string */
TNimType NTI122155; /* KeyValuePairSeq */
TNimType NTI122152; /* Table */
TNimType NTI122092; /* KeyValuePair */
TNimType NTI122089; /* KeyValuePairSeq */
TNimType NTI122086; /* Table */
TNimType NTI122114; /* KeyValuePair */
extern TNimType NTI128; /* float */
TNimType NTI122111; /* KeyValuePairSeq */
TNimType NTI122108; /* Table */
TNimType NTI122224; /* KeyValuePair */
extern TNimType NTI122641; /* seq[cstring] */
TNimType NTI122221; /* KeyValuePairSeq */
TNimType NTI122218; /* Table */
TNimType NTI122180; /* KeyValuePair */
extern TNimType NTI122470; /* seq[int] */
TNimType NTI122177; /* KeyValuePairSeq */
TNimType NTI122174; /* Table */
TNimType NTI122202; /* KeyValuePair */
extern TNimType NTI122527; /* seq[float] */
TNimType NTI122199; /* KeyValuePairSeq */
TNimType NTI122196; /* Table */
TNimType NTI125867; /* KeyValuePair */
TNimType NTI125864; /* KeyValuePairSeq */
extern tgcheap47016 gch_47044;
TNimType NTI125861; /* Table */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_113302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP228;
	NI TMP229;
	NI TMP230;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(120, "tables.nim");
	{
		nimln(120, "tables.nim");
		nimln(120, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(120, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP227));
	}
	LA3: ;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	LOC5 = 0;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP228 = mulInt(length, 2);
	nimln(121, "tables.nim");
	TMP229 = mulInt(counter, 3);
	LOC5 = ((NI32)(TMP228) < (NI32)(TMP229));
	if (LOC5) goto LA6;
	nimln(121, "tables.nim");
	nimln(121, "tables.nim");
	TMP230 = subInt(length, counter);
	LOC5 = ((NI32)(TMP230) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_113410)(NI h, NI maxhash) {
	NI result;
	NI TMP231;
	NI TMP232;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	nimln(124, "tables.nim");
	TMP231 = mulInt(5, h);
	TMP232 = addInt((NI32)(TMP231), 1);
	result = (NI)((NI32)(TMP232) & maxhash);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP272)(void* p, NI op) {
	keyvaluepairseq122133* a;
	NI LOC1;
	a = (keyvaluepairseq122133*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittable_123510)(NI initialsize_123515, table122130* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_123515);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122133*) newSeq((&NTI122133), initialsize_123515));
	popFrame();
}
N_NIMCALL(void, TMP275)(void* p, NI op) {
	keyvaluepairseq122155* a;
	NI LOC1;
	a = (keyvaluepairseq122155*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_123631)(NI initialsize_123636, table122152* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_123636);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122155*) newSeq((&NTI122155), initialsize_123636));
	popFrame();
}
N_NIMCALL(void, TMP278)(void* p, NI op) {
	keyvaluepairseq122089* a;
	NI LOC1;
	a = (keyvaluepairseq122089*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittable_123831)(NI initialsize_123836, table122086* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_123836);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122089*) newSeq((&NTI122089), initialsize_123836));
	popFrame();
}
N_NIMCALL(void, TMP281)(void* p, NI op) {
	keyvaluepairseq122111* a;
	NI LOC1;
	a = (keyvaluepairseq122111*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittable_124031)(NI initialsize_124036, table122108* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_124036);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122111*) newSeq((&NTI122111), initialsize_124036));
	popFrame();
}
N_NIMCALL(void, TMP284)(void* p, NI op) {
	keyvaluepairseq122221* a;
	NI LOC1;
	a = (keyvaluepairseq122221*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_124231)(NI initialsize_124236, table122218* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_124236);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122221*) newSeq((&NTI122221), initialsize_124236));
	popFrame();
}
N_NIMCALL(void, TMP287)(void* p, NI op) {
	keyvaluepairseq122177* a;
	NI LOC1;
	a = (keyvaluepairseq122177*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_124431)(NI initialsize_124436, table122174* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_124436);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122177*) newSeq((&NTI122177), initialsize_124436));
	popFrame();
}
N_NIMCALL(void, TMP290)(void* p, NI op) {
	keyvaluepairseq122199* a;
	NI LOC1;
	a = (keyvaluepairseq122199*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_124631)(NI initialsize_124636, table122196* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_124636);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq122199*) newSeq((&NTI122199), initialsize_124636));
	popFrame();
}
N_NIMCALL(void, TMP309)(void* p, NI op) {
	keyvaluepairseq125864* a;
	NI LOC1;
	a = (keyvaluepairseq125864*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_125880)(NI initialsize_125885, table125861* Result) {
	nimfr("initTable", "tables.nim")
	nimln(229, "tables.nim");
	{
		NIM_BOOL LOC3;
		nimln(229, "tables.nim");
		nimln(229, "tables.nim");
		LOC3 = 0;
		LOC3 = ispoweroftwo_110318(initialsize_125885);
		if (!!(LOC3)) goto LA4;
		nimln(229, "tables.nim");
		failedassertimpl_86825(((NimStringDesc*) &TMP267));
	}
	LA4: ;
	nimln(230, "tables.nim");
	(*Result).Counter = 0;
	nimln(231, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq125864*) newSeq((&NTI125864), initialsize_125885));
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawget_126043)(table125861 t_126050, NimStringDesc* key_126053) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100842(key_126053);
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_126050.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_126050.Data->Sup.len)) raiseIndexError();
			if (!!((t_126050.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_126050.Data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t_126050.Data->data[h].Field1, key_126053);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_126050.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_126050.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_113410(h, (t_126050.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell44933* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_126170)(table125861* t_126179, keyvaluepairseq125864** data_126187, NimStringDesc* key_126191, NimStringDesc* val_126193) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100842(key_126191);
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_126187)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_126187)->Sup.len)) raiseIndexError();
			if (!((*data_126187)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_113410(h, ((*data_126187)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126187)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_126187)->data[h].Field1; (*data_126187)->data[h].Field1 = copyStringRC1(key_126191);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126187)->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = (*data_126187)->data[h].Field2; (*data_126187)->data[h].Field2 = copyStringRC1(val_126193);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126187)->Sup.len)) raiseIndexError();
	(*data_126187)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_126100)(table125861* t_126109) {
	keyvaluepairseq125864* n;
	NI TMP310;
	keyvaluepairseq125864* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP310 = mulInt((*t_126109).Data->Sup.len, 2);
	n = (keyvaluepairseq125864*) newSeq((&NTI125864), (NI32)(TMP310));
	{
		NI i_126155;
		NI HEX3Atmp_126234;
		NI res_126237;
		i_126155 = 0;
		HEX3Atmp_126234 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_126234 = ((*t_126109).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_126237 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_126237 <= HEX3Atmp_126234)) goto LA3;
				nimln(1569, "system.nim");
				i_126155 = res_126237;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_126155) >= (NU)((*t_126109).Data->Sup.len)) raiseIndexError();
					if (!((*t_126109).Data->data[i_126155].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_126155) >= (NU)((*t_126109).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_126155) >= (NU)((*t_126109).Data->Sup.len)) raiseIndexError();
					rawinsert_126170(t_126109, (&n), (*t_126109).Data->data[i_126155].Field1, (*t_126109).Data->data[i_126155].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_126237 = addInt(res_126237, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_126109).Data;
	unsureAsgnRef((void**) (&(*t_126109).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_126025)(table125861* t_126034, NimStringDesc* key_126038, NimStringDesc* val_126040) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_126043((*t_126034), key_126038);
	nimln(190, "tables.nim");
	{
		NimStringDesc* LOC5;
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_126034).Data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t_126034).Data->data[index].Field2; (*t_126034).Data->data[index].Field2 = copyStringRC1(val_126040);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC9;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC9 = 0;
			LOC9 = mustrehash_113302((*t_126034).Data->Sup.len, (*t_126034).Counter);
			if (!LOC9) goto LA10;
			nimln(184, "tables.nim");
			enlarge_126100(t_126034);
		}
		LA10: ;
		nimln(185, "tables.nim");
		rawinsert_126170(t_126034, (&(*t_126034).Data), key_126038, val_126040);
		nimln(186, "tables.nim");
		(*t_126034).Counter = addInt((*t_126034).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, totable_126314)(TY107550* pairs_126327, NI pairs_126327Len0, table125861* Result) {
	NI TMP311;
	NI LOC1;
	nimfr("toTable", "tables.nim")
	nimln(236, "tables.nim");
	nimln(236, "tables.nim");
	nimln(236, "tables.nim");
	nimln(236, "tables.nim");
	TMP311 = addInt(pairs_126327Len0, 10);
	LOC1 = 0;
	LOC1 = nextpoweroftwo_110328((NI32)(TMP311));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI125861));
	inittable_125880(LOC1, Result);
	{
		NimStringDesc* key_126391;
		NimStringDesc* val_126392;
		NI i_126416;
		key_126391 = 0;
		val_126392 = 0;
		nimln(1649, "system.nim");
		i_126416 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_126416 < pairs_126327Len0)) goto LA4;
				nimln(1651, "system.nim");
				if ((NU)(i_126416) >= (NU)(pairs_126327Len0)) raiseIndexError();
				key_126391 = pairs_126327[i_126416].Field0;
				nimln(1651, "system.nim");
				if ((NU)(i_126416) >= (NU)(pairs_126327Len0)) raiseIndexError();
				val_126392 = pairs_126327[i_126416].Field1;
				nimln(237, "tables.nim");
				HEX5BHEX5DHEX3D_126025(Result, key_126391, val_126392);
				nimln(1652, "system.nim");
				i_126416 = addInt(i_126416, 1);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX5BHEX5D_126432)(table125861 t_126439, NimStringDesc* key_126442) {
	NimStringDesc* result;
	NI index;
	nimfr("[]", "tables.nim")
	result = 0;
	nimln(150, "tables.nim");
	index = rawget_126043(t_126439, key_126442);
	nimln(151, "tables.nim");
	{
		nimln(151, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(151, "tables.nim");
		if ((NU)(index) >= (NU)(t_126439.Data->Sup.len)) raiseIndexError();
		result = copyString(t_126439.Data->data[index].Field2);
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_100401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(95, "hashes.nim");
	nimln(95, "hashes.nim");
	result = (NI)((NU32)(((NI) (x))) >> (NU32)(3));
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_126498)(table122152 t_126505, NCSTRING key_126508) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "tables.nim")
	result = 0;
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	nimln(127, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100401(((void*) (key_126508)));
	nimln(127, "tables.nim");
	h = (NI)(LOC1 & (t_126505.Data->Sup.len-1));
	{
		nimln(128, "tables.nim");
		while (1) {
			nimln(128, "tables.nim");
			nimln(128, "tables.nim");
			if ((NU)(h) >= (NU)(t_126505.Data->Sup.len)) raiseIndexError();
			if (!!((t_126505.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			nimln(129, "tables.nim");
			{
				NIM_BOOL LOC6;
				nimln(129, "tables.nim");
				LOC6 = 0;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_126505.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_126505.Data->data[h].Field1 == key_126508);
				if (!(LOC6)) goto LA7;
				nimln(129, "tables.nim");
				if ((NU)(h) >= (NU)(t_126505.Data->Sup.len)) raiseIndexError();
				LOC6 = (t_126505.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(130, "tables.nim");
				nimln(130, "tables.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(131, "tables.nim");
			nimln(131, "tables.nim");
			h = nexttry_113410(h, (t_126505.Data->Sup.len-1));
		} LA3: ;
	}
	nimln(132, "tables.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_126625)(table122152* t_126634, keyvaluepairseq122155** data_126642, NCSTRING key_126646, NimStringDesc* val_126648) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	nimfr("rawInsert", "tables.nim")
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	nimln(135, "tables.nim");
	LOC1 = 0;
	LOC1 = hash_100401(((void*) (key_126646)));
	nimln(135, "tables.nim");
	h = (NI)(LOC1 & ((*data_126642)->Sup.len-1));
	{
		nimln(136, "tables.nim");
		while (1) {
			nimln(136, "tables.nim");
			if ((NU)(h) >= (NU)((*data_126642)->Sup.len)) raiseIndexError();
			if (!((*data_126642)->data[h].Field0 == ((NU8) 1))) goto LA3;
			nimln(137, "tables.nim");
			nimln(137, "tables.nim");
			h = nexttry_113410(h, ((*data_126642)->Sup.len-1));
		} LA3: ;
	}
	nimln(138, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126642)->Sup.len)) raiseIndexError();
	(*data_126642)->data[h].Field1 = key_126646;
	nimln(139, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126642)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data_126642)->data[h].Field2; (*data_126642)->data[h].Field2 = copyStringRC1(val_126648);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(140, "tables.nim");
	if ((NU)(h) >= (NU)((*data_126642)->Sup.len)) raiseIndexError();
	(*data_126642)->data[h].Field0 = ((NU8) 1);
	popFrame();
}

N_NIMCALL(void, enlarge_126555)(table122152* t_126564) {
	keyvaluepairseq122155* n;
	NI TMP313;
	keyvaluepairseq122155* LOC8;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	nimln(178, "tables.nim");
	TMP313 = mulInt((*t_126564).Data->Sup.len, 2);
	n = (keyvaluepairseq122155*) newSeq((&NTI122155), (NI32)(TMP313));
	{
		NI i_126610;
		NI HEX3Atmp_126689;
		NI res_126692;
		i_126610 = 0;
		HEX3Atmp_126689 = 0;
		nimln(179, "tables.nim");
		nimln(179, "tables.nim");
		HEX3Atmp_126689 = ((*t_126564).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_126692 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_126692 <= HEX3Atmp_126689)) goto LA3;
				nimln(1569, "system.nim");
				i_126610 = res_126692;
				nimln(180, "tables.nim");
				{
					nimln(180, "tables.nim");
					if ((NU)(i_126610) >= (NU)((*t_126564).Data->Sup.len)) raiseIndexError();
					if (!((*t_126564).Data->data[i_126610].Field0 == ((NU8) 1))) goto LA6;
					nimln(180, "tables.nim");
					if ((NU)(i_126610) >= (NU)((*t_126564).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_126610) >= (NU)((*t_126564).Data->Sup.len)) raiseIndexError();
					rawinsert_126625(t_126564, (&n), (*t_126564).Data->data[i_126610].Field1, (*t_126564).Data->data[i_126610].Field2);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_126692 = addInt(res_126692, 1);
			} LA3: ;
		}
	}
	nimln(181, "tables.nim");
	LOC8 = 0;
	LOC8 = (*t_126564).Data;
	unsureAsgnRef((void**) (&(*t_126564).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_126480)(table122152* t_126489, NCSTRING key_126493, NimStringDesc* val_126495) {
	NI index;
	nimfr("[]=", "tables.nim")
	nimln(189, "tables.nim");
	index = rawget_126498((*t_126489), key_126493);
	nimln(190, "tables.nim");
	{
		NimStringDesc* LOC5;
		nimln(190, "tables.nim");
		if (!(0 <= index)) goto LA3;
		nimln(191, "tables.nim");
		if ((NU)(index) >= (NU)((*t_126489).Data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t_126489).Data->data[index].Field2; (*t_126489).Data->data[index].Field2 = copyStringRC1(val_126495);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		nimln(184, "tables.nim");
		{
			NIM_BOOL LOC9;
			nimln(184, "tables.nim");
			nimln(184, "tables.nim");
			LOC9 = 0;
			LOC9 = mustrehash_113302((*t_126489).Data->Sup.len, (*t_126489).Counter);
			if (!LOC9) goto LA10;
			nimln(184, "tables.nim");
			enlarge_126555(t_126489);
		}
		LA10: ;
		nimln(185, "tables.nim");
		rawinsert_126625(t_126489, (&(*t_126489).Data), key_126493, val_126495);
		nimln(186, "tables.nim");
		(*t_126489).Counter = addInt((*t_126489).Counter, 1);
	}
	LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP268[3];
static TNimNode* TMP269[3];
NI TMP271;
static char* NIM_CONST TMP270[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode* TMP273[2];
static TNimNode* TMP274[3];
static TNimNode* TMP276[2];
static TNimNode* TMP277[3];
static TNimNode* TMP279[2];
static TNimNode* TMP280[3];
static TNimNode* TMP282[2];
static TNimNode* TMP283[3];
static TNimNode* TMP285[2];
static TNimNode* TMP286[3];
static TNimNode* TMP288[2];
static TNimNode* TMP289[3];
static TNimNode* TMP291[2];
static TNimNode* TMP308[3];
static TNimNode* TMP312[2];
static TNimNode TMP133[60];
NTI122136.size = sizeof(keyvaluepair122136);
NTI122136.kind = 18;
NTI122136.base = 0;
NTI122136.flags = 3;
TMP268[0] = &TMP133[1];
NTI113009.size = sizeof(NU8);
NTI113009.kind = 14;
NTI113009.base = 0;
NTI113009.flags = 3;
for (TMP271 = 0; TMP271 < 3; TMP271++) {
TMP133[TMP271+2].kind = 1;
TMP133[TMP271+2].offset = TMP271;
TMP133[TMP271+2].name = TMP270[TMP271];
TMP269[TMP271] = &TMP133[TMP271+2];
}
TMP133[5].len = 3; TMP133[5].kind = 2; TMP133[5].sons = &TMP269[0];
NTI113009.node = &TMP133[5];
TMP133[1].kind = 1;
TMP133[1].offset = offsetof(keyvaluepair122136, Field0);
TMP133[1].typ = (&NTI113009);
TMP133[1].name = "Field0";
TMP268[1] = &TMP133[6];
TMP133[6].kind = 1;
TMP133[6].offset = offsetof(keyvaluepair122136, Field1);
TMP133[6].typ = (&NTI151);
TMP133[6].name = "Field1";
TMP268[2] = &TMP133[7];
TMP133[7].kind = 1;
TMP133[7].offset = offsetof(keyvaluepair122136, Field2);
TMP133[7].typ = (&NTI151);
TMP133[7].name = "Field2";
TMP133[0].len = 3; TMP133[0].kind = 2; TMP133[0].sons = &TMP268[0];
NTI122136.node = &TMP133[0];
NTI122133.size = sizeof(keyvaluepairseq122133*);
NTI122133.kind = 24;
NTI122133.base = (&NTI122136);
NTI122133.flags = 2;
NTI122133.marker = TMP272;
NTI122130.size = sizeof(table122130);
NTI122130.kind = 18;
NTI122130.base = 0;
NTI122130.flags = 2;
TMP273[0] = &TMP133[9];
TMP133[9].kind = 1;
TMP133[9].offset = offsetof(table122130, Data);
TMP133[9].typ = (&NTI122133);
TMP133[9].name = "data";
TMP273[1] = &TMP133[10];
TMP133[10].kind = 1;
TMP133[10].offset = offsetof(table122130, Counter);
TMP133[10].typ = (&NTI108);
TMP133[10].name = "counter";
TMP133[8].len = 2; TMP133[8].kind = 2; TMP133[8].sons = &TMP273[0];
NTI122130.node = &TMP133[8];
NTI122158.size = sizeof(keyvaluepair122158);
NTI122158.kind = 18;
NTI122158.base = 0;
NTI122158.flags = 2;
TMP274[0] = &TMP133[12];
TMP133[12].kind = 1;
TMP133[12].offset = offsetof(keyvaluepair122158, Field0);
TMP133[12].typ = (&NTI113009);
TMP133[12].name = "Field0";
TMP274[1] = &TMP133[13];
TMP133[13].kind = 1;
TMP133[13].offset = offsetof(keyvaluepair122158, Field1);
TMP133[13].typ = (&NTI151);
TMP133[13].name = "Field1";
TMP274[2] = &TMP133[14];
TMP133[14].kind = 1;
TMP133[14].offset = offsetof(keyvaluepair122158, Field2);
TMP133[14].typ = (&NTI149);
TMP133[14].name = "Field2";
TMP133[11].len = 3; TMP133[11].kind = 2; TMP133[11].sons = &TMP274[0];
NTI122158.node = &TMP133[11];
NTI122155.size = sizeof(keyvaluepairseq122155*);
NTI122155.kind = 24;
NTI122155.base = (&NTI122158);
NTI122155.flags = 2;
NTI122155.marker = TMP275;
NTI122152.size = sizeof(table122152);
NTI122152.kind = 18;
NTI122152.base = 0;
NTI122152.flags = 2;
TMP276[0] = &TMP133[16];
TMP133[16].kind = 1;
TMP133[16].offset = offsetof(table122152, Data);
TMP133[16].typ = (&NTI122155);
TMP133[16].name = "data";
TMP276[1] = &TMP133[17];
TMP133[17].kind = 1;
TMP133[17].offset = offsetof(table122152, Counter);
TMP133[17].typ = (&NTI108);
TMP133[17].name = "counter";
TMP133[15].len = 2; TMP133[15].kind = 2; TMP133[15].sons = &TMP276[0];
NTI122152.node = &TMP133[15];
NTI122092.size = sizeof(keyvaluepair122092);
NTI122092.kind = 18;
NTI122092.base = 0;
NTI122092.flags = 3;
TMP277[0] = &TMP133[19];
TMP133[19].kind = 1;
TMP133[19].offset = offsetof(keyvaluepair122092, Field0);
TMP133[19].typ = (&NTI113009);
TMP133[19].name = "Field0";
TMP277[1] = &TMP133[20];
TMP133[20].kind = 1;
TMP133[20].offset = offsetof(keyvaluepair122092, Field1);
TMP133[20].typ = (&NTI151);
TMP133[20].name = "Field1";
TMP277[2] = &TMP133[21];
TMP133[21].kind = 1;
TMP133[21].offset = offsetof(keyvaluepair122092, Field2);
TMP133[21].typ = (&NTI108);
TMP133[21].name = "Field2";
TMP133[18].len = 3; TMP133[18].kind = 2; TMP133[18].sons = &TMP277[0];
NTI122092.node = &TMP133[18];
NTI122089.size = sizeof(keyvaluepairseq122089*);
NTI122089.kind = 24;
NTI122089.base = (&NTI122092);
NTI122089.flags = 2;
NTI122089.marker = TMP278;
NTI122086.size = sizeof(table122086);
NTI122086.kind = 18;
NTI122086.base = 0;
NTI122086.flags = 2;
TMP279[0] = &TMP133[23];
TMP133[23].kind = 1;
TMP133[23].offset = offsetof(table122086, Data);
TMP133[23].typ = (&NTI122089);
TMP133[23].name = "data";
TMP279[1] = &TMP133[24];
TMP133[24].kind = 1;
TMP133[24].offset = offsetof(table122086, Counter);
TMP133[24].typ = (&NTI108);
TMP133[24].name = "counter";
TMP133[22].len = 2; TMP133[22].kind = 2; TMP133[22].sons = &TMP279[0];
NTI122086.node = &TMP133[22];
NTI122114.size = sizeof(keyvaluepair122114);
NTI122114.kind = 18;
NTI122114.base = 0;
NTI122114.flags = 3;
TMP280[0] = &TMP133[26];
TMP133[26].kind = 1;
TMP133[26].offset = offsetof(keyvaluepair122114, Field0);
TMP133[26].typ = (&NTI113009);
TMP133[26].name = "Field0";
TMP280[1] = &TMP133[27];
TMP133[27].kind = 1;
TMP133[27].offset = offsetof(keyvaluepair122114, Field1);
TMP133[27].typ = (&NTI151);
TMP133[27].name = "Field1";
TMP280[2] = &TMP133[28];
TMP133[28].kind = 1;
TMP133[28].offset = offsetof(keyvaluepair122114, Field2);
TMP133[28].typ = (&NTI128);
TMP133[28].name = "Field2";
TMP133[25].len = 3; TMP133[25].kind = 2; TMP133[25].sons = &TMP280[0];
NTI122114.node = &TMP133[25];
NTI122111.size = sizeof(keyvaluepairseq122111*);
NTI122111.kind = 24;
NTI122111.base = (&NTI122114);
NTI122111.flags = 2;
NTI122111.marker = TMP281;
NTI122108.size = sizeof(table122108);
NTI122108.kind = 18;
NTI122108.base = 0;
NTI122108.flags = 2;
TMP282[0] = &TMP133[30];
TMP133[30].kind = 1;
TMP133[30].offset = offsetof(table122108, Data);
TMP133[30].typ = (&NTI122111);
TMP133[30].name = "data";
TMP282[1] = &TMP133[31];
TMP133[31].kind = 1;
TMP133[31].offset = offsetof(table122108, Counter);
TMP133[31].typ = (&NTI108);
TMP133[31].name = "counter";
TMP133[29].len = 2; TMP133[29].kind = 2; TMP133[29].sons = &TMP282[0];
NTI122108.node = &TMP133[29];
NTI122224.size = sizeof(keyvaluepair122224);
NTI122224.kind = 18;
NTI122224.base = 0;
NTI122224.flags = 2;
TMP283[0] = &TMP133[33];
TMP133[33].kind = 1;
TMP133[33].offset = offsetof(keyvaluepair122224, Field0);
TMP133[33].typ = (&NTI113009);
TMP133[33].name = "Field0";
TMP283[1] = &TMP133[34];
TMP133[34].kind = 1;
TMP133[34].offset = offsetof(keyvaluepair122224, Field1);
TMP133[34].typ = (&NTI151);
TMP133[34].name = "Field1";
TMP283[2] = &TMP133[35];
TMP133[35].kind = 1;
TMP133[35].offset = offsetof(keyvaluepair122224, Field2);
TMP133[35].typ = (&NTI122641);
TMP133[35].name = "Field2";
TMP133[32].len = 3; TMP133[32].kind = 2; TMP133[32].sons = &TMP283[0];
NTI122224.node = &TMP133[32];
NTI122221.size = sizeof(keyvaluepairseq122221*);
NTI122221.kind = 24;
NTI122221.base = (&NTI122224);
NTI122221.flags = 2;
NTI122221.marker = TMP284;
NTI122218.size = sizeof(table122218);
NTI122218.kind = 18;
NTI122218.base = 0;
NTI122218.flags = 2;
TMP285[0] = &TMP133[37];
TMP133[37].kind = 1;
TMP133[37].offset = offsetof(table122218, Data);
TMP133[37].typ = (&NTI122221);
TMP133[37].name = "data";
TMP285[1] = &TMP133[38];
TMP133[38].kind = 1;
TMP133[38].offset = offsetof(table122218, Counter);
TMP133[38].typ = (&NTI108);
TMP133[38].name = "counter";
TMP133[36].len = 2; TMP133[36].kind = 2; TMP133[36].sons = &TMP285[0];
NTI122218.node = &TMP133[36];
NTI122180.size = sizeof(keyvaluepair122180);
NTI122180.kind = 18;
NTI122180.base = 0;
NTI122180.flags = 2;
TMP286[0] = &TMP133[40];
TMP133[40].kind = 1;
TMP133[40].offset = offsetof(keyvaluepair122180, Field0);
TMP133[40].typ = (&NTI113009);
TMP133[40].name = "Field0";
TMP286[1] = &TMP133[41];
TMP133[41].kind = 1;
TMP133[41].offset = offsetof(keyvaluepair122180, Field1);
TMP133[41].typ = (&NTI151);
TMP133[41].name = "Field1";
TMP286[2] = &TMP133[42];
TMP133[42].kind = 1;
TMP133[42].offset = offsetof(keyvaluepair122180, Field2);
TMP133[42].typ = (&NTI122470);
TMP133[42].name = "Field2";
TMP133[39].len = 3; TMP133[39].kind = 2; TMP133[39].sons = &TMP286[0];
NTI122180.node = &TMP133[39];
NTI122177.size = sizeof(keyvaluepairseq122177*);
NTI122177.kind = 24;
NTI122177.base = (&NTI122180);
NTI122177.flags = 2;
NTI122177.marker = TMP287;
NTI122174.size = sizeof(table122174);
NTI122174.kind = 18;
NTI122174.base = 0;
NTI122174.flags = 2;
TMP288[0] = &TMP133[44];
TMP133[44].kind = 1;
TMP133[44].offset = offsetof(table122174, Data);
TMP133[44].typ = (&NTI122177);
TMP133[44].name = "data";
TMP288[1] = &TMP133[45];
TMP133[45].kind = 1;
TMP133[45].offset = offsetof(table122174, Counter);
TMP133[45].typ = (&NTI108);
TMP133[45].name = "counter";
TMP133[43].len = 2; TMP133[43].kind = 2; TMP133[43].sons = &TMP288[0];
NTI122174.node = &TMP133[43];
NTI122202.size = sizeof(keyvaluepair122202);
NTI122202.kind = 18;
NTI122202.base = 0;
NTI122202.flags = 2;
TMP289[0] = &TMP133[47];
TMP133[47].kind = 1;
TMP133[47].offset = offsetof(keyvaluepair122202, Field0);
TMP133[47].typ = (&NTI113009);
TMP133[47].name = "Field0";
TMP289[1] = &TMP133[48];
TMP133[48].kind = 1;
TMP133[48].offset = offsetof(keyvaluepair122202, Field1);
TMP133[48].typ = (&NTI151);
TMP133[48].name = "Field1";
TMP289[2] = &TMP133[49];
TMP133[49].kind = 1;
TMP133[49].offset = offsetof(keyvaluepair122202, Field2);
TMP133[49].typ = (&NTI122527);
TMP133[49].name = "Field2";
TMP133[46].len = 3; TMP133[46].kind = 2; TMP133[46].sons = &TMP289[0];
NTI122202.node = &TMP133[46];
NTI122199.size = sizeof(keyvaluepairseq122199*);
NTI122199.kind = 24;
NTI122199.base = (&NTI122202);
NTI122199.flags = 2;
NTI122199.marker = TMP290;
NTI122196.size = sizeof(table122196);
NTI122196.kind = 18;
NTI122196.base = 0;
NTI122196.flags = 2;
TMP291[0] = &TMP133[51];
TMP133[51].kind = 1;
TMP133[51].offset = offsetof(table122196, Data);
TMP133[51].typ = (&NTI122199);
TMP133[51].name = "data";
TMP291[1] = &TMP133[52];
TMP133[52].kind = 1;
TMP133[52].offset = offsetof(table122196, Counter);
TMP133[52].typ = (&NTI108);
TMP133[52].name = "counter";
TMP133[50].len = 2; TMP133[50].kind = 2; TMP133[50].sons = &TMP291[0];
NTI122196.node = &TMP133[50];
NTI125867.size = sizeof(keyvaluepair125867);
NTI125867.kind = 18;
NTI125867.base = 0;
NTI125867.flags = 2;
TMP308[0] = &TMP133[54];
TMP133[54].kind = 1;
TMP133[54].offset = offsetof(keyvaluepair125867, Field0);
TMP133[54].typ = (&NTI113009);
TMP133[54].name = "Field0";
TMP308[1] = &TMP133[55];
TMP133[55].kind = 1;
TMP133[55].offset = offsetof(keyvaluepair125867, Field1);
TMP133[55].typ = (&NTI149);
TMP133[55].name = "Field1";
TMP308[2] = &TMP133[56];
TMP133[56].kind = 1;
TMP133[56].offset = offsetof(keyvaluepair125867, Field2);
TMP133[56].typ = (&NTI149);
TMP133[56].name = "Field2";
TMP133[53].len = 3; TMP133[53].kind = 2; TMP133[53].sons = &TMP308[0];
NTI125867.node = &TMP133[53];
NTI125864.size = sizeof(keyvaluepairseq125864*);
NTI125864.kind = 24;
NTI125864.base = (&NTI125867);
NTI125864.flags = 2;
NTI125864.marker = TMP309;
NTI125861.size = sizeof(table125861);
NTI125861.kind = 18;
NTI125861.base = 0;
NTI125861.flags = 2;
TMP312[0] = &TMP133[58];
TMP133[58].kind = 1;
TMP133[58].offset = offsetof(table125861, Data);
TMP133[58].typ = (&NTI125864);
TMP133[58].name = "data";
TMP312[1] = &TMP133[59];
TMP133[59].kind = 1;
TMP133[59].offset = offsetof(table125861, Counter);
TMP133[59].typ = (&NTI108);
TMP133[59].name = "counter";
TMP133[57].len = 2; TMP133[57].kind = 2; TMP133[57].sons = &TMP312[0];
NTI125861.node = &TMP133[57];
}

