/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   F:\Nim\dist\mingw\bin\gcc.exe -c  -w  -IF:\Nim\lib -o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_times.o f:\mydocument\[programing]\python\pynimcffi\nimcache\stdlib_times.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <time.h>

#include <string.h>
typedef struct timeinterval107407 timeinterval107407;
typedef struct timeinfo107405 timeinfo107405;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY107550 TY107550;
typedef struct tfiletime104276 tfiletime104276;
typedef struct slice86066 slice86066;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell44933 tcell44933;
typedef struct tcellseq44949 tcellseq44949;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset44945 tcellset44945;
typedef struct tpagedesc44941 tpagedesc44941;
typedef struct tmemregion27210 tmemregion27210;
typedef struct tsmallchunk26440 tsmallchunk26440;
typedef struct tllchunk27204 tllchunk27204;
typedef struct tbigchunk26442 tbigchunk26442;
typedef struct tintset26417 tintset26417;
typedef struct ttrunk26413 ttrunk26413;
typedef struct tavlnode27208 tavlnode27208;
typedef struct tgcstat47014 tgcstat47014;
typedef struct tbasechunk26438 tbasechunk26438;
typedef struct tfreecell26430 tfreecell26430;
struct  timeinterval107407  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  timeinfo107405  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY108054[7];
struct TY107550 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY108075[7];
struct  tfiletime104276  {
NI32 Dwlowdatetime;
NI32 Dwhighdatetime;
};
typedef N_STDCALL_PTR(void, TY105625) (tfiletime104276* lpsystemtimeasfiletime);
typedef NimStringDesc* TY109239[7];
typedef NimStringDesc* TY109255[12];
struct  slice86066  {
NI A;
NI B;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell44933  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq44949  {
NI Len;
NI Cap;
tcell44933** D;
};
struct  tcellset44945  {
NI Counter;
NI Max;
tpagedesc44941* Head;
tpagedesc44941** Data;
};
typedef tsmallchunk26440* TY27222[512];
typedef ttrunk26413* ttrunkbuckets26415[256];
struct  tintset26417  {
ttrunkbuckets26415 Data;
};
struct  tmemregion27210  {
NI Minlargeobj;
NI Maxlargeobj;
TY27222 Freesmallchunks;
tllchunk27204* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26442* Freechunkslist;
tintset26417 Chunkstarts;
tavlnode27208* Root;
tavlnode27208* Deleted;
tavlnode27208* Last;
tavlnode27208* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44949 Zct;
tcellseq44949 Decstack;
tcellset44945 Cycleroots;
tcellseq44949 Tempstack;
NI Recgclock;
tmemregion27210 Region;
tgcstat47014 Stat;
};
typedef NI TY26420[16];
struct  tpagedesc44941  {
tpagedesc44941* Next;
NI Key;
TY26420 Bits;
};
struct  tbasechunk26438  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26440  {
  tbasechunk26438 Sup;
tsmallchunk26440* Next;
tsmallchunk26440* Prev;
tfreecell26430* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27204  {
NI Size;
NI Acc;
tllchunk27204* Next;
};
struct  tbigchunk26442  {
  tbasechunk26438 Sup;
tbigchunk26442* Next;
tbigchunk26442* Prev;
NI Align;
NF Data;
};
struct  ttrunk26413  {
ttrunk26413* Next;
NI Key;
TY26420 Bits;
};
typedef tavlnode27208* TY27214[2];
struct  tavlnode27208  {
TY27214 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26430  {
tfreecell26430* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_107477)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(timeinterval107407, initinterval_107614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_107630)(NI year);
N_NIMCALL(NI, getdaysinmonth_107645)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_107693)(NF* x_107699, NF y_107702);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_107658)(timeinfo107405* a, timeinterval107407* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_86004)(NI x, NI y);
N_NIMCALL(void, HEX2B_107833)(timeinfo107405* a, timeinterval107407* interval, timeinfo107405* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_107846)(timeinfo107405* a, timeinterval107407* interval, timeinfo107405* Result);
N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, timeinfo107405* Result);
N_NIMCALL(void, gettzname_107548)(TY107550* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_107604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_108070)(timeinfo107405* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_107609)(void);
N_NIMCALL(time_t, gettime_107448)(void);
N_NIMCALL(void, getlocaltime_107453)(time_t t, timeinfo107405* Result);
N_NIMCALL(void, getgmtime_107459)(time_t t, timeinfo107405* Result);
N_NIMCALL(time_t, timeinfototime_107465)(timeinfo107405* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_108637)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_107494)(timeinfo107405* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_107500)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_108683)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_108691)(NI64 t);
N_NIMCALL(time_t, fromseconds_107471)(NF since1970);
N_NIMCALL(NF, toseconds_107488)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI64, rdfiletime_105604)(tfiletime104276 f);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_109234)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_109250)(NU8 m);
N_NIMCALL(void, formattoken_109266)(timeinfo107405* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_86059)(NimStringDesc* s, slice86066 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74828, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(slice86066, HEX2EHEX2E_92098)(NI a_92102, NI b_92104);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_87801)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell44933*, usrtocell_48646)(void* usr);
static N_INLINE(void, rtladdzct_50204)(tcell44933* c);
N_NOINLINE(void, addzct_48617)(tcellseq44949* s, tcell44933* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_109421)(timeinfo107405* info, NimStringDesc* f);
STRING_LITERAL(TMP170, "UTC", 3);
NIM_CONST TY108054 weekdays_108053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY108075 weekdays_108074 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP171, "", 0);
STRING_LITERAL(TMP173, "Monday", 6);
STRING_LITERAL(TMP174, "Tuesday", 7);
STRING_LITERAL(TMP175, "Wednesday", 9);
STRING_LITERAL(TMP176, "Thursday", 8);
STRING_LITERAL(TMP177, "Friday", 6);
STRING_LITERAL(TMP178, "Saturday", 8);
STRING_LITERAL(TMP179, "Sunday", 6);
NIM_CONST TY109239 lookup_109238 = {((NimStringDesc*) &TMP173),
((NimStringDesc*) &TMP174),
((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176),
((NimStringDesc*) &TMP177),
((NimStringDesc*) &TMP178),
((NimStringDesc*) &TMP179)}
;
STRING_LITERAL(TMP180, "January", 7);
STRING_LITERAL(TMP181, "February", 8);
STRING_LITERAL(TMP182, "March", 5);
STRING_LITERAL(TMP183, "April", 5);
STRING_LITERAL(TMP184, "May", 3);
STRING_LITERAL(TMP185, "June", 4);
STRING_LITERAL(TMP186, "July", 4);
STRING_LITERAL(TMP187, "August", 6);
STRING_LITERAL(TMP188, "September", 9);
STRING_LITERAL(TMP189, "October", 7);
STRING_LITERAL(TMP190, "November", 8);
STRING_LITERAL(TMP191, "December", 8);
NIM_CONST TY109255 lookup_109254 = {((NimStringDesc*) &TMP180),
((NimStringDesc*) &TMP181),
((NimStringDesc*) &TMP182),
((NimStringDesc*) &TMP183),
((NimStringDesc*) &TMP184),
((NimStringDesc*) &TMP185),
((NimStringDesc*) &TMP186),
((NimStringDesc*) &TMP187),
((NimStringDesc*) &TMP188),
((NimStringDesc*) &TMP189),
((NimStringDesc*) &TMP190),
((NimStringDesc*) &TMP191)}
;
STRING_LITERAL(TMP192, "d", 1);
STRING_LITERAL(TMP193, "dd", 2);
STRING_LITERAL(TMP194, "ddd", 3);
STRING_LITERAL(TMP195, "dddd", 4);
STRING_LITERAL(TMP196, "h", 1);
STRING_LITERAL(TMP197, "hh", 2);
STRING_LITERAL(TMP198, "H", 1);
STRING_LITERAL(TMP199, "HH", 2);
STRING_LITERAL(TMP200, "m", 1);
STRING_LITERAL(TMP201, "mm", 2);
STRING_LITERAL(TMP202, "M", 1);
STRING_LITERAL(TMP203, "MM", 2);
STRING_LITERAL(TMP204, "MMM", 3);
STRING_LITERAL(TMP205, "MMMM", 4);
STRING_LITERAL(TMP206, "s", 1);
STRING_LITERAL(TMP207, "ss", 2);
STRING_LITERAL(TMP208, "t", 1);
STRING_LITERAL(TMP209, "tt", 2);
STRING_LITERAL(TMP210, "y", 1);
STRING_LITERAL(TMP211, "yy", 2);
STRING_LITERAL(TMP212, "yyy", 3);
STRING_LITERAL(TMP213, "yyyy", 4);
STRING_LITERAL(TMP214, "yyyyy", 5);
STRING_LITERAL(TMP215, "z", 1);
STRING_LITERAL(TMP216, "zz", 2);
STRING_LITERAL(TMP217, "zzz", 3);
STRING_LITERAL(TMP218, "ZZZ", 3);
STRING_LITERAL(TMP219, "0", 1);
STRING_LITERAL(TMP222, "PM", 2);
STRING_LITERAL(TMP223, "AM", 2);
STRING_LITERAL(TMP225, ":00", 3);
STRING_LITERAL(TMP226, "Invalid format string: ", 23);
extern TFrame* frameptr_16242;
extern TNimType NTI3211; /* RootObj */
TNimType NTI107405; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI107408; /* range 0..61(int) */
TNimType NTI107410; /* range 0..59(int) */
TNimType NTI107412; /* range 0..23(int) */
TNimType NTI107415; /* range 1..31(int) */
TNimType NTI104206; /* Month */
TNimType NTI107418; /* range -10000..10000(int) */
TNimType NTI104208; /* WeekDay */
TNimType NTI107424; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TY105625 Dl_105624;
extern TNimType NTI21601; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47016 gch_47044;
TNimType NTI107550; /* tuple[nonDST: string, DST: string] */

N_NIMCALL(time_t, fromseconds_107477)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_107471(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(timeinterval107407, initinterval_107614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	timeinterval107407 result;
	memset((void*)(&result), 0, sizeof(result));
	result.Miliseconds = miliseconds;
	result.Seconds = seconds;
	result.Minutes = minutes;
	result.Hours = hours;
	result.Days = days;
	result.Months = months;
	result.Years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_107630)(NI year) {
	NIM_BOOL result;
	result = 0;
	{
		if (!(((NI) ((NI32)(year % 400))) == 0)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI32)(year % 100))) == 0)) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI32)(year % 4))) == 0)) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_107645)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_107630(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = 30;
	}
	break;
	default:
	{
		result = 31;
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(void, HEX2BHEX3D_107693)(NF* x_107699, NF y_107702) {
	nimfr("+=", "system.nim")
	nimln(2893, "system.nim");
	nimln(2893, "system.nim");
	(*x_107699) = ((NF)((*x_107699)) + (NF)(y_107702));
	popFrame();
}

static N_INLINE(NF, HEX2F_86004)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	nimln(2749, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_107658)(timeinfo107405* a, timeinterval107407* interval) {
	NF result;
	timeinfo107405 anew;
	timeinterval107407 newinterv;
	NU8 curmonth;
	NF LOC10;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI107405);
	genericAssign((void*)(&anew), (void*)a, (&NTI107405));
	newinterv = (*interval);
	result = 0.0;
	newinterv.Months += (NI32)((*interval).Years * 12);
	curmonth = anew.Month;
	{
		NI mth_107688;
		NI HEX3Atmp_107809;
		NI res_107812;
		mth_107688 = 0;
		HEX3Atmp_107809 = 0;
		HEX3Atmp_107809 = newinterv.Months;
		res_107812 = 1;
		{
			while (1) {
				NI LOC4;
				if (!(res_107812 <= HEX3Atmp_107809)) goto LA3;
				mth_107688 = res_107812;
				LOC4 = 0;
				LOC4 = getdaysinmonth_107645(curmonth, ((NI) (anew.Year)));
				HEX2BHEX3D_107693((&result), ((NF) ((NI32)((NI32)((NI32)(LOC4 * 24) * 60) * 60))));
				{
					if (!(curmonth == ((NU8) 11))) goto LA7;
					curmonth = ((NU8) 0);
					anew.Year += 1;
				}
				goto LA5;
				LA7: ;
				{
					curmonth += 1;
				}
				LA5: ;
				res_107812 += 1;
			} LA3: ;
		}
	}
	HEX2BHEX3D_107693((&result), ((NF) ((NI32)((NI32)((NI32)(newinterv.Days * 24) * 60) * 60))));
	HEX2BHEX3D_107693((&result), ((NF) ((NI32)((NI32)(newinterv.Hours * 60) * 60))));
	HEX2BHEX3D_107693((&result), ((NF) ((NI32)(newinterv.Minutes * 60))));
	HEX2BHEX3D_107693((&result), ((NF) (newinterv.Seconds)));
	LOC10 = 0;
	LOC10 = HEX2F_86004(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_107693((&result), LOC10);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI32)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_107833)(timeinfo107405* a, timeinterval107407* interval, timeinfo107405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_107465(a);
	t = toseconds_107488(LOC1);
	secs = toseconds_107658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP170))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_107471(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getgmtime_107459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_107471(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getlocaltime_107453(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_107846)(timeinfo107405* a, timeinterval107407* interval, timeinfo107405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_107465(a);
	t = toseconds_107488(LOC1);
	secs = toseconds_107658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP170))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_107471(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getgmtime_107459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_107471(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getlocaltime_107453(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_107548)(TY107550* Result) {
	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(0)- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_107604)(void) {
	NI result;
	result = 0;
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, timeinfo107405* Result) {
	timeinfo107405 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107405);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107405);
	LOC1.Second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.Minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.Hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.Monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.Month = ((NU8) ((*tm).tm_mon));
	LOC1.Year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.Weekday = weekdays_108053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY107550 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_107548((&LOC10));
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY107550 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_107548((&LOC12));
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP170));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.Timezone = gettimezone_107604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI107405));
}

N_NIMCALL(struct tm, timeinfototm_108070)(timeinfo107405* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).Second));
	result.tm_min = ((int) ((*t).Minute));
	result.tm_hour = ((int) ((*t).Hour));
	result.tm_mday = ((int) ((*t).Monthday));
	result.tm_mon = ((int) ((*t).Month));
	result.tm_year = ((int) ((NI32)(((NI) ((*t).Year)) - 1900)));
	result.tm_wday = ((int) (weekdays_108074[((*t).Weekday)- 0]));
	result.tm_yday = ((int) ((*t).Yearday));
	LOC1 = 0;
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_107609)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI32)(LOC1 / (NI32)(CLOCKS_PER_SEC / 1000));
	return result;
}

N_NIMCALL(time_t, gettime_107448)(void) {
	time_t result;
	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_107453)(time_t t, timeinfo107405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime((&a));
	genericReset((void*)Result, (&NTI107405));
	(*Result).Sup.m_type = (&NTI107405);
	tmtotimeinfo_108048((&(*LOC1)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_107459)(time_t t, timeinfo107405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI107405));
	(*Result).Sup.m_type = (&NTI107405);
	tmtotimeinfo_108048((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_107465)(timeinfo107405* timeinfo) {
	time_t result;
	timeinfo107405 ctimeinfo;
	struct tm LOC1;
	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI107405);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI107405));
	LOC1 = timeinfototm_108070((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_108637)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP171));
	i = 0;
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += 1;
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107494)(timeinfo107405* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_108070(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_108637(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107500)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_108637(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_108683)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_108691)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_107471)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_107488)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	tfiletime104276 f;
	NI64 i64;
	NI64 LOC1;
	NI64 secs;
	NI64 subsecs;
	result = 0;
	memset((void*)(&f), 0, sizeof(f));
	Dl_105624((&f));
	LOC1 = 0;
	LOC1 = rdfiletime_105604(f);
	i64 = (NI64)(LOC1 - IL64(116444736000000000));
	secs = (NI64)(i64 / IL64(10000000));
	subsecs = (NI64)(i64 % IL64(10000000));
	result = ((NF)(((double) (((NI) (secs))))) + (NF)(((NF)(((double) (((NI) (subsecs))))) * (NF)(9.9999999999999995e-008))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI32)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	timeinfo107405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	LOC1 = 0;
	LOC1 = gettime_107448();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI32)(((NI) (ti.Month)) + 1))), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	timeinfo107405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	LOC1 = 0;
	LOC1 = gettime_107448();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_109234)(NU8 day) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_109238[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_109250)(NU8 m) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_109254[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_86059)(NimStringDesc* s, slice86066 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP220;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP220 = addInt(s->Sup.len, x.A);
		LOC1 = (NI32)(TMP220);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP221;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP221 = addInt(s->Sup.len, x.B);
		LOC7 = (NI32)(TMP221);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice86066, HEX2EHEX2E_92098)(NI a_92102, NI b_92104) {
	slice86066 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_92102;
	nimln(227, "system.nim");
	result.B = b_92104;
	popFrame();
	return result;
}

static N_INLINE(tcell44933*, usrtocell_48646)(void* usr) {
	tcell44933* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell44933*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44933))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell44933* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell44933* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_48646(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell44933* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_48646((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_109266)(timeinfo107405* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP171))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA10;
break;
	case 4: 
if (eqStrings(token, ((NimStringDesc*) &TMP214))) goto LA23;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP209))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP218))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP204))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP217))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA17;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP216))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP205))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP215))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP219));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		slice86066 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_109234((*info).Weekday);
		LOC41 = HEX2EHEX2E_92098(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_86059(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_109234((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			LOC46 = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			amerhour = ((NI) ((NI32)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		{
			if (!(amerhour < 10)) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI32)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		slice86066 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_109250((*info).Month);
		LOC90 = HEX2EHEX2E_92098(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_86059(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_109250((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP222));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP223));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		slice86066 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC115->Sup.len - 1);
		{
			if (!(fr < 0)) goto LA118;
			fr = 0;
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		LOC122 = HEX2EHEX2E_92098(fr, (NI32)(LOC121->Sup.len - 1));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_86059(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		slice86066 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC125->Sup.len - 2);
		{
			if (!(fr < 0)) goto LA128;
			fr = 0;
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		LOC132 = HEX2EHEX2E_92098(fr, (NI32)(LOC131->Sup.len - 1));
		fyear = HEX5BHEX5D_86059(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!((fyear->Sup.len == 2))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI32)(2 - fyear->Sup.len), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		slice86066 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC140->Sup.len - 3);
		{
			if (!(fr < 0)) goto LA143;
			fr = 0;
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		LOC147 = HEX2EHEX2E_92098(fr, (NI32)(LOC146->Sup.len - 1));
		fyear = HEX5BHEX5D_86059(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!((fyear->Sup.len == 3))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI32)(3 - fyear->Sup.len), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		slice86066 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC155->Sup.len - 4);
		{
			if (!(fr < 0)) goto LA158;
			fr = 0;
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		LOC162 = HEX2EHEX2E_92098(fr, (NI32)(LOC161->Sup.len - 1));
		fyear = HEX5BHEX5D_86059(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!((fyear->Sup.len == 4))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI32)(4 - fyear->Sup.len), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		slice86066 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI32)(LOC170->Sup.len - 5);
		{
			if (!(fr < 0)) goto LA173;
			fr = 0;
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		LOC177 = HEX2EHEX2E_92098(fr, (NI32)(LOC176->Sup.len - 1));
		fyear = HEX5BHEX5D_86059(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!((fyear->Sup.len == 5))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI32)(5 - fyear->Sup.len), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC192->Sup.len - LOC193));
			insert_87801(buf, ((NimStringDesc*) &TMP219), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI32)((NI32)((*info).Timezone / 60) / 60);
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP225));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < 10)) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP225));
			LOC208 = 0;
			{
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			atindex = (NI32)((*buf)->Sup.len - (NI32)(LOC206->Sup.len - LOC208));
			insert_87801(buf, ((NimStringDesc*) &TMP219), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		valueerror3249* e_109394;
		NimStringDesc* LOC217;
		e_109394 = 0;
		e_109394 = (valueerror3249*) newObj((&NTI21601), sizeof(valueerror3249));
		(*e_109394).Sup.Sup.m_type = (&NTI3249);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP226));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_109394).Sup.message), LOC217);
		raiseException((Exception*)e_109394, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_109421)(timeinfo107405* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP171));
	i = 0;
	currentf = copyString(((NimStringDesc*) &TMP171));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_109266(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP171));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += 1;
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI32)(f->Sup.len - 1));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += 1;
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = (currentf->Sup.len < 1);
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_109266(info, currentf, (&result));
					i -= 1;
					currentf = copyString(((NimStringDesc*) &TMP171));
				}
				LA18: ;
			}
			break;
			}
			i += 1;
		}
	} LA1: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
static TNimNode* TMP163[11];
static TNimNode* TMP164[12];
NI TMP166;
static char* NIM_CONST TMP165[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP167[7];
NI TMP169;
static char* NIM_CONST TMP168[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode* TMP343[2];
static TNimNode TMP148[36];
NTI107405.size = sizeof(timeinfo107405);
NTI107405.kind = 17;
NTI107405.base = (&NTI3211);
TMP163[0] = &TMP148[1];
NTI107408.size = sizeof(NI);
NTI107408.kind = 20;
NTI107408.base = (&NTI108);
NTI107408.flags = 3;
TMP148[1].kind = 1;
TMP148[1].offset = offsetof(timeinfo107405, Second);
TMP148[1].typ = (&NTI107408);
TMP148[1].name = "second";
TMP163[1] = &TMP148[2];
NTI107410.size = sizeof(NI);
NTI107410.kind = 20;
NTI107410.base = (&NTI108);
NTI107410.flags = 3;
TMP148[2].kind = 1;
TMP148[2].offset = offsetof(timeinfo107405, Minute);
TMP148[2].typ = (&NTI107410);
TMP148[2].name = "minute";
TMP163[2] = &TMP148[3];
NTI107412.size = sizeof(NI);
NTI107412.kind = 20;
NTI107412.base = (&NTI108);
NTI107412.flags = 3;
TMP148[3].kind = 1;
TMP148[3].offset = offsetof(timeinfo107405, Hour);
TMP148[3].typ = (&NTI107412);
TMP148[3].name = "hour";
TMP163[3] = &TMP148[4];
NTI107415.size = sizeof(NI);
NTI107415.kind = 20;
NTI107415.base = (&NTI108);
NTI107415.flags = 3;
TMP148[4].kind = 1;
TMP148[4].offset = offsetof(timeinfo107405, Monthday);
TMP148[4].typ = (&NTI107415);
TMP148[4].name = "monthday";
TMP163[4] = &TMP148[5];
NTI104206.size = sizeof(NU8);
NTI104206.kind = 14;
NTI104206.base = 0;
NTI104206.flags = 3;
for (TMP166 = 0; TMP166 < 12; TMP166++) {
TMP148[TMP166+6].kind = 1;
TMP148[TMP166+6].offset = TMP166;
TMP148[TMP166+6].name = TMP165[TMP166];
TMP164[TMP166] = &TMP148[TMP166+6];
}
TMP148[18].len = 12; TMP148[18].kind = 2; TMP148[18].sons = &TMP164[0];
NTI104206.node = &TMP148[18];
TMP148[5].kind = 1;
TMP148[5].offset = offsetof(timeinfo107405, Month);
TMP148[5].typ = (&NTI104206);
TMP148[5].name = "month";
TMP163[5] = &TMP148[19];
NTI107418.size = sizeof(NI);
NTI107418.kind = 20;
NTI107418.base = (&NTI108);
NTI107418.flags = 3;
TMP148[19].kind = 1;
TMP148[19].offset = offsetof(timeinfo107405, Year);
TMP148[19].typ = (&NTI107418);
TMP148[19].name = "year";
TMP163[6] = &TMP148[20];
NTI104208.size = sizeof(NU8);
NTI104208.kind = 14;
NTI104208.base = 0;
NTI104208.flags = 3;
for (TMP169 = 0; TMP169 < 7; TMP169++) {
TMP148[TMP169+21].kind = 1;
TMP148[TMP169+21].offset = TMP169;
TMP148[TMP169+21].name = TMP168[TMP169];
TMP167[TMP169] = &TMP148[TMP169+21];
}
TMP148[28].len = 7; TMP148[28].kind = 2; TMP148[28].sons = &TMP167[0];
NTI104208.node = &TMP148[28];
TMP148[20].kind = 1;
TMP148[20].offset = offsetof(timeinfo107405, Weekday);
TMP148[20].typ = (&NTI104208);
TMP148[20].name = "weekday";
TMP163[7] = &TMP148[29];
NTI107424.size = sizeof(NI);
NTI107424.kind = 20;
NTI107424.base = (&NTI108);
NTI107424.flags = 3;
TMP148[29].kind = 1;
TMP148[29].offset = offsetof(timeinfo107405, Yearday);
TMP148[29].typ = (&NTI107424);
TMP148[29].name = "yearday";
TMP163[8] = &TMP148[30];
TMP148[30].kind = 1;
TMP148[30].offset = offsetof(timeinfo107405, Isdst);
TMP148[30].typ = (&NTI138);
TMP148[30].name = "isDST";
TMP163[9] = &TMP148[31];
TMP148[31].kind = 1;
TMP148[31].offset = offsetof(timeinfo107405, Tzname);
TMP148[31].typ = (&NTI149);
TMP148[31].name = "tzname";
TMP163[10] = &TMP148[32];
TMP148[32].kind = 1;
TMP148[32].offset = offsetof(timeinfo107405, Timezone);
TMP148[32].typ = (&NTI108);
TMP148[32].name = "timezone";
TMP148[0].len = 11; TMP148[0].kind = 2; TMP148[0].sons = &TMP163[0];
NTI107405.node = &TMP148[0];
NTI107550.size = sizeof(TY107550);
NTI107550.kind = 18;
NTI107550.base = 0;
NTI107550.flags = 2;
TMP343[0] = &TMP148[34];
TMP148[34].kind = 1;
TMP148[34].offset = offsetof(TY107550, Field0);
TMP148[34].typ = (&NTI149);
TMP148[34].name = "Field0";
TMP343[1] = &TMP148[35];
TMP148[35].kind = 1;
TMP148[35].offset = offsetof(TY107550, Field1);
TMP148[35].typ = (&NTI149);
TMP148[35].name = "Field1";
TMP148[33].len = 2; TMP148[33].kind = 2; TMP148[33].sons = &TMP343[0];
NTI107550.node = &TMP148[33];
}

